"use client";

import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { useExperienceLocale } from "@/components/experience-locale-provider";

type PilotCopy = {
  title: string; intro: string; code: string; campaign: string; join: string; consent: string; participation: string;
  metrics: string; feedbackConsent: string; publication: string; accept: string; profile: string; startTask: string;
  task: string; complete: string; skip: string; feedback: string; submit: string; finish: string; declined: string;
  preliminary: string; unavailable: string; speak: string; noAudio: string; privacy: string;
};

const COPY: Record<string, PilotCopy> = {
  "zh-TW": { title: "封閉試用", intro: "這是封閉試用，不是公開競賽 demo。結果仍屬初步資料，請勿輸入真實客戶資料。", code: "試用代碼", campaign: "試用活動識別", join: "加入封閉試用", consent: "試用同意", participation: "我同意參與此試用。", metrics: "我同意收集互動與完成時間資料。", feedbackConsent: "我同意提交書面回饋。", publication: "我同意匿名回饋在審核後用於競賽證據。", accept: "接受並繼續", profile: "可選參與者輪廓", startTask: "開始試用任務", task: "目前任務", complete: "完成任務", skip: "略過並說明原因", feedback: "試用後回饋", submit: "提交回饋", finish: "完成試用", declined: "你可以繼續使用產品，但未同意的資料不會被收集。", preliminary: "試用結果初步且尚未代表一般結論。", unavailable: "試用資料目前無法使用，請稍後再試。", speak: "朗讀目前任務", noAudio: "瀏覽器朗讀為明確操作，不上傳音訊、不保存逐字稿。", privacy: "不收集地址、價格、座標、語音或原始 provider response。" },
  en: { title: "Closed pilot", intro: "This is a closed pilot, separate from the public competition demo. Results are preliminary; do not enter real client data.", code: "Pilot code", campaign: "Campaign ID", join: "Join the closed pilot", consent: "Pilot consent", participation: "I agree to participate in this pilot.", metrics: "I agree to interaction and completion-time metrics.", feedbackConsent: "I agree to submit written feedback.", publication: "I allow anonymized feedback to be used in competition evidence after review.", accept: "Accept and continue", profile: "Optional participant profile", startTask: "Start the pilot task", task: "Current task", complete: "Complete task", skip: "Skip with a reason", feedback: "Post-session feedback", submit: "Submit feedback", finish: "Complete pilot", declined: "You may continue using the product; data without consent will not be collected.", preliminary: "Pilot results are preliminary and do not represent a general conclusion.", unavailable: "Pilot evidence is temporarily unavailable. Please try again later.", speak: "Read current task aloud", noAudio: "Browser narration is explicit; no audio is uploaded and no transcript is stored.", privacy: "Addresses, prices, coordinates, speech, and raw provider responses are not collected." },
  ja: { title: "クローズド試用", intro: "公開デモとは別のクローズド試用です。結果は予備的なものです。実際の顧客データは入力しないでください。", code: "試用コード", campaign: "キャンペーン ID", join: "クローズド試用に参加", consent: "試用の同意", participation: "この試用への参加に同意します。", metrics: "操作と完了時間の計測に同意します。", feedbackConsent: "書面のフィードバック提出に同意します。", publication: "審査後、匿名フィードバックを競技用資料に使うことに同意します。", accept: "同意して続ける", profile: "任意の参加者プロフィール", startTask: "試用タスクを開始", task: "現在のタスク", complete: "タスクを完了", skip: "理由を付けてスキップ", feedback: "試用後のフィードバック", submit: "フィードバックを送信", finish: "試用を完了", declined: "同意していないデータは収集されません。", preliminary: "試用結果は予備的で、一般的な結論ではありません。", unavailable: "試用データを利用できません。後でもう一度お試しください。", speak: "現在のタスクを読み上げる", noAudio: "読み上げは明示的操作です。音声や文字起こしは保存されません。", privacy: "住所、価格、座標、音声、provider の生データは収集しません。" },
  ko: { title: "비공개 파일럿", intro: "공개 데모와 분리된 비공개 파일럿입니다. 결과는 예비적이며 실제 고객 데이터를 입력하지 마세요.", code: "파일럿 코드", campaign: "캠페인 ID", join: "비공개 파일럿 참여", consent: "파일럿 동의", participation: "이 파일럿에 참여하는 데 동의합니다.", metrics: "상호작용 및 완료 시간 측정에 동의합니다.", feedbackConsent: "서면 피드백 제출에 동의합니다.", publication: "검토 후 익명 피드백을 경쟁 자료에 사용하는 데 동의합니다.", accept: "동의하고 계속", profile: "선택적 참가자 프로필", startTask: "파일럿 과제 시작", task: "현재 과제", complete: "과제 완료", skip: "사유를 적고 건너뛰기", feedback: "세션 후 피드백", submit: "피드백 제출", finish: "파일럿 완료", declined: "동의하지 않은 데이터는 수집하지 않습니다.", preliminary: "파일럿 결과는 예비적이며 일반적인 결론이 아닙니다.", unavailable: "파일럿 데이터를 사용할 수 없습니다. 나중에 다시 시도하세요.", speak: "현재 과제 읽어주기", noAudio: "읽어주기는 명시적 동작이며 음성과 대본을 저장하지 않습니다.", privacy: "주소, 가격, 좌표, 음성 및 provider 원자료를 수집하지 않습니다." },
};

const TASKS = ["Review initial facts and change one material value.", "Open one source and limitation detail.", "Open the printable report."];
const PILOT_MODE = "closed_pilot";

export function PilotEvidenceCenter() {
  const { locale } = useExperienceLocale();
  const copy = COPY[locale] ?? COPY.en;
  const [campaignId, setCampaignId] = useState("");
  const [pilotCode, setPilotCode] = useState("");
  const [session, setSession] = useState<{ id: string; token: string }>();
  const [consent, setConsent] = useState({ participation: false, interaction_metrics: false, written_feedback: false, follow_up_contact: false, publication: false });
  const [step, setStep] = useState<"access" | "consent" | "profile" | "task" | "feedback" | "done">("access");
  const [taskIndex, setTaskIndex] = useState(0);
  const [profile, setProfile] = useState({ participant_role: "", experience_band: "", organization_type: "", case_volume_band: "", current_tools: "", device_type: "", accessibility_needs: "" });
  const [feedback, setFeedback] = useState({ task_completion: "completed", result_clarity: 3, source_clarity: 3, limitation_clarity: 3, entry_ease: 3, meeting_usefulness: 3, trust_level: 3, reuse_likelihood: 3, most_confusing_step: "", missing_capability: "", current_alternative: "", decision_maker_role: "", privacy_concern: "", required_integration: "", free_text: "", willingness_to_pay: { decision_maker: "", model: "", range: "", conditions: "" } });
  const [error, setError] = useState("");
  const [activeSeconds, setActiveSeconds] = useState(0);
  const taskLabel = useMemo(() => TASKS[taskIndex] ?? TASKS[0], [taskIndex]);

  useEffect(() => {
    let last = document.visibilityState === "visible" ? Date.now() : 0;
    const timer = window.setInterval(() => { if (document.visibilityState === "visible" && last) setActiveSeconds((value) => value + Math.min(1, Math.round((Date.now() - last) / 1000))); last = document.visibilityState === "visible" ? Date.now() : 0; }, 1000);
    const visibility = () => { last = document.visibilityState === "visible" ? Date.now() : 0; };
    document.addEventListener("visibilitychange", visibility);
    return () => { window.clearInterval(timer); document.removeEventListener("visibilitychange", visibility); };
  }, []);

  async function join() { setError(""); try { const result = await api.pilotAccess({ campaign_id: campaignId.trim(), pilot_code: pilotCode, locale, device_class: /Mobi/i.test(navigator.userAgent) ? "mobile" : "desktop", viewport_class: window.innerWidth <= 430 ? String(window.innerWidth) : "wide", workflow_id: "tax-holding-preparation" }); setSession({ id: result.session_id, token: result.session_token }); setStep("consent"); } catch { setError(copy.unavailable); } }
  async function acceptConsent() { if (!consent.participation) return; setError(""); try { await api.pilotConsent(session!.id, session!.token, consent); setStep("profile"); } catch { setError(copy.unavailable); } }
  async function saveProfile() { setError(""); try { await api.pilotProfile(session!.id, session!.token, profile); await api.pilotEvent(session!.id, session!.token, { event_type: "pilot_started", idempotency_key: `start:${session!.id}`, metadata: { step_id: "profile", visible: true } }); setStep("task"); } catch { setError(copy.unavailable); } }
  async function completeTask() { setError(""); try { await api.pilotEvent(session!.id, session!.token, { event_type: "task_completed", idempotency_key: `task:${session!.id}:${taskIndex}`, metadata: { task_id: `task-${taskIndex + 1}`, active_seconds: activeSeconds, visible: true } }); if (taskIndex < TASKS.length - 1) setTaskIndex((value) => value + 1); else setStep("feedback"); } catch { setError(copy.unavailable); } }
  async function submitFeedback() { setError(""); try { await api.pilotFeedback(session!.id, session!.token, feedback); await api.pilotComplete(session!.id, session!.token); setStep("done"); } catch { setError(copy.unavailable); } }
  function speak() { if (typeof window !== "undefined" && "speechSynthesis" in window) window.speechSynthesis.speak(new SpeechSynthesisUtterance(taskLabel)); }

  return <main className="mx-auto max-w-3xl space-y-5" data-testid="closed-pilot" aria-labelledby="pilot-heading"><header className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5"><p className="text-xs font-bold uppercase tracking-widest text-cyan-800">CLOSED PILOT · {step}</p><h1 id="pilot-heading" className="mt-2 text-2xl font-black text-slate-950">{copy.title}</h1><p className="mt-2 text-sm leading-6 text-slate-700">{copy.intro}</p><p className="mt-2 text-xs text-slate-600">{copy.privacy}</p></header>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    {step === "access" && <section className="space-y-4 rounded-2xl border border-stone-200 bg-white p-5"><h2 className="text-lg font-bold">{copy.join}</h2><label className="block text-sm font-semibold">{copy.campaign}<input value={campaignId} onChange={(event) => setCampaignId(event.target.value)} className="mt-1 w-full rounded-lg border p-2.5" maxLength={80} /></label><label className="block text-sm font-semibold">{copy.code}<input type="password" value={pilotCode} onChange={(event) => setPilotCode(event.target.value)} className="mt-1 w-full rounded-lg border p-2.5" maxLength={200} /></label><button type="button" onClick={join} disabled={!campaignId.trim() || !pilotCode} className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{copy.join}</button></section>}
    {step === "consent" && <section className="space-y-4 rounded-2xl border border-stone-200 bg-white p-5"><h2 className="text-lg font-bold">{copy.consent}</h2>{([ ["participation", copy.participation], ["interaction_metrics", copy.metrics], ["written_feedback", copy.feedbackConsent], ["publication", copy.publication] ] as const).map(([key, label]) => <label key={key} className="flex gap-3 text-sm leading-6"><input type="checkbox" checked={consent[key]} onChange={(event) => setConsent((value) => ({ ...value, [key]: event.target.checked }))} className="mt-1 h-4 w-4" />{label}</label>)}<p className="text-xs text-slate-500">{copy.noAudio}</p><button type="button" onClick={acceptConsent} disabled={!consent.participation} className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{copy.accept}</button></section>}
    {step === "profile" && <section className="space-y-4 rounded-2xl border border-stone-200 bg-white p-5"><h2 className="text-lg font-bold">{copy.profile}</h2><div className="grid gap-3 sm:grid-cols-2">{Object.entries(profile).map(([key, value]) => <label key={key} className="text-xs font-semibold text-slate-700">{key.replaceAll("_", " ")}<input value={value} onChange={(event) => setProfile((current) => ({ ...current, [key]: event.target.value }))} className="mt-1 w-full rounded-lg border p-2.5" maxLength={240} /></label>)}</div><button type="button" onClick={saveProfile} className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">{copy.startTask}</button></section>}
    {step === "task" && <section className="space-y-4 rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs font-bold text-cyan-800">{copy.task} {taskIndex + 1} / {TASKS.length}</p><h2 className="text-xl font-bold text-slate-950">{taskLabel}</h2><div className="h-2 rounded-full bg-stone-100"><div className="h-2 rounded-full bg-cyan-600" style={{ width: `${((taskIndex + 1) / TASKS.length) * 100}%` }} /></div><div className="flex flex-wrap gap-2"><button type="button" onClick={completeTask} className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">{copy.complete}</button><button type="button" onClick={() => setTaskIndex((value) => Math.min(TASKS.length - 1, value + 1))} className="rounded-lg border px-4 py-2.5 text-sm font-bold">{copy.skip}</button><button type="button" onClick={speak} className="rounded-lg border px-4 py-2.5 text-sm font-bold">{copy.speak}</button></div><p className="text-xs text-slate-500">{copy.noAudio}</p></section>}
    {step === "feedback" && <section className="space-y-4 rounded-2xl border border-stone-200 bg-white p-5"><h2 className="text-lg font-bold">{copy.feedback}</h2><div className="grid gap-3 sm:grid-cols-2">{([ ["result_clarity", "Result clarity"], ["source_clarity", "Source clarity"], ["limitation_clarity", "Limitation clarity"], ["entry_ease", "Ease of entering facts"], ["meeting_usefulness", "Usefulness before a client meeting"], ["trust_level", "Trust level"], ["reuse_likelihood", "Likelihood of using again"] ] as const).map(([key, label]) => <label key={key} className="text-xs font-semibold">{label}<select value={feedback[key]} onChange={(event) => setFeedback((current) => ({ ...current, [key]: Number(event.target.value) }))} className="mt-1 w-full rounded-lg border p-2.5">{[1, 2, 3, 4, 5].map((value) => <option key={value} value={value}>{value}</option>)}</select></label>)}</div><textarea value={feedback.free_text} onChange={(event) => setFeedback((current) => ({ ...current, free_text: event.target.value }))} maxLength={2000} className="min-h-28 w-full rounded-lg border p-2.5" aria-label="Optional feedback" /><button type="button" onClick={submitFeedback} className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">{copy.submit}</button></section>}
    {step === "done" && <section role="status" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="text-lg font-bold">{copy.finish}</h2><p className="mt-2 text-sm leading-6">{copy.preliminary}</p><p className="mt-2 text-xs text-slate-600">{copy.declined}</p></section>}
  </main>;
}

export function ProfessionalReviewCenter() {
  const { locale } = useExperienceLocale();
  const labels = { "zh-TW": ["專業審查模式", "此記錄只適用於指定版本與範圍。提交後維持私有，不代表公開背書。"], en: ["Professional review mode", "This record applies only to the recorded version and scope. Submission stays private and is not public endorsement."], ja: ["専門レビュー", "この記録は指定されたバージョンと範囲だけに適用されます。公開推薦ではありません。"], ko: ["전문가 검토 모드", "이 기록은 지정된 버전과 범위에만 적용됩니다. 공개 추천이 아닙니다."] }[locale] ?? ["Professional review mode", "This record stays private."];
  return <section className="mx-auto max-w-3xl space-y-4" data-testid="professional-review"><div className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><p className="text-xs font-bold uppercase tracking-widest text-violet-800">PROFESSIONAL REVIEW</p><h1 className="mt-2 text-2xl font-black">{labels[0]}</h1><p className="mt-2 text-sm leading-6">{labels[1]}</p></div><p className="rounded-xl border border-stone-200 bg-white p-5 text-sm leading-6 text-slate-700">Reviewers can inspect customer wording, rule version, official source metadata, example inputs, expected outcome and limitations. Reviewer names remain private unless separately consented, and qualification is not treated as verified without evidence.</p></section>;
}
