import Link from "next/link";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ViewingDecisionReportCard } from "@/components/viewing-decision-report-card";
import type { ModuleSlug } from "@/lib/viewing-decision";

const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";

type ReportPageProps = {
  moduleName: string;
  moduleSlug: ModuleSlug;
  assessmentId: string;
  backHref: string;
};

export function ReportPage({
  moduleName,
  moduleSlug,
  assessmentId,
  backHref,
}: ReportPageProps) {
  const reportUrl = `${apiBaseUrl}/api/${moduleSlug}/assessments/${assessmentId}/report`;
  const pdfUrl = `${apiBaseUrl}/api/${moduleSlug}/assessments/${assessmentId}/report.pdf`;

  return (
    <main className="mx-auto grid min-h-screen max-w-7xl gap-6 px-4 py-6 sm:px-6 sm:py-8">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <p className="text-sm text-muted-foreground">PropGuard AI Report</p>
          <h1 className="break-words text-2xl font-semibold leading-tight">
            {moduleName} #{assessmentId}
          </h1>
        </div>
        <div className="grid gap-2 sm:flex sm:shrink-0">
          <Button asChild className="w-full sm:w-auto" variant="outline">
            <Link href={backHref}>Back</Link>
          </Button>
          <Button asChild className="w-full sm:w-auto">
            <a href={pdfUrl}>Export PDF</a>
          </Button>
        </div>
      </div>

      <ViewingDecisionReportCard
        assessmentId={assessmentId}
        moduleName={moduleName}
        moduleSlug={moduleSlug}
      />

      <Card>
        <CardHeader>
          <CardTitle>Report Preview</CardTitle>
          <CardDescription>HTML report generated by the backend template.</CardDescription>
        </CardHeader>
        <CardContent>
          <iframe
            className="h-[70vh] min-h-[460px] w-full rounded-md border bg-white sm:h-[760px]"
            src={reportUrl}
            title={`${moduleName} report preview`}
          />
        </CardContent>
      </Card>
    </main>
  );
}
