import type { HoldingCostResult } from "@/lib/api";
import type { HoldingCostVisualModel } from "@/lib/holding-cost-visualization";
import { MetricTile, SectionCard } from "@/components/product-ui";
import { DetailDisclosure } from "@/components/detail-disclosure";
import { AffordabilityStatus } from "./affordability-status";
import { HoldingCostBreakdownChart } from "./holding-cost-breakdown-chart";
import { VisualDataUnavailableState } from "./visual-data-unavailable-state";

export function HoldingCostVisualPanel({ model, result }: { model: HoldingCostVisualModel; result: HoldingCostResult }) {
  if (model.state !== "available") return <VisualDataUnavailableState message={model.summary} />;
  return <div className="min-w-0 space-y-4"><SectionCard title="持有成本摘要"><p className="text-sm leading-6 text-slate-700">{model.summary}</p><div className="mt-3"><AffordabilityStatus value={model.affordability} /></div></SectionCard><div className="grid gap-3 sm:grid-cols-2"><MetricTile label="每月總持有成本" value={`${model.metrics.monthlyTotal?.toLocaleString()} 元`} /><MetricTile label="年持有成本" value={`${model.metrics.annualTotal?.toLocaleString()} 元`} /><MetricTile label="月收入負擔率" value={model.metrics.incomeBurden === null ? "未輸入收入" : `${(model.metrics.incomeBurden * 100).toFixed(1)}%`} /><MetricTile label="每年簡化稅費估算" value={model.metrics.annualTaxEstimate === null ? "尚無可用資料" : `${model.metrics.annualTaxEstimate.toLocaleString()} 元`} /></div><HoldingCostBreakdownChart model={model} /><SectionCard title="主要成本來源"><ul className="grid gap-2 text-xs text-slate-700 sm:grid-cols-2">{model.breakdown.slice(0, 4).map((item) => <li key={item.key} className="rounded-lg bg-stone-50 px-3 py-2.5"><strong>{item.label}</strong>：{item.monthlyAmount.toLocaleString()} 元／月</li>)}</ul></SectionCard><DetailDisclosure title="查看完整成本明細與計算假設"><div className="space-y-3 text-xs text-slate-700"><dl className="grid gap-2 sm:grid-cols-2">{model.evidence.map((item) => <div key={item.key}><dt className="font-bold text-slate-800">{item.label}</dt><dd>{item.value}</dd></div>)}</dl><div className="max-w-full overflow-x-auto"><table className="w-full min-w-[520px] text-left"><thead><tr className="bg-stone-50"><th className="p-2">項目</th><th>每月金額</th><th>占總成本</th></tr></thead><tbody>{model.breakdown.map((item) => <tr key={item.key} className="border-t border-stone-100"><td className="p-2">{item.label}</td><td>{item.monthlyAmount.toLocaleString()} 元</td><td>{item.percentage === null ? "無法計算占比" : `${item.percentage.toFixed(1)}%`}</td></tr>)}</tbody></table></div><p>房屋稅與地價稅為簡化估算；管理費與修繕金來自本次輸入假設，實際費用可能不同，不是正式稅務或財務意見。</p><p>{result.disclaimer}</p></div></DetailDisclosure></div>;
}
