"use client";

import { DUE_DILIGENCE_STATUS_LABELS, groupDueDiligenceItems, type DueDiligenceItem, type DueDiligenceReadinessResult } from "@/lib/property-case-due-diligence";
import { useExperienceLocale } from "@/components/experience-locale-provider";
import { getLocalizedStructuredLabel } from "@/lib/structured-options";

export function PropertyCaseDueDiligenceMatrix({ items, readiness }: { items: DueDiligenceItem[]; readiness: DueDiligenceReadinessResult }) {
  const { locale, copy } = useExperienceLocale();
  return <section className="rounded-2xl border border-stone-200 bg-white p-4" aria-label={getLocalizedStructuredLabel("due_diligence", locale)}><div><p className="text-xs font-bold text-slate-500">DUE DILIGENCE</p><h3 className="mt-1 text-sm font-black text-slate-900">{getLocalizedStructuredLabel("due_diligence", locale)}</h3><p className="mt-1 text-xs text-slate-600">{getLocalizedStructuredLabel("reviewing", locale)} / {getLocalizedStructuredLabel("blocked", locale)} / {getLocalizedStructuredLabel("not_applicable", locale)}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><Stat label={getLocalizedStructuredLabel("confirmed", locale)} value={readiness.confirmed_count} /><Stat label={getLocalizedStructuredLabel("reviewing", locale)} value={readiness.reviewing_count} /><Stat label={getLocalizedStructuredLabel("blocked", locale)} value={readiness.blocked_count} /><Stat label={getLocalizedStructuredLabel("not_applicable", locale)} value={readiness.not_applicable_count} /></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{groupDueDiligenceItems(items).map((group) => <article key={group.category_id} className="rounded-xl border border-stone-200 bg-stone-50 p-3"><h4 className="text-xs font-bold text-slate-900">{getLocalizedStructuredLabel(group.category_id, locale)}</h4><ul className="mt-2 space-y-2">{group.items.map((item) => <li key={item.item_id} className="flex items-start justify-between gap-2 text-[11px]"><span className="min-w-0 text-slate-700">{item.label}</span><span className={`shrink-0 rounded-full px-2 py-0.5 font-bold ${statusTone(item.status)}`}>{getLocalizedStructuredLabel(item.status, locale)}</span></li>)}</ul></article>)}</div><details className="mt-4 rounded-xl border border-stone-200"><summary className="cursor-pointer px-3 py-2 text-xs font-bold text-slate-700">{copy("viz.evidenceDetailsTitle")}</summary><ul className="space-y-2 border-t border-stone-200 p-3 text-[11px] leading-5 text-slate-600">{items.map((item) => <li key={item.item_id}><strong>{item.label}</strong>: {item.note || copy("viz.dueDiligenceNoNote")}; {copy("wizard.nextAction")}: {item.next_action || copy("viz.dueDiligenceNextNotProvided")}</li>)}</ul></details></section>;
}

function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-stone-50 p-2 text-center"><p className="text-[10px] text-slate-500">{label}</p><p className="mt-1 text-lg font-black text-slate-900">{value}</p></div>; }
function statusTone(status: string): string { return status === "blocked" ? "bg-rose-100 text-rose-800" : status === "confirmed" ? "bg-emerald-100 text-emerald-800" : status === "not_applicable" ? "bg-slate-100 text-slate-700" : "bg-amber-100 text-amber-800"; }
