"use client";

import type { CaseMilestone, TimelineEvent, TimelineReadinessResult } from "@/lib/property-case-timeline";
import { CASE_MILESTONE_TEMPLATE } from "@/lib/property-case-timeline";
import { useExperienceLocale } from "@/components/experience-locale-provider";

export function PropertyCaseTimelineChart({ events, milestones, readiness }: { events: TimelineEvent[]; milestones: CaseMilestone[]; readiness: TimelineReadinessResult }) {
  const { copy } = useExperienceLocale();
  return <section className="rounded-2xl border border-stone-200 bg-white p-4" aria-label={copy("viz.timelineTitle")}><div><p className="text-xs font-bold text-slate-500">{copy("viz.timelineKicker")}</p><h3 className="mt-1 text-sm font-black text-slate-900">{copy("viz.timelineTitle")}</h3><p className="mt-1 text-xs text-slate-600">{copy("viz.timelineDesc")}</p></div><div className="mt-4 rounded-xl border border-cyan-100 bg-cyan-50 p-3" role="img" aria-label={copy("viz.timelineMilestoneLabel")}><div className="flex h-3 gap-1 overflow-hidden rounded-full bg-white">{milestones.map((milestone) => <span key={milestone.milestone_id} className={`h-full flex-1 ${milestone.is_done ? "bg-cyan-600" : "bg-slate-200"}`} />)}</div><p className="mt-2 text-xs text-cyan-900">{readiness.milestone_done_count} / {milestones.length} {copy("viz.timelineMilestoneDone")}; {readiness.event_count} events</p></div><ol className="mt-4 space-y-3">{events.length ? events.map((event) => <li key={event.id} className="rounded-xl border border-stone-200 p-3"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-stone-100 px-2 py-1 text-[10px] font-bold text-slate-700">{event.event_date || copy("viz.timelineDateNotProvided")}</span><strong className="text-xs text-slate-900">{event.title}</strong></div><p className="mt-1 text-[11px] leading-5 text-slate-600">{event.summary || copy("viz.timelineNoSummary")}</p></li>) : <li className="rounded-xl border border-dashed border-stone-200 p-3 text-xs text-slate-500">{copy("viz.timelineNoEvents")}</li>}</ol><details className="mt-4 rounded-xl border border-stone-200"><summary className="cursor-pointer px-3 py-2 text-xs font-bold text-slate-700">{copy("viz.timelineMilestoneDetails")}</summary><ul className="space-y-2 border-t border-stone-200 p-3 text-[11px] text-slate-600">{milestones.map((milestone) => <li key={milestone.milestone_id}><strong>{CASE_MILESTONE_TEMPLATE.find((item) => item.milestone_id === milestone.milestone_id)?.label ?? milestone.milestone_id}</strong>: {milestone.is_done ? copy("viz.timelineMilestoneCompleted") : copy("viz.timelineMilestoneNotCompleted")}{milestone.done_date ? ` · ${milestone.done_date}` : ` · ${copy("viz.timelineDateNotProvided")}`}</li>)}</ul></details></section>;
}
