"use client";

import { useState } from "react";
import { readSavedCases, type SavedCase } from "@/lib/case-storage";
import { buildPropertyCaseComparisonModel } from "@/lib/property-case-comparison";

export function PropertyCaseComparisonWorkbench() {
  const [savedCases, setSavedCases] = useState<SavedCase[]>([]);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [open, setOpen] = useState(false);
  const model = buildPropertyCaseComparisonModel(savedCases, selectedIds);
  function loadCases() { setSavedCases(readSavedCases()); setSelectedIds([]); setOpen(true); }
  function toggle(id: string) { setSelectedIds((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length >= 3 ? current : [...current, id]); }
  return <section className="rounded-2xl border border-stone-200 bg-white p-4" aria-label="案件比較工作台"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold text-slate-500">CASE COMPARISON</p><h3 className="mt-1 text-sm font-black text-slate-900">案件比較工作台</h3><p className="mt-1 text-xs text-slate-600">只比較使用者明確勾選的 2–3 個已儲存案件，不產生總分、排名或推薦。</p></div><button type="button" onClick={loadCases} className="shrink-0 rounded-lg bg-cyan-700 px-3 py-2 text-xs font-bold text-white">載入已儲存案件</button></div>{open && <div className="mt-4 border-t border-stone-100 pt-4"><p className="mb-3 text-xs text-slate-600">資料不足時僅比較已知欄位，並保留每個案件的待補資料數量。</p>{savedCases.length === 0 ? <p className="rounded-xl bg-stone-50 p-3 text-xs text-slate-600">目前沒有可供明確選取的已儲存案件。</p> : <><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{savedCases.map((saved) => <label key={saved.id} className="flex min-w-0 items-start gap-2 rounded-xl border border-stone-200 p-3 text-xs"><input type="checkbox" checked={selectedIds.includes(saved.id)} onChange={() => toggle(saved.id)} disabled={!selectedIds.includes(saved.id) && selectedIds.length >= 3} aria-label={`選取案件 ${saved.title}`} /><span className="min-w-0"><strong className="block truncate text-slate-900">{saved.title || "未命名案件"}</strong><span className="mt-1 block truncate text-slate-500">{[saved.inputSummary.city, saved.inputSummary.district, saved.inputSummary.road].filter(Boolean).join("") || "未提供地址／識別"}</span></span></label>)}</div><p className="mt-3 text-xs font-bold text-cyan-800" role="status">已選取 {selectedIds.length} / 3；{model.message}</p>{model.canCompare && <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{model.rows.map((row) => <article key={row.caseId} className="min-w-0 rounded-xl border border-cyan-100 bg-cyan-50/50 p-3"><h4 className="truncate text-sm font-black text-slate-900">{row.caseName}</h4><p className="mt-1 truncate text-[11px] text-slate-600">{row.addressSummary}</p><dl className="mt-3 space-y-2 text-[11px]"><Row label="案件狀態" value={row.decisionStatus} /><Row label="開價" value={format(row.listingPrice, "萬元")} /><Row label="使用者估計價值" value={format(row.userEstimatedValue, "萬元")} /><Row label="初期現金需求" value={format(row.initialCashNeeded, "萬元")} /><Row label="每月月付" value={format(row.monthlyPayment, "元")} /><Row label="每月持有成本" value={format(row.monthlyHoldingCost, "元")} /><Row label="財務資料" value={row.financialStatus} /><Row label="盡職調查" value={row.dueDiligenceReadiness} /><Row label="看屋／出價" value={row.viewingOfferReadiness} /><Row label="時間軸" value={row.timelineReadiness} /><Row label="缺失資料" value={`${row.missingDataCount} 項`} /></dl></article>)}</div>}</>}</div>}</section>;
}

function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-2"><dt className="text-slate-600">{label}</dt><dd className="text-right font-bold text-slate-900">{value}</dd></div>; }
function format(value: number | null, unit: string): string { return value === null ? "未提供" : `${value.toLocaleString()} ${unit}`; }
