import type { TaxResult, TaxCase } from "@/lib/api";
import { Button } from "@/components/ui";
import { ErrorState, MetricTile, ResultSummaryPanel, SectionCard } from "@/components/product-ui";
import { buildTaxVisualModel } from "@/lib/tax-visualization";
import { DetailDisclosure } from "@/components/detail-disclosure";
import { TaxReminderTimeline } from "./tax-reminder-timeline";
import { TaxRiskGauge } from "./tax-risk-gauge";
import { TaxRuleOutcomeChart } from "./tax-rule-outcome-chart";

export function TaxDecisionVisualPanel({ result, taxCase, downloading, error, onDownload }: { result: TaxResult; taxCase?: TaxCase; downloading: boolean; error: string; onDownload: () => void }) {
  const model = buildTaxVisualModel(result);
  return <ResultSummaryPanel><div className="border-b border-stone-100 px-5 py-4"><p className="text-[10px] font-bold tracking-wider text-slate-400">TAXORACLE DECISION SUMMARY</p><h2 className="mt-1 font-bold text-slate-950">稅務資格與複核摘要</h2><p className="mt-1 text-xs text-slate-500">結論來自既有 TX001–TX009 規則，不是律師、會計師或稅務機關正式意見。</p></div><div className="space-y-4 p-5"><div className="grid gap-4 lg:grid-cols-[170px_minmax(0,1fr)]"><TaxRiskGauge model={model} /><div><p className="text-xs font-bold text-slate-500">資格／複核結論</p><p className="mt-1 text-2xl font-bold text-slate-950">{model.eligibility.label}</p><p className="mt-2 text-sm leading-6 text-slate-700">{model.eligibility.message}</p><p className="mt-2 text-sm leading-6 text-slate-600">{result.ai_explanation.headline}</p></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="未通過規則" value={model.counts.failed} /><MetricTile label="需複核規則" value={model.counts.manualReview} /><MetricTile label="通過規則" value={model.counts.passed} /><MetricTile label="缺少文件" value={model.counts.missingDocs} /></div><TaxRuleOutcomeChart model={model} /><SectionCard title="關鍵命中規則"><ul className="space-y-2 text-xs text-slate-700">{model.keyRules.length ? model.keyRules.map((item) => <li key={item.code} className="rounded-lg bg-stone-50 p-3"><strong className="text-cyan-800">{item.code} · {item.title}</strong><p className="mt-1">{item.outcome}：{item.detail}</p></li>) : <li>目前沒有回傳未通過或需複核規則。</li>}</ul></SectionCard><TaxReminderTimeline model={model} /><DetailDisclosure title="查看 AI 客戶溝通內容與完整使用限制"><div className="space-y-3 text-xs leading-5 text-slate-700"><p>{result.ai_explanation.customer_script}</p><p>{result.disclaimer}</p></div></DetailDisclosure><Button onClick={onDownload} disabled={downloading || !taxCase} className="w-full bg-cyan-700 hover:bg-cyan-800">{downloading ? "正在呼叫報告 API..." : "下載 TaxOracle HTML 報告"}</Button>{error && <ErrorState message={error} />}</div></ResultSummaryPanel>;
}
