import type { ExperienceLocale } from "./experience-i18n";
// @ts-expect-error Native TS runner extension.
import { formatAreaPing } from "./commercial/formatters.ts";

const keys = ["title", "included", "excluded", "considered", "examples", "counts", "unknown", "target", "value", "difference", "threshold", "scope", "ranking", "weight", "outlier", "context", "location", "building_type", "area", "age", "distance", "recency", "unit_price", "floor", "parking", "selected", "time_window", "official_source", "required_metrics", "price_outlier", "rank_limit", "insufficient_samples", "rules", "limits", "coverage", "unavailable", "stale", "reference", "window", "recencyReference", "distanceMethod", "parkingLimit", "missingLimit", "selectionLimit", "orderRule", "scoreRule", "outlierRule", "fallbackRule", "geographyRule", "report", "bound", "ping", "metres", "months", "years", "priceUnit", "none", "community", "road", "district", "city", "fallback", "tower", "midrise", "apartment", "townhouse", "studio"] as const;
type Copy = Record<typeof keys[number] | "community_distance" | "community_distance_unknown" | "community_distance_label" | "eligibilityRule", string>;
const communityCopy: Record<ExperienceLocale, [string, string, string, string]> = {
  "zh-TW": ["距同社區參考點超過 600 公尺", "缺少同社區距離證據", "同社區參考點距離", "官方來源、有效期別，以及有限且大於零的面積、總價與單價是官方候選必要條件。"],
  en: ["Beyond 600 m from the community reference", "Community distance evidence missing", "Distance from community reference", "Official candidates require an official source, valid period, and finite positive area, total price and unit price."],
  ja: ["団地基準点から600m超", "団地距離の根拠が不足", "団地基準点からの距離", "公式候補は公式出典・有効な期・有限かつ正の面積、総額、単価が必要です。"],
  ko: ["단지 기준점에서 600m 초과", "단지 거리 근거 누락", "단지 기준점 거리", "공식 후보는 공식 출처, 유효한 기간, 유한한 양수 면적과 총액 및 단가가 필요합니다."],
};
const resources: Record<ExperienceLocale, readonly string[]> = {
  "zh-TW": [
    "為何採用這些可比成交？", "已採用", "已排除", "已檢視候選", "排除範例", "排除原因計數", "未知", "目標", "成交", "差異", "規則範圍", "範圍篩選", "排序使用", "權重使用", "單價離群檢查", "僅供背景參考", "位置", "建物類型", "面積", "屋齡", "距離", "成交期別／月數", "成交單價", "樓層", "停車處理", "通過範圍與最終排序，納入最多十筆", "超出官方期間或期別無效", "不是官方成交來源", "必要面積或價格證據缺失／無效", "單價超出 IQR 範圍", "通過檢查但未進入前十筆", "不足三筆可用成交", "選取規則", "方法限制", "僅涵蓋供應端回傳的候選；SQL 已排除或因 200 筆上限未回傳的交易與計數未知。多重原因計數可能重疊。", "未保存有效決策軌跡；無法從估價摘要重建原因。", "這是先前條件的選取證據；不代表目前物件的可比成交。", "官方期間基準（UTC）", "官方可用期間", "排序／權重日期基準", "近似直線距離；不是步行或道路距離，沒有一般距離排除門檻。", "車位是否包含、分開計價或無車位皆未知；未用於選取，也未新增車位扣價。", "來源缺失的屋齡／樓層顯示未知；既有估價可能使用零值預設，說明不會視為已知。", "採用不代表正確或同質；排序分數不是可信度，不能取代專業鑑價。", "先依同路段／來源、建物類型、面積差、較近期別及既有相似分數排序，最多十筆。面積／型態不同不直接排除。", "既有權重分數：可能同社區 15、同路段 35、同行政區 20、同縣市 10、同型態 15；面積 max(0,10−差異/max(目標,1)×20)、屋齡 max(0,8−差異/4)、距離 max(0,7−公尺/800)、期間 max(0,5−月数/12)，未來期別為 0；總分上限 100，權重至少 0.05。", "單價規則：Q1−1.5×IQR 至 Q3+1.5×IQR。少於四筆不篩；特定官方保留模式可略過。", "離群檢查後少於三筆時，恢復原候選再排序。", "官方同路段至少三筆，否則改用同區其他路段，再改同縣市；展示資料可採同社區 600 公尺，再依路段／行政區／縣市回退。", "可比成交選取摘要", "最多五筆，依決策觀察順序；不是所有被排除交易。", "坪", "公尺", "個月", "年", "萬元／坪", "無可用範圍", "同社區範圍", "同路段", "同行政區", "同縣市", "展示回退", "住宅大樓", "華廈", "公寓", "透天厝", "套房",
  ],
  en: [
    "Why these comparables?", "Included", "Excluded", "Candidates considered", "Excluded examples", "Exclusion reason counts", "Unknown", "Target", "Transaction", "Difference", "Rule range", "Scope selection", "Used in ranking", "Used in weighting", "Price outlier check", "Context only", "Location", "Building type", "Area", "Building age", "Distance", "Transaction period / months", "Unit price", "Floor", "Parking treatment", "Passed scope and final ranking; up to ten selected", "Outside official window or invalid period", "Not an official transaction source", "Required area or price evidence missing / invalid", "Unit price outside IQR bounds", "Passed checks but outside the top ten", "Fewer than three usable transactions", "Selection rules", "Method limitations", "Only candidates returned by the provider are counted. SQL exclusions and transactions beyond its 200-row limit are unknown. Multiple reason counts can overlap.", "No valid decision trace was saved; reasons cannot be reconstructed from a valuation summary.", "Selection evidence belongs to earlier inputs; these are not comparables for the current property.", "Official window reference (UTC)", "Official allowed window", "Ranking / weighting date reference", "Approximate straight-line distance, not walking or road distance. No general distance rejection threshold.", "Included, separately priced or absent parking are unknown. Parking is not used in selection; no parking adjustment is added.", "Missing source age / floor remain unknown. Existing valuation may use zero defaults; explanation does not treat them as known.", "Inclusion does not establish correctness or equivalence. Ranking scores are not confidence; professional appraisal is still needed.", "Order: same road / source, building type, area difference, newer period, then existing similarity score; at most ten. Area / type differences do not directly reject.", "Existing weight score: probable community 15, same road 35, district 20, city 10, type 15; area max(0,10−difference/max(target,1)×20), age max(0,8−difference/4), distance max(0,7−metres/800), period max(0,5−months/12), future period 0. Score capped at 100; minimum weight 0.05.", "Unit-price rule: Q1−1.5×IQR to Q3+1.5×IQR. No filtering below four rows; an existing official-preservation mode can bypass it.", "If fewer than three survive the outlier check, restore the original candidates and rank again.", "Official scope needs three same-road rows; otherwise other roads in the district, then city. Demo can use a 600 m community scope, then road / district / city fallback.", "Comparable selection summary", "At most five, in decision observation order; not all excluded transactions.", "ping", "m", "months", "years", "NT$10k/ping", "No usable scope", "Community scope", "Same road", "Same district", "Same city", "Demo fallback", "Residential tower", "Mid-rise", "Apartment", "Townhouse", "Studio",
  ],
  ja: [
    "これらの比較成約を採用した理由", "採用", "除外", "確認した候補", "除外例", "除外理由の件数", "不明", "対象", "成約", "差", "規則範囲", "範囲選択", "順位付けに使用", "重みに使用", "単価外れ値確認", "参考情報のみ", "位置", "建物タイプ", "面積", "築年数", "距離", "成約期／月数", "成約単価", "階", "駐車場の扱い", "範囲と最終順位を通過し最大十件を採用", "公式期間外または無効な期", "公式成約の出典ではない", "必要な面積・価格情報が欠落または無効", "単価が IQR 範囲外", "確認通過後も上位十件に入らない", "利用可能な成約が三件未満", "選択規則", "方法の制約", "出典から返された候補のみ集計。SQL 除外や二百件の上限を超える取引・件数は不明。複数理由の件数は重複します。", "有効な決定記録が保存されていないため、評価摘要から理由は再構成できません。", "以前の条件の選択記録です。現在の物件の比較成約を意味しません。", "公式期間基準（UTC）", "公式の許容期間", "順位・重みの日付基準", "概算の直線距離であり、徒歩・道路距離ではありません。一般的な距離除外基準はありません。", "駐車場込み・別価格・なしの区別は不明。選択には使用せず、駐車場価格の調整も追加しません。", "出典で欠落する築年数・階は不明のまま。既存評価がゼロを既定値にしても、説明では既知としません。", "採用は正確さや同等性を保証しません。順位点は信頼度ではなく、専門鑑定が必要です。", "同道路・出典、建物タイプ、面積差、新しい期、既存類似点の順に最大十件。面積・タイプの相違だけでは除外しません。", "既存の重み点：推定同団地15、同道路35、同区20、同市10、同型15。面積max(0,10−差/max(対象,1)×20)、築年数max(0,8−差/4)、距離max(0,7−m/800)、期間max(0,5−月数/12)、未来期0。点数上限100、重み下限0.05。", "単価規則：Q1−1.5×IQR～Q3+1.5×IQR。四件未満は除外せず、既存の公式成約保持モードは通過可能。", "外れ値確認後に三件未満なら元の候補を戻して順位付けします。", "公式は同道路三件以上、なければ同区の他道路、次に同市。展示は団地600m、道路・区・市へ範囲を広げます。", "比較成約選択の摘要", "決定観測順に最大五件。除外取引の全件ではありません。", "坪", "m", "か月", "年", "万NTD／坪", "利用可能な範囲なし", "団地範囲", "同道路", "同区", "同市", "展示代替", "高層住宅", "中層住宅", "アパート", "戸建て", "ワンルーム",
  ],
  ko: [
    "이 비교 거래를 선택한 이유", "포함", "제외", "검토한 후보", "제외 예시", "제외 사유 건수", "알 수 없음", "대상", "거래", "차이", "규칙 범위", "범위 선택", "순위에 사용", "가중치에 사용", "단가 이상치 확인", "참고 정보만", "위치", "건물 유형", "면적", "건물 연령", "거리", "거래 기간 / 개월", "거래 단가", "층", "주차 처리", "범위와 최종 순위를 통과하여 최대 열 건 포함", "공식 기간 밖 또는 잘못된 기간", "공식 거래 출처가 아님", "필수 면적 또는 가격 근거 누락 / 무효", "단가가 IQR 범위 밖", "검사를 통과했지만 상위 열 건 밖", "사용 가능한 거래가 세 건 미만", "선택 규칙", "방법의 한계", "출처가 반환한 후보만 집계합니다. SQL 제외나 이백 건 한도 밖 거래 및 건수는 알 수 없습니다. 여러 사유의 건수는 중복될 수 있습니다.", "유효한 결정 기록이 저장되지 않아 평가 요약에서 사유를 재구성할 수 없습니다.", "이전 조건의 선택 근거이며 현재 물건의 비교 거래를 의미하지 않습니다.", "공식 기간 기준 (UTC)", "공식 허용 기간", "순위 / 가중치 날짜 기준", "근사 직선거리이며 도보나 도로 거리가 아닙니다. 일반적인 거리 제외 기준은 없습니다.", "주차 포함, 별도 가격, 주차 없음은 알 수 없습니다. 선택에 사용하지 않으며 주차 가격 조정을 추가하지 않습니다.", "출처 연령 / 층 누락은 알 수 없음으로 유지합니다. 기존 평가는 기본값 0을 쓸 수 있으나 설명은 알려진 값으로 보지 않습니다.", "포함이 정확성이나 동등성을 보장하지 않습니다. 순위 점수는 신뢰도가 아니며 전문 감정이 필요합니다.", "같은 도로 / 출처, 건물 유형, 면적 차이, 최근 기간, 기존 유사 점수 순으로 최대 열 건. 면적 / 유형 차이만으로 제외하지 않습니다.", "기존 가중 점수: 추정 같은 단지15, 도로35, 구20, 시10, 유형15. 면적max(0,10−차이/max(대상,1)×20), 연령max(0,8−차이/4), 거리max(0,7−m/800), 기간max(0,5−개월/12), 미래기간0. 점수 상한100, 가중치 최소0.05.", "단가 규칙: Q1−1.5×IQR부터 Q3+1.5×IQR까지. 네 건 미만은 필터링하지 않으며 기존 공식 거래 보존 모드는 통과할 수 있습니다.", "이상치 확인 후 세 건 미만이면 원래 후보를 복원하고 순위를 매깁니다.", "공식 범위는 같은 도로 세 건 이상, 없으면 같은 구의 다른 도로, 다음 같은 시. 데모는 단지600m부터 도로 / 구 / 시로 확장합니다.", "비교 거래 선택 요약", "결정 관측 순서로 최대 다섯 건이며 모든 제외 거래는 아닙니다.", "평", "m", "개월", "년", "만NTD/평", "사용 가능한 범위 없음", "단지 범위", "같은 도로", "같은 구", "같은 시", "데모 대체", "고층 주택", "중층 주택", "아파트", "단독 주택", "원룸",
  ],
};
export function comparableCopy(locale: ExperienceLocale): Copy {
  return { ...Object.fromEntries(keys.map((key, i) => [key, resources[locale][i]])), community_distance: communityCopy[locale][0], community_distance_unknown: communityCopy[locale][1], community_distance_label: communityCopy[locale][2], eligibilityRule: communityCopy[locale][3] } as Copy;
}
export function formatComparableValue(value: string | number | null, dimension: string, locale: ExperienceLocale): string {
  const c = comparableCopy(locale);
  if (value === null) return c.unknown;
  if (typeof value === "string") {
    const typeKeys: Record<string, keyof Copy> = { "住宅大樓": "tower", "華廈": "midrise", "公寓": "apartment", "透天厝": "townhouse", "套房": "studio" };
    return dimension === "building_type" && typeKeys[value] ? c[typeKeys[value]] : value;
  }
  // The workspace currently uses canonical ping; reuse its precision formatter.
  if (dimension === "area") return `${formatAreaPing(value).replace(/ 坪$/, "")} ${c.ping}`;
  const n = new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(value);
  const unit = { age: c.years, distance: c.metres, community_distance: c.metres, recency: c.months, unit_price: c.priceUnit }[dimension];
  return unit ? `${n} ${unit}` : n;
}
