import type { ExperienceLocale } from "@/lib/experience-i18n";

// Guide resources join the existing runtime-copy catalogue; components use copy().
export const GUIDED_TOUR_COPY_KEYS = [
  "guide.title", "guide.path", "guide.progress", "guide.next", "guide.back",
  "guide.skip", "guide.finish", "guide.restart", "guide.context", "guide.boundary",
  "guide.property.label", "guide.property.heading", "guide.property.description",
  "guide.market.label", "guide.market.heading", "guide.market.description",
  "guide.location.label", "guide.location.heading", "guide.location.description",
  "guide.risk.label", "guide.risk.heading", "guide.risk.description",
  "guide.finance.label", "guide.finance.heading", "guide.finance.description",
  "guide.verify.label", "guide.verify.heading", "guide.verify.description",
  "guide.save.label", "guide.save.heading", "guide.save.description",
] as const;
export type GuidedTourCopyKey = typeof GUIDED_TOUR_COPY_KEYS[number];

export const GUIDED_TOUR_COPY: Record<ExperienceLocale, Record<GuidedTourCopyKey, string>> = {
  "zh-TW": {
    "guide.title": "物件決策導覽", "guide.path": "決策流程", "guide.progress": "第 {{current}} 步，共 {{total}} 步",
    "guide.next": "下一步", "guide.back": "上一步", "guide.skip": "略過導覽", "guide.finish": "完成導覽", "guide.restart": "重新開啟導覽",
    "guide.context": "這是流程導覽。關閉後，可在工作區依需要查看各項證據。",
    "guide.boundary": "資料缺漏不代表沒有風險。仍需向官方、現場或專業人員查證。",
    "guide.property.label": "建立案件", "guide.property.heading": "先建立物件案件",
    "guide.property.description": "從物件搜尋或地址開始，確認案件與價格來源。區域交易可提供背景，但不能證明特定物件的官方身分。",
    "guide.market.label": "市場證據", "guide.market.heading": "查看價格背後的證據",
    "guide.market.description": "檢視市場與估價資料的來源、期間及可比交易。比較條件與資料限制，再判讀價格範圍；範圍不是正確價格的保證。",
    "guide.location.label": "生活圈與通勤", "guide.location.heading": "確認生活圈與通勤",
    "guide.location.description": "確認地址，再按需要查詢周邊設施與通勤參考。檢查涵蓋範圍與更新時間，並實地確認自己的生活需求。",
    "guide.risk.label": "地形與風險", "guide.risk.heading": "分別檢查風險證據",
    "guide.risk.description": "查看地形、災害與周邊風險的資料來源及限制。參考圖層不是法定證明；未查詢或無法取得資料，不代表物件安全。",
    "guide.finance.label": "資金評估", "guide.finance.heading": "用明確假設評估資金",
    "guide.finance.description": "確認採用的價格與來源，再比較頭期款、貸款月付及持有成本。手動情境是試算假設，實際利率與核貸條件仍由銀行確認。",
    "guide.verify.label": "證據查核", "guide.verify.heading": "整理缺漏與待查證事項",
    "guide.verify.description": "在案件總覽檢視證據驗證清單，區分已取得、缺漏與待查證項目。資料完成度不等於查證完成，也不代表建議購買。",
    "guide.save.label": "保存、比較與報告", "guide.save.heading": "保存案件，帶著證據做比較",
    "guide.save.description": "保存目前案件，重新開啟時檢查證據時效。比較案件或產生報告時，一併保留來源、限制與待查證事項，方便下一次討論。",
  },
  en: {
    "guide.title": "Property decision guide", "guide.path": "Decision workflow", "guide.progress": "Step {{current}} of {{total}}",
    "guide.next": "Next", "guide.back": "Back", "guide.skip": "Skip tour", "guide.finish": "Finish", "guide.restart": "Restart tour",
    "guide.context": "This is a workflow guide. Close it to inspect evidence in the workspace when you need it.",
    "guide.boundary": "Missing data does not mean no risk. Verify with official sources, a site visit or a professional.",
    "guide.property.label": "Property case", "guide.property.heading": "Establish the property case",
    "guide.property.description": "Start with Property Finder or an address. Confirm the case and price source. Area transactions provide context; they do not verify a specific property's official identity.",
    "guide.market.label": "Market evidence", "guide.market.heading": "Inspect the evidence behind the price",
    "guide.market.description": "Review sources, periods and comparable transactions in market and valuation evidence. Check comparability and data limits before interpreting a range; it does not guarantee the correct price.",
    "guide.location.label": "Location and commute", "guide.location.heading": "Check location and commute",
    "guide.location.description": "Confirm the address, then request nearby facilities and commute references as needed. Check coverage and freshness, and confirm your daily needs on site.",
    "guide.risk.label": "Terrain and risk", "guide.risk.heading": "Review each risk source separately",
    "guide.risk.description": "Inspect sources and limitations for terrain, hazards and nearby risks. Reference layers are not statutory evidence. Unchecked or unavailable data does not establish property safety.",
    "guide.finance.label": "Finance", "guide.finance.heading": "Evaluate finance with clear assumptions",
    "guide.finance.description": "Confirm the price basis and source, then compare down payment, mortgage payments and holding costs. A manual scenario is an assumption; actual rates and loan approval require bank confirmation.",
    "guide.verify.label": "Evidence verification", "guide.verify.heading": "Identify missing evidence and checks",
    "guide.verify.description": "Use the Evidence Verification Checklist in the overview to separate available evidence, gaps and pending checks. Data completeness does not mean verification is complete or recommend a purchase.",
    "guide.save.label": "Save, compare and report", "guide.save.heading": "Save the case and compare with evidence",
    "guide.save.description": "Save the current case and check evidence freshness when you reopen it. Compare cases or generate a report with sources, limitations and pending checks for your next discussion.",
  },
  ja: {
    "guide.title": "物件の意思決定ガイド", "guide.path": "検討の流れ", "guide.progress": "ステップ {{current}} / {{total}}",
    "guide.next": "次へ", "guide.back": "前へ", "guide.skip": "ガイドをスキップ", "guide.finish": "ガイドを完了", "guide.restart": "ガイドを再開",
    "guide.context": "検討手順のガイドです。閉じた後、必要に応じてワークスペースで資料を確認できます。",
    "guide.boundary": "資料の欠落はリスクがないことを意味しません。公的機関、現地や専門家に確認してください。",
    "guide.property.label": "案件の作成", "guide.property.heading": "まず物件の案件を作成",
    "guide.property.description": "物件検索または住所から始め、案件と価格の出典を確認します。地域の取引は参考情報であり、特定物件の公的な同一性を証明するものではありません。",
    "guide.market.label": "市場資料", "guide.market.heading": "価格の根拠となる資料を確認",
    "guide.market.description": "市場・価格推定資料の出典、期間、比較取引を確認します。条件の類似性と資料の制約を確認して価格帯を判断してください。正しい価格を保証するものではありません。",
    "guide.location.label": "生活圏と通勤", "guide.location.heading": "生活圏と通勤を確認",
    "guide.location.description": "住所を確認し、必要に応じて周辺施設や通勤情報を照会します。対象範囲と更新時点を確認し、自分の生活条件を現地で確かめてください。",
    "guide.risk.label": "地形とリスク", "guide.risk.heading": "リスク資料を個別に確認",
    "guide.risk.description": "地形、災害、周辺リスクの出典と制約を確認します。参考レイヤーは法定資料ではありません。未照会や利用不能は物件の安全を意味しません。",
    "guide.finance.label": "資金計画", "guide.finance.heading": "明確な前提で資金を検討",
    "guide.finance.description": "価格の根拠と出典を確認し、頭金、ローン月額、保有費用を比較します。手入力のシナリオは試算の前提です。実際の金利と融資条件は銀行に確認してください。",
    "guide.verify.label": "資料の検証", "guide.verify.heading": "不足資料と確認事項を整理",
    "guide.verify.description": "案件概要の資料検証チェックリストで、取得済み資料、欠落、未確認事項を区別します。資料の充足度は検証の完了や購入推奨を意味しません。",
    "guide.save.label": "保存・比較・レポート", "guide.save.heading": "案件を保存し、資料に基づいて比較",
    "guide.save.description": "現在の案件を保存し、再度開くときに資料の更新時点を確認します。比較やレポートには出典、制約、未確認事項も残し、次の相談に役立ててください。",
  },
  ko: {
    "guide.title": "부동산 의사결정 안내", "guide.path": "검토 과정", "guide.progress": "{{total}}단계 중 {{current}}단계",
    "guide.next": "다음", "guide.back": "이전", "guide.skip": "안내 건너뛰기", "guide.finish": "안내 완료", "guide.restart": "안내 다시 시작",
    "guide.context": "검토 과정 안내입니다. 닫은 후 필요에 따라 작업공간에서 근거를 확인하세요.",
    "guide.boundary": "자료가 없다고 위험이 없는 것은 아닙니다. 공식 출처, 현장 또는 전문가에게 확인하세요.",
    "guide.property.label": "사례 설정", "guide.property.heading": "먼저 부동산 사례 설정",
    "guide.property.description": "부동산 검색이나 주소로 시작하여 사례와 가격 출처를 확인하세요. 지역 거래는 참고 배경이며 특정 부동산의 공식 신원을 증명하지 않습니다.",
    "guide.market.label": "시장 근거", "guide.market.heading": "가격의 근거 자료 검토",
    "guide.market.description": "시장과 가격 추정 자료의 출처, 기간, 비교 거래를 검토하세요. 조건의 유사성과 자료 한계를 확인한 후 가격 범위를 해석하세요. 정확한 가격을 보장하지 않습니다.",
    "guide.location.label": "입지와 통근", "guide.location.heading": "입지와 통근 확인",
    "guide.location.description": "주소를 확인한 후 필요한 주변 시설과 통근 참고 자료를 조회하세요. 자료 범위와 갱신 시점을 확인하고 생활 조건을 현장에서 점검하세요.",
    "guide.risk.label": "지형과 위험", "guide.risk.heading": "위험 출처를 각각 검토",
    "guide.risk.description": "지형, 재해, 주변 위험의 출처와 한계를 검토하세요. 참고 레이어는 법정 근거가 아닙니다. 조회하지 않았거나 자료를 이용할 수 없다고 안전한 것은 아닙니다.",
    "guide.finance.label": "자금 계획", "guide.finance.heading": "명확한 가정으로 자금 검토",
    "guide.finance.description": "가격 기준과 출처를 확인한 후 계약금, 대출 월액, 보유 비용을 비교하세요. 수동 시나리오는 계산 가정입니다. 실제 금리와 대출 승인은 은행에 확인하세요.",
    "guide.verify.label": "근거 검증", "guide.verify.heading": "누락 자료와 확인 사항 정리",
    "guide.verify.description": "사례 개요의 근거 검증 체크리스트에서 확보한 근거, 누락 자료, 확인할 사항을 구분하세요. 자료 완성도가 검증 완료나 구매 권고를 의미하지 않습니다.",
    "guide.save.label": "저장·비교·보고서", "guide.save.heading": "사례 저장 후 근거로 비교",
    "guide.save.description": "현재 사례를 저장하고 다시 열 때 자료의 갱신 시점을 확인하세요. 사례 비교와 보고서에 출처, 한계, 확인할 사항을 함께 남겨 다음 상담에 활용하세요.",
  },
};
