import type { CopyCatalogue } from "@/lib/copy-catalogue";

const en = {
  title: "A case, from question to next action",
  badge: "Synthetic example",
  disclosure: "All example data is fictional. No real property analysis, provider requests or saved cases.",
  exit: "Exit demo", restart: "Restart demo", skipTyping: "Show completed input",
  address: "Example address", addressValue: "No. 18, Example Lane, Fictional District, Taiwan",
  created: "Example case created locally", caseName: "Fictional Taiwan apartment",
  price: "Scenario price", area: "Area", areaValue: "30 ping", currency: "TWD {{amount}}",
  propertyNext: "Next: inspect comparable transactions before interpreting a price.",
  comparable: "Example comparable {{amount}}", marketLimit: "Illustrative figures only; no transaction source or freshness claim. Check age, floor, area and period in a real case.",
  marketNext: "Next: test whether the location fits your daily life.",
  walk: "Walk to example station", commute: "Example commute", minutes: "{{amount}} minutes",
  locationLimit: "Schematic route only. No map or route query; confirm actual travel time and facilities on site.",
  locationNext: "Next: look for risk evidence and keep gaps visible.",
  flood: "Flood evidence", slope: "Terrain evidence", unknown: "Unknown · not queried",
  riskNext: "Next: use your own price and loan assumptions to explore affordability.",
  down: "Down payment (%)", cash: "Example cash required", loan: "Example loan principal",
  financeLimit: "Example terms: 2.5% over 30 years. Actual rates, taxes, holding costs and approval need separate checks.",
  financeNext: "Next: review the gaps in Overview and the Evidence Checklist.",
  review: "I reviewed this example's price assumptions", reviewed: "Personal review recorded in this demo only",
  reviewBoundary: "Personal review is not official verification. Risk evidence remains unknown.",
  verifyNext: "Next: turn the evidence and open questions into a report preview.",
  reportWhy: "A useful report supports a discussion: what is known, what is assumed, and what must be checked next.",
  reportTitle: "Example report preview", conclusion: "Next action: confirm property identity, compare real transactions, visit the site and check loan terms with a bank.",
  reportBoundary: "Preview only. No saved report, safety clearance, purchase recommendation or valuation.",
  done: "Journey explored", completed: "Previously explored",
} as const;
export type DemoCopyKey = keyof typeof en;
export const DEMO_COPY: CopyCatalogue<DemoCopyKey> = {
  en,
  "zh-TW": {
    title: "從物件問題到下一步行動", badge: "合成示範",
    disclosure: "所有示範資料皆為虛構；不執行真實物件分析、不查詢外部服務，也不保存案件。",
    exit: "離開示範", restart: "重新開始示範", skipTyping: "直接顯示完整輸入",
    address: "示範地址", addressValue: "臺灣示範市虛構區示例巷18號", created: "示範案件已在此畫面建立", caseName: "虛構臺灣住宅",
    price: "情境價格", area: "面積", areaValue: "30坪", currency: "新臺幣 {{amount}} 元",
    propertyNext: "下一步：先看可比交易，再解讀價格。",
    comparable: "示範比較案例 {{amount}}", marketLimit: "僅為示意數字，沒有交易來源或更新時間聲明。真實案件需確認屋齡、樓層、面積與期間。",
    marketNext: "下一步：確認區位是否適合你的日常生活。",
    walk: "步行至示範車站", commute: "示範通勤", minutes: "{{amount}} 分鐘",
    locationLimit: "僅為路徑示意，不查詢地圖或路線；實際交通時間與設施需現場確認。",
    locationNext: "下一步：檢視風險證據，保留資料缺口。",
    flood: "淹水證據", slope: "地形證據", unknown: "未知・尚未查詢",
    riskNext: "下一步：用自己的價格與貸款假設評估負擔。",
    down: "頭期款（%）", cash: "示範自備款", loan: "示範貸款本金",
    financeLimit: "示範條件：年利率2.5%、30年。實際利率、稅費、持有成本與核貸仍需另行確認。",
    financeNext: "下一步：在總覽與證據查證清單整理缺漏。",
    review: "我已核對此示範的價格假設", reviewed: "個人核對僅記錄於本次示範",
    reviewBoundary: "個人核對不代表官方查證；風險證據仍為未知。",
    verifyNext: "下一步：將證據與待查事項整理成報告預覽。",
    reportWhy: "有用的報告協助討論：哪些已知、哪些是假設，以及下一步需要查證什麼。",
    reportTitle: "示範報告預覽", conclusion: "下一步行動：確認物件身分、比較真實交易、現場勘查，並向銀行確認貸款條件。",
    reportBoundary: "僅供預覽，不保存報告；不提供安全證明、購買建議或估價。", done: "已體驗流程", completed: "已瀏覽",
  },
  ja: {
    title: "物件の疑問から次の行動へ", badge: "架空の例",
    disclosure: "すべて架空のデータです。実物件の分析、外部サービスへの照会、案件の保存は行いません。",
    exit: "デモを終了", restart: "デモをやり直す", skipTyping: "入力の完成形を表示",
    address: "例の住所", addressValue: "台湾デモ市架空区サンプル巷18号", created: "この画面に例の案件を作成", caseName: "架空の台湾住宅",
    price: "想定価格", area: "面積", areaValue: "30坪", currency: "台湾ドル {{amount}}",
    propertyNext: "次に：価格を読む前に比較可能な取引を確認します。",
    comparable: "比較例 {{amount}}", marketLimit: "数値は例示です。取引の出所や更新時点は示していません。実案件では築年、階数、面積、期間を確認します。",
    marketNext: "次に：立地が日常生活に合うか確認します。",
    walk: "例の駅への徒歩", commute: "例の通勤", minutes: "{{amount}}分",
    locationLimit: "経路は模式図です。地図や経路を照会しません。実際の所要時間と施設は現地で確認します。",
    locationNext: "次に：リスクの資料を探し、不足を残します。",
    flood: "浸水の資料", slope: "地形の資料", unknown: "不明・未照会",
    riskNext: "次に：自身の価格と融資の想定で負担を考えます。",
    down: "頭金（%）", cash: "例の自己資金", loan: "例の借入元本",
    financeLimit: "例の条件：年2.5%、30年。実際の金利、税、維持費、融資承認は別途確認が必要です。",
    financeNext: "次に：概要と資料確認リストで不足を整理します。",
    review: "この例の価格の想定を個人で確認しました", reviewed: "個人の確認をこのデモ内だけに記録",
    reviewBoundary: "個人の確認は公的な検証ではありません。リスク資料は不明のままです。",
    verifyNext: "次に：資料と未確認事項をレポートのプレビューにまとめます。",
    reportWhy: "役立つレポートは既知の事項、想定、次に確認する事項の話し合いを支えます。",
    reportTitle: "例のレポートプレビュー", conclusion: "次の行動：物件を特定し、実取引を比較し、現地を訪問し、銀行に融資条件を確認します。",
    reportBoundary: "プレビューのみ。保存、安全の証明、購入推奨、価格評価は行いません。", done: "流れを体験しました", completed: "閲覧済み",
  },
  ko: {
    title: "매물의 질문에서 다음 행동으로", badge: "가상 예시",
    disclosure: "모든 예시 자료는 가상입니다. 실제 매물 분석, 외부 서비스 조회, 사례 저장을 하지 않습니다.",
    exit: "데모 나가기", restart: "데모 다시 시작", skipTyping: "완성된 입력 보기",
    address: "예시 주소", addressValue: "대만 데모시 가상구 예시길 18번지", created: "이 화면에 예시 사례 생성", caseName: "가상의 대만 주택",
    price: "시나리오 가격", area: "면적", areaValue: "30핑", currency: "대만달러 {{amount}}",
    propertyNext: "다음: 가격을 해석하기 전에 비교 거래를 확인합니다.",
    comparable: "비교 예시 {{amount}}", marketLimit: "예시 숫자이며 거래 출처나 최신성 주장은 없습니다. 실제 사례에서는 연식, 층, 면적, 기간을 확인하세요.",
    marketNext: "다음: 입지가 일상생활에 맞는지 확인합니다.",
    walk: "예시 역까지 도보", commute: "예시 통근", minutes: "{{amount}}분",
    locationLimit: "경로는 개략도입니다. 지도나 경로를 조회하지 않습니다. 실제 시간과 시설은 현장에서 확인하세요.",
    locationNext: "다음: 위험 근거를 살피고 자료의 공백을 남깁니다.",
    flood: "침수 근거", slope: "지형 근거", unknown: "알 수 없음 · 조회 전",
    riskNext: "다음: 자신의 가격과 대출 가정으로 부담을 살펴봅니다.",
    down: "자기자금 비율 (%)", cash: "예시 자기자금", loan: "예시 대출 원금",
    financeLimit: "예시 조건: 연 2.5%, 30년. 실제 금리, 세금, 보유 비용과 대출 승인은 별도 확인이 필요합니다.",
    financeNext: "다음: 개요와 근거 확인 목록에서 공백을 정리합니다.",
    review: "이 예시의 가격 가정을 개인적으로 검토했습니다", reviewed: "개인 검토를 이 데모에만 기록",
    reviewBoundary: "개인 검토는 공식 검증이 아닙니다. 위험 근거는 여전히 알 수 없습니다.",
    verifyNext: "다음: 근거와 미확인 사항을 보고서 미리보기로 정리합니다.",
    reportWhy: "유용한 보고서는 알려진 사실, 가정과 다음에 확인할 사항의 논의를 돕습니다.",
    reportTitle: "예시 보고서 미리보기", conclusion: "다음 행동: 매물을 식별하고 실제 거래를 비교하고 현장을 방문하고 은행에 대출 조건을 확인하세요.",
    reportBoundary: "미리보기 전용입니다. 보고서 저장, 안전 인증, 구매 추천이나 감정가는 제공하지 않습니다.", done: "과정 체험 완료", completed: "둘러봄",
  },
};
