import type { ExperienceLocale } from "@/lib/experience-i18n";
import { getRuntimeCopyOverride } from "@/lib/runtime-copy-overrides";

export const RUNTIME_COPY_KEYS = [
  "action.retry", "action.reset", "action.expand", "action.open", "action.search", "action.loading", "action.submit", "action.download", "action.copy", "action.calculate", "action.startAnalysis", "action.loadDemo", "action.save", "action.load", "action.delete", "action.clear", "action.compare",
  "common.optional", "common.noData", "common.unavailable", "common.notStarted", "common.yes", "common.no", "common.source", "common.updated", "common.period", "common.count", "common.records", "common.dataLimit", "common.tableSwipe", "common.selectCounty", "common.selectDistrict", "common.selectRoad",
  "map.kicker", "map.title", "map.description", "map.help", "map.quickMode", "map.manualMode", "map.city", "map.district", "map.road", "map.searchPlaceholder", "map.radius", "map.search", "map.searching", "map.empty", "map.emptyDetail", "map.nearby", "map.nearbyDescription", "map.noResult", "map.searchError", "map.healthUnavailable", "map.sourceNote", "map.baseStandard", "map.baseLight", "map.baseSatellite", "map.selected", "map.distance", "map.rating",
  "location.title", "location.description", "location.address", "location.radius", "location.propertyPrice", "location.area", "location.start", "location.analyzing", "location.empty", "location.changeNotice", "location.noResult", "location.error", "location.map", "location.results", "location.score", "location.strengths", "location.weaknesses", "location.poiDetails", "location.buyerFit", "location.dataQuality", "location.transit", "location.convenience", "location.education", "location.green", "location.medical", "location.risk",
  "finder.title", "finder.description", "finder.county", "finder.district", "finder.budgetMin", "finder.budgetMax", "finder.areaMin", "finder.areaMax", "finder.buildingType", "finder.ageMax", "finder.unlimited", "finder.search", "finder.searching", "finder.demo", "finder.sourceNote", "finder.empty", "finder.emptyDetail", "finder.budgetRequired", "finder.error", "finder.noData", "finder.results", "finder.districts", "finder.roads", "finder.transactions", "finder.useValuation", "finder.useLoan", "finder.useHolding", "finder.useLocation", "finder.tableSwipe",
  "valuation.kicker", "valuation.title", "valuation.description", "valuation.help", "valuation.criteria", "valuation.recheck", "valuation.share", "valuation.shareDescription", "valuation.copyShare", "valuation.download", "valuation.useMedian", "valuation.estimateTotal", "valuation.unitPrice", "valuation.confidence", "valuation.level", "valuation.basis", "valuation.dataSource", "valuation.composition", "valuation.usedRecords", "valuation.sameRoad", "valuation.sameType", "valuation.similarity", "valuation.communityMatch", "valuation.noCommunity", "valuation.range", "valuation.low", "valuation.mid", "valuation.high", "valuation.comparables", "valuation.disclaimer", "valuation.empty", "valuation.emptyDetail", "valuation.estimate", "valuation.calculating", "valuation.error", "valuation.trend", "valuation.trendDescription", "valuation.scenario", "valuation.months", "valuation.unitPriceScenario", "valuation.totalPrice", "valuation.annualRate", "valuation.recentData", "valuation.dataStatus", "valuation.source", "valuation.official", "valuation.sample", "valuation.mixed", "valuation.unknownPeriod", "valuation.unknownData",
  "loan.title", "loan.description", "loan.propertyPrice", "loan.downPayment", "loan.rate", "loan.years", "loan.grace", "loan.income", "loan.calculate", "loan.calculating", "loan.invalid", "loan.empty", "loan.emptyDetail", "loan.error",
  "commute.title", "commute.description", "commute.check", "commute.checking", "commute.empty", "commute.noData", "commute.station", "commute.lines", "commute.distance", "commute.updated", "commute.source", "commute.idle", "commute.unresolved", "commute.unavailable", "commute.error",
  "tax.kicker", "tax.title", "tax.description", "tax.help", "tax.select", "tax.example", "tax.custom", "tax.start", "tax.running", "tax.reset", "tax.error", "tax.empty", "tax.emptyDetail", "tax.download", "tax.reportUnavailable",
  "case.title", "case.description", "case.save", "case.recent", "case.clearCurrent", "case.clearAll", "case.empty", "case.compare", "case.compareCount", "case.caseWorkspace", "case.load", "case.delete", "case.confirmDelete", "case.export", "case.missing", "case.status", "case.address", "case.price", "case.ready", "case.notReady",
  "tour.dialogLabel", "tour.skip", "tour.previous", "tour.next", "tour.finish", "tour.openTax", "tour.openMap", "tour.explore", "tour.step1Eyebrow", "tour.step1Title", "tour.step1Description", "tour.step2Eyebrow", "tour.step2Title", "tour.step2Description", "tour.step3Eyebrow", "tour.step3Title", "tour.step3Description", "tour.step4Eyebrow", "tour.step4Title", "tour.step4Description", "tour.step5Eyebrow", "tour.step5Title", "tour.step5Description", "tour.skipNotice", "tour.start", "tour.caseLowRisk", "tour.caseMediumRisk", "tour.caseHighRisk", "tour.feasible", "tour.review", "tour.highRisk", "tour.ruleComplete", "tour.eligibility", "tour.risk", "tour.missing", "tour.fiveYear", "tour.searchNearby", "tour.standard", "tour.light", "tour.satellite", "tour.comparableRange", "tour.bankRate", "tour.marketReference", "tour.riskNotice", "tour.clientReport", "tour.eligibilityReason", "tour.riskReason", "tour.missingReminder", "tour.downloadHtml",
  "dashboard.otherTools", "dashboard.flowHeading", "dashboard.flowDescription", "dashboard.flowDetailDescription", "dashboard.startFinder", "dashboard.runDemo", "dashboard.step1", "dashboard.step1Note", "dashboard.step2", "dashboard.step2Note", "dashboard.step3", "dashboard.step3Note", "dashboard.step4", "dashboard.step4Note", "dashboard.viewingDecision", "dashboard.viewingDisclaimer", "dashboard.nextActions", "dashboard.helpMain", "dashboard.advancedTools", "dashboard.taxExamples", "dashboard.taxExamplesNote", "dashboard.supplementTools", "dashboard.supplementToolsNote", "dashboard.caseLow", "dashboard.caseLowDesc", "dashboard.caseMedium", "dashboard.caseMediumDesc", "dashboard.caseHigh", "dashboard.caseHighDesc", "dashboard.taxModule", "dashboard.taxModuleDesc", "dashboard.mapModule", "dashboard.mapModuleDesc", "dashboard.marketModule", "dashboard.marketModuleDesc", "dashboard.rateModule", "dashboard.rateModuleDesc", "dashboard.valuationModule", "dashboard.valuationModuleDesc", "dashboard.expand",
  "dashboard.ws1Title", "dashboard.ws1Summary", "dashboard.ws1Action", "dashboard.ws1Note",
  "dashboard.ws2Title", "dashboard.ws2Summary", "dashboard.ws2Action", "dashboard.ws2Secondary", "dashboard.ws2Note",
  "dashboard.ws3Title", "dashboard.ws3Summary", "dashboard.ws3Action", "dashboard.ws3Secondary", "dashboard.ws3Note",
  "dashboard.ws4Title", "dashboard.ws4Summary", "dashboard.ws4Action", "dashboard.ws4Secondary", "dashboard.ws4Note",
  "tax.caseLabel", "tax.customLabel", "tax.customEditable", "tax.customCase", "tax.caseIdLabel", "tax.caseNameLabel", "tax.apiNote", "tax.errorLoad", "tax.errorApi", "tax.waitingTitle", "tax.waitingDetail", "tax.runningTitle", "tax.runningDetail", "tax.reportDisabled", "tax.riskScore", "tax.signalNote", "tax.noMissing", "tax.aiNotice", "tax.tabReason", "tax.tabTrace", "tax.tabMissing", "tax.tabMonitor", "tax.tabAi", "tax.ruleTitle",
  "tax.fieldSold", "tax.fieldResidency", "tax.fieldPeriod", "tax.fieldPurchased", "tax.fieldOwner", "tax.fieldLandValue", "tax.fieldDocs", "tax.fieldMonitor", "tax.fieldException",
  "tax.previewCase", "tax.previewClient", "tax.previewSoldSelf", "tax.previewPurchasedSelf", "tax.previewDocs", "tax.previewMonitor",
  "dashboard.mapLoading",
  "dashboard.affordMissingPrice", "dashboard.affordMissingLoan", "dashboard.affordMissingHolding", "dashboard.affordMissingTax",
] as const;

export type RuntimeCopyKey = (typeof RUNTIME_COPY_KEYS)[number];

type RuntimeResource = Record<RuntimeCopyKey, string>;

const zhTW: RuntimeResource = {
  "action.retry": "再試一次", "action.reset": "重設", "action.expand": "展開", "action.open": "開啟", "action.search": "搜尋", "action.loading": "載入中…", "action.submit": "送出", "action.download": "下載", "action.copy": "複製", "action.calculate": "計算", "action.startAnalysis": "開始分析", "action.loadDemo": "載入示範條件", "action.save": "儲存", "action.load": "載入", "action.delete": "刪除", "action.clear": "清除", "action.compare": "比較",
  "common.optional": "可選", "common.noData": "資料不足", "common.unavailable": "暫時無法使用", "common.notStarted": "尚未開始", "common.yes": "是", "common.no": "否", "common.source": "資料來源", "common.updated": "更新時間", "common.period": "期間", "common.count": "筆數", "common.records": "筆", "common.dataLimit": "資料限制", "common.tableSwipe": "表格可左右滑動", "common.selectCounty": "選擇縣市", "common.selectDistrict": "選擇鄉鎮市區", "common.selectRoad": "選擇路段",
  "map.kicker": "地圖與生活機能", "map.title": "Map Insight Lite", "map.description": "搜尋位置並查看附近的生活機能與資料來源。", "map.help": "地圖結果僅供區位參考；資料可能受來源、範圍與可用性限制。", "map.quickMode": "快速選擇", "map.manualMode": "手動輸入", "map.city": "縣市", "map.district": "行政區", "map.road": "路段或地點", "map.searchPlaceholder": "輸入地址、地標或路段", "map.radius": "搜尋半徑（公尺）", "map.search": "搜尋位置", "map.searching": "搜尋中…", "map.empty": "尚未搜尋位置", "map.emptyDetail": "輸入位置後，按下搜尋查看地圖與附近資料。", "map.nearby": "附近生活機能", "map.nearbyDescription": "結果依類別與距離整理，僅供參考。", "map.noResult": "目前沒有可用的地圖結果。", "map.searchError": "地圖資料暫時無法取得，請稍後再試。", "map.healthUnavailable": "地圖服務狀態暫時無法確認。", "map.sourceNote": "來源與可用性依目前服務回應為準。", "map.baseStandard": "標準地圖", "map.baseLight": "淺色地圖", "map.baseSatellite": "衛星影像", "map.selected": "目前位置", "map.distance": "距離", "map.rating": "評分",
  "location.title": "位置洞察", "location.description": "用同一個物件地址，依序完成位置洞察、地勢／災害風險、通勤與生活機能。", "location.address": "物件地址", "location.radius": "分析半徑（公尺）", "location.propertyPrice": "房屋總價（萬元，可選）", "location.area": "坪數（可選）", "location.start": "開始位置分析", "location.analyzing": "分析中…", "location.empty": "請先輸入完整物件地址，按下開始位置分析後才會呼叫 API。", "location.changeNotice": "地址變更後，舊的位置、地勢與通勤結果會失效；請重新分析。", "location.noResult": "目前沒有可用的位置結果。", "location.error": "位置資料暫時無法取得，請稍後再試。", "location.map": "在地圖查看", "location.results": "位置分析結果", "location.score": "位置分數", "location.strengths": "位置優勢", "location.weaknesses": "位置限制", "location.poiDetails": "查看附近 POI 詳細資料", "location.buyerFit": "適合情境參考", "location.dataQuality": "查看資料品質與限制", "location.transit": "交通", "location.convenience": "生活便利", "location.education": "教育", "location.green": "綠地", "location.medical": "醫療", "location.risk": "風險資料",
  "finder.title": "Property Finder", "finder.description": "依預算與條件，從官方實價登錄成交資料找出較符合的區域與路段，作為看屋方向參考。", "finder.county": "縣市（可留空）", "finder.district": "行政區（可用逗號分隔）", "finder.budgetMin": "預算下限（萬元）", "finder.budgetMax": "預算上限（萬元）", "finder.areaMin": "坪數下限", "finder.areaMax": "坪數上限", "finder.buildingType": "建物型態", "finder.ageMax": "屋齡上限", "finder.unlimited": "不限", "finder.search": "搜尋看屋方向", "finder.searching": "搜尋中…", "finder.demo": "載入示範條件", "finder.sourceNote": "僅使用既有官方 PLVR 歷史成交，不代表目前有待售物件。", "finder.empty": "尚未開始找房", "finder.emptyDetail": "請先輸入預算與地點，或載入示範條件後搜尋。", "finder.budgetRequired": "請先輸入預算上限，才能開始找房。", "finder.error": "找房資料暫時無法取得，請稍後再試。", "finder.noData": "目前篩選條件沒有可用的官方交易資料。", "finder.results": "找房結果", "finder.districts": "推薦行政區", "finder.roads": "推薦路段", "finder.transactions": "查看完整成交樣本", "finder.useValuation": "用這個路段估價", "finder.useLoan": "用這個價格算月付", "finder.useHolding": "算每月總支出", "finder.useLocation": "看附近生活機能", "finder.tableSwipe": "表格可左右滑動",
  "valuation.kicker": "市場背景參考", "valuation.title": "實價登錄可比成交估算", "valuation.description": "選擇區域與物件條件，查看可比成交估值區間與信心分數。", "valuation.help": "估價資料由既有後台資料管線維護；結果是可比成交參考，不是保證成交價或購買建議。", "valuation.criteria": "估算條件", "valuation.recheck": "重新查看官方成交條件", "valuation.share": "分享與匯出", "valuation.shareDescription": "分享連結只帶入查詢條件，不會自動送出估價。", "valuation.copyShare": "複製分享連結", "valuation.download": "下載 HTML 摘要", "valuation.useMedian": "用估價中位總價試算", "valuation.estimateTotal": "估算總價", "valuation.unitPrice": "每坪估算單價", "valuation.confidence": "信心分數", "valuation.level": "估價層級", "valuation.basis": "本次估算依據", "valuation.dataSource": "資料來源", "valuation.composition": "資料組成", "valuation.usedRecords": "採用成交", "valuation.sameRoad": "同路段", "valuation.sameType": "同建物類型", "valuation.similarity": "平均相似度", "valuation.communityMatch": "可能命中社區：{{name}}（{{confidence}}）", "valuation.noCommunity": "目前未命中特定社區，改以同路段或同區可比成交估算。", "valuation.range": "估值區間", "valuation.low": "P25 低", "valuation.mid": "加權中位", "valuation.high": "P75 高", "valuation.comparables": "查看完整可比成交", "valuation.disclaimer": "區間是估值參考，不是保證成交價或購買建議。", "valuation.empty": "尚未估算", "valuation.emptyDetail": "選擇區域與物件條件後，系統會整理可比成交與估值區間。", "valuation.estimate": "估算房價", "valuation.calculating": "估算中…", "valuation.error": "估價資料暫時無法取得，請稍後再試。", "valuation.trend": "市場趨勢與未來情境", "valuation.trendDescription": "依既有官方實價登錄趨勢整理情境參考。", "valuation.scenario": "情境", "valuation.months": "個月", "valuation.unitPriceScenario": "每坪情境單價", "valuation.totalPrice": "總價參考", "valuation.annualRate": "採用年率", "valuation.recentData": "查看最近 24 個月資料", "valuation.dataStatus": "估價資料狀態", "valuation.source": "目前資料來源", "valuation.official": "官方匯入資料", "valuation.sample": "展示樣本", "valuation.mixed": "官方與展示混合", "valuation.unknownPeriod": "尚無可確認期間", "valuation.unknownData": "資料不足",
  "loan.title": "貸款月付試算", "loan.description": "用透明公式估算頭期款、月付、總利息與利率變動影響；帶入總價後不會自動送出。", "loan.propertyPrice": "房屋總價（萬元）", "loan.downPayment": "頭期款比例", "loan.rate": "年利率（%）", "loan.years": "貸款年限（年）", "loan.grace": "寬限期年數", "loan.income": "月收入（萬元，可選）", "loan.calculate": "計算貸款月付", "loan.calculating": "試算中…", "loan.invalid": "請先輸入有效總價與貸款年限；寬限期必須小於貸款年限。", "loan.empty": "尚未試算", "loan.emptyDetail": "請先輸入總價、利率與貸款年限，再計算月付、總利息與負擔率。", "loan.error": "貸款試算暫時無法完成，請稍後再試。",
  "commute.title": "通勤與生活機能", "commute.description": "只查最近捷運站與官方快照時間，不會改變風險或看房結論。", "commute.check": "查看通勤資訊", "commute.checking": "正在查詢通勤資訊…", "commute.empty": "請先輸入完整物件地址。", "commute.noData": "資料不足", "commute.station": "最近捷運站", "commute.lines": "路線", "commute.distance": "步行前的直線距離（公尺）", "commute.updated": "資料來源／資料更新時間", "commute.source": "TDX", "commute.idle": "尚未查詢", "commute.unresolved": "目前無法從此地址取得可信的通勤參考結果。", "commute.unavailable": "通勤資料目前無法使用，請稍後再試。", "commute.error": "通勤資料暫時無法取得，請稍後再試。",
  "tax.kicker": "案件決策", "tax.title": "TaxOracle 稅務快篩", "tax.description": "重購退稅資格快篩、五年列管提醒與客戶溝通報告。", "tax.help": "選擇範例案件或自行輸入條件，再呼叫既有 TaxOracle API 檢核規則。", "tax.select": "選擇或輸入案件", "tax.example": "範例案件", "tax.custom": "自訂案件", "tax.start": "開始稅務快篩", "tax.running": "正在檢核規則…", "tax.reset": "重設", "tax.error": "稅務資料暫時無法取得，請稍後再試。", "tax.empty": "尚未產生結果", "tax.emptyDetail": "請先選擇案件，然後按開始稅務快篩。", "tax.download": "下載 HTML 報告", "tax.reportUnavailable": "請先完成稅務快篩才能輸出報告",
  "case.title": "案件儲存與比較", "case.description": "只保存案件摘要，不保存原始交易列或 provider payload。", "case.save": "儲存案件", "case.recent": "最近案件", "case.clearCurrent": "清除目前案件", "case.clearAll": "清除全部案件", "case.empty": "尚未保存案件，完成案件名稱與地址後即可保存。", "case.compare": "比較案件", "case.compareCount": "最多比較 3 件，已選 {{selected}} 件", "case.caseWorkspace": "案件工作台", "case.load": "載入", "case.delete": "刪除", "case.confirmDelete": "再次點擊確認刪除", "case.export": "匯出 HTML 報告", "case.missing": "待補資料：{{items}}", "case.status": "案件狀態", "case.address": "物件地址／識別", "case.price": "可比較價格", "case.ready": "是", "case.notReady": "否",
  "tour.dialogLabel": "Urban Copilot 產品導覽", "tour.skip": "略過導覽", "tour.previous": "上一步", "tour.next": "下一步", "tour.finish": "完成導覽", "tour.openTax": "查看稅務示範", "tour.openMap": "開啟 Map Insight", "tour.explore": "開始探索", "tour.step1Eyebrow": "案件決策工作台", "tour.step1Title": "先從一筆交易案件開始", "tour.step1Description": "選擇展示案件，系統會把稅務、區域、估價與房貸資訊整理在同一個工作台。", "tour.step2Eyebrow": "稅務快篩", "tour.step2Title": "先判斷稅務風險", "tour.step2Description": "系統依既有規則整理資格、風險燈號與補件提醒。AI 只做解釋，不取代規則判斷。", "tour.step3Eyebrow": "地圖洞察", "tour.step3Title": "用地圖看懂這個區域", "tour.step3Description": "搜尋地址或快速選擇區域，查看交通、學校、公園、醫療、商圈與餐飲。", "tour.step4Eyebrow": "價格與房貸背景", "tour.step4Title": "補上價格與房貸背景", "tour.step4Description": "用可比成交樣本查看估值區間與房貸風險背景，這些不是正式鑑價或核貸結果。", "tour.step5Eyebrow": "客戶溝通報告", "tour.step5Title": "整理成可溝通的結論", "tour.step5Description": "下載 HTML 報告，整理資格判斷、風險原因、補件提醒與客戶說明。", "tour.skipNotice": "本系統為展示型決策輔助工具，內容不代表正式申報、鑑價、核貸或法律結論。", "tour.start": "開始導覽", "tour.caseLowRisk": "低風險", "tour.caseMediumRisk": "中風險", "tour.caseHighRisk": "高風險", "tour.feasible": "可行", "tour.review": "需複核", "tour.highRisk": "高風險", "tour.ruleComplete": "規則引擎判斷完成", "tour.eligibility": "資格", "tour.risk": "風險", "tour.missing": "補件", "tour.fiveYear": "五年列管", "tour.searchNearby": "搜尋附近", "tour.standard": "標準", "tour.light": "淺色", "tour.satellite": "衛星", "tour.comparableRange": "可比成交估值區間", "tour.bankRate": "銀行牌告利率", "tour.marketReference": "市場背景參考", "tour.riskNotice": "風險提示：仍需銀行審核", "tour.clientReport": "客戶溝通報告", "tour.eligibilityReason": "資格判斷", "tour.riskReason": "風險原因", "tour.missingReminder": "補件提醒", "tour.downloadHtml": "下載 HTML 報告",
  "dashboard.otherTools": "其他進入方式與工具", "dashboard.flowHeading": "輸入物件資訊，開始看房決策", "dashboard.flowDescription": "先找物件，再依序檢查位置、地勢、通勤、價格與資金，最後彙整成「這間房值得去看嗎」的保守摘要。", "dashboard.flowDetailDescription": "物件決策工作台", "dashboard.startFinder": "開始找物件", "dashboard.runDemo": "先跑示範流程", "dashboard.step1": "找物件", "dashboard.step1Note": "輸入預算、地點與坪數", "dashboard.step2": "看位置", "dashboard.step2Note": "位置洞察、地勢風險、通勤", "dashboard.step3": "算價格與資金", "dashboard.step3Note": "估價、貸款、持有成本、稅費", "dashboard.step4": "比較與做決策", "dashboard.step4Note": "保存、比較、報告與列印", "dashboard.viewingDecision": "看房決策", "dashboard.viewingDisclaimer": "此摘要只整理既有分析結果，不新增黑箱分數，也不取代貸款、法律、稅務或地勢災害判斷。", "dashboard.nextActions": "保存、比較、匯出與其他下一步", "dashboard.helpMain": "主流程會從找房一路帶到位置、風險、估價、資金與看屋報告；通勤資訊只作生活機能參考，不影響看房決策結論。", "dashboard.advancedTools": "進階工具與稅務補充", "dashboard.taxExamples": "TaxOracle 範例案件", "dashboard.taxExamplesNote": "完成看屋報告後，可用範例案件體驗稅務快篩。", "dashboard.supplementTools": "其他補充工具", "dashboard.supplementToolsNote": "需要時再展開 Map Insight、GeoMap、行情與利率背景。", "dashboard.caseLow": "低風險換屋案", "dashboard.caseLowDesc": "展示完整可行流程與報告輸出", "dashboard.caseMedium": "中風險持分案", "dashboard.caseMediumDesc": "展示人工補件與資格複核", "dashboard.caseHigh": "高風險非自住案", "dashboard.caseHighDesc": "展示規則阻擋與關鍵風險", "dashboard.taxModule": "稅務快篩", "dashboard.taxModuleDesc": "判斷資格與補件", "dashboard.mapModule": "Map Insight / GeoMap", "dashboard.mapModuleDesc": "查看區域與 POI", "dashboard.marketModule": "區域行情", "dashboard.marketModuleDesc": "補充市場背景", "dashboard.rateModule": "銀行利率", "dashboard.rateModuleDesc": "查詢牌告房貸相關利率", "dashboard.valuationModule": "房價估算", "dashboard.valuationModuleDesc": "依可比成交推估區間", "dashboard.expand": "展開",
  "dashboard.ws1Title": "找物件", "dashboard.ws1Summary": "用 Property Finder 找出符合預算與坪數的候選路段。", "dashboard.ws1Action": "開始找物件", "dashboard.ws1Note": "沒有輸入資料時，這裡就是第一步；不會自動查詢，也不會新增第二套地址狀態。",
  "dashboard.ws2Title": "看位置", "dashboard.ws2Summary": "檢查位置洞察、地勢／災害風險、通勤與生活機能。", "dashboard.ws2Action": "檢查位置", "dashboard.ws2Secondary": "在地圖查看", "dashboard.ws2Note": "通勤資訊仍需手動點擊查詢，且只供生活機能參考，不影響地勢、貸款、稅務、估價或看房決策。",
  "dashboard.ws3Title": "算價格與資金", "dashboard.ws3Summary": "把估價、貸款、持有成本、稅費與市場背景集中在一處操作。", "dashboard.ws3Action": "估價與資金試算", "dashboard.ws3Secondary": "稅務快篩", "dashboard.ws3Note": "每個工具仍由使用者手動按下才會呼叫 API；資料不足時只顯示未完成，不猜測結論。",
  "dashboard.ws4Title": "比較與做決策", "dashboard.ws4Summary": "整理 Viewing Decision、Decision Report、案例保存、比較與列印／另存 PDF。", "dashboard.ws4Action": "查看看房決策", "dashboard.ws4Secondary": "管理案件", "dashboard.ws4Note": "比較報告只彙整既有結果；通勤資料不納入分數或排名，地勢資料未知也不會被視為低風險。",
  "tax.caseLabel": "範例案件", "tax.customLabel": "可自行修改", "tax.customEditable": "可自行修改", "tax.customCase": "自訂案件", "tax.caseIdLabel": "案件編號", "tax.caseNameLabel": "案件名稱", "tax.apiNote": "按下後會呼叫 POST /taxoracle/analyze，成功後自動開啟原因追蹤。", "tax.errorLoad": "範例案件暫時無法載入，仍可使用自訂案件。請稍後再試。", "tax.errorApi": "稅務快篩 API 呼叫失敗，請稍後再試", "tax.waitingTitle": "等待稅務快篩", "tax.waitingDetail": "請先選擇案件，然後按開始稅務快篩；完成後會顯示資格、規則原因與報告入口。", "tax.runningTitle": "正在執行稅務快篩", "tax.runningDetail": "TaxOracle API 正在檢核 TX001–TX009，完成後會顯示規則結果與補件建議。", "tax.reportDisabled": "請先完成稅務快篩才能輸出報告", "tax.riskScore": "風險分數／100", "tax.signalNote": "訊號：{{signal}}；不代表法律判斷或安全保證。", "tax.noMissing": "目前無補件項目", "tax.aiNotice": "AI 只做語言化說明，資格由規則引擎 TX001–TX009 判斷。", "tax.tabReason": "原因", "tax.tabTrace": "規則追蹤", "tax.tabMissing": "補件清單", "tax.tabMonitor": "五年列管", "tax.tabAi": "AI 說明", "tax.ruleTitle": "查看 TX001–TX009 完整規則追蹤",
  "tax.fieldSold": "出售物件為自住", "tax.fieldResidency": "設籍／自住條件符合", "tax.fieldPeriod": "換購時間合理", "tax.fieldPurchased": "換購物件為自住", "tax.fieldOwner": "所有權主體一致", "tax.fieldLandValue": "公告土地現值齊備", "tax.fieldDocs": "文件完整", "tax.fieldMonitor": "進入五年列管", "tax.fieldException": "存在例外事由",
  "tax.previewCase": "案件", "tax.previewClient": "客戶", "tax.previewSoldSelf": "出售自住", "tax.previewPurchasedSelf": "換購自住", "tax.previewDocs": "文件完整", "tax.previewMonitor": "五年列管",
  "dashboard.mapLoading": "地圖載入中...",
  "dashboard.affordMissingPrice": "尚未提供房屋總價", "dashboard.affordMissingLoan": "尚未試算貸款", "dashboard.affordMissingHolding": "尚未試算持有成本", "dashboard.affordMissingTax": "尚未執行 TaxOracle",
};

const en: RuntimeResource = {
  "action.retry": "Try again", "action.reset": "Reset", "action.expand": "Expand", "action.open": "Open", "action.search": "Search", "action.loading": "Loading…", "action.submit": "Submit", "action.download": "Download", "action.copy": "Copy", "action.calculate": "Calculate", "action.startAnalysis": "Start analysis", "action.loadDemo": "Load demo conditions", "action.save": "Save", "action.load": "Load", "action.delete": "Delete", "action.clear": "Clear", "action.compare": "Compare",
  "common.optional": "optional", "common.noData": "Insufficient data", "common.unavailable": "Temporarily unavailable", "common.notStarted": "Not started", "common.yes": "Yes", "common.no": "No", "common.source": "Source", "common.updated": "Updated", "common.period": "Period", "common.count": "Count", "common.records": "records", "common.dataLimit": "Data limits", "common.tableSwipe": "Swipe to view the table", "common.selectCounty": "Select county/city", "common.selectDistrict": "Select district", "common.selectRoad": "Select road",
  "map.kicker": "Maps and livability", "map.title": "Map Insight Lite", "map.description": "Search a place and review nearby livability information and sources.", "map.help": "Map results are location references only and may be limited by source coverage and availability.", "map.quickMode": "Quick select", "map.manualMode": "Manual input", "map.city": "County/city", "map.district": "District", "map.road": "Road or place", "map.searchPlaceholder": "Enter an address, landmark, or road", "map.radius": "Search radius (m)", "map.search": "Search location", "map.searching": "Searching…", "map.empty": "No location searched", "map.emptyDetail": "Enter a location and search to view the map and nearby data.", "map.nearby": "Nearby livability", "map.nearbyDescription": "Results are grouped by category and distance for reference only.", "map.noResult": "No usable map result is available.", "map.searchError": "Map data is temporarily unavailable. Try again later.", "map.healthUnavailable": "Map service status is temporarily unavailable.", "map.sourceNote": "Source and availability follow the current service response.", "map.baseStandard": "Standard map", "map.baseLight": "Light map", "map.baseSatellite": "Satellite imagery", "map.selected": "Selected location", "map.distance": "Distance", "map.rating": "Rating",
  "location.title": "Location Insight", "location.description": "Use one property address to review location, terrain/disaster risk, commute, and livability in sequence.", "location.address": "Property address", "location.radius": "Analysis radius (m)", "location.propertyPrice": "Property price (TWD ten-thousands, optional)", "location.area": "Area (ping, optional)", "location.start": "Start location analysis", "location.analyzing": "Analyzing…", "location.empty": "Enter a complete property address and start analysis to call the API.", "location.changeNotice": "Changing the address invalidates older location, terrain, and commute results; run the analysis again.", "location.noResult": "No usable location result is available.", "location.error": "Location data is temporarily unavailable. Try again later.", "location.map": "View on map", "location.results": "Location analysis", "location.score": "Location score", "location.strengths": "Location strengths", "location.weaknesses": "Location limits", "location.poiDetails": "View nearby POI details", "location.buyerFit": "Context fit reference", "location.dataQuality": "View data quality and limits", "location.transit": "Transit", "location.convenience": "Convenience", "location.education": "Education", "location.green": "Green space", "location.medical": "Medical", "location.risk": "Risk data",
  "finder.title": "Property Finder", "finder.description": "Use budget and property conditions to find relevant areas and roads from official transaction data as a viewing reference.", "finder.county": "County/city (optional)", "finder.district": "District (comma-separated)", "finder.budgetMin": "Minimum budget (TWD ten-thousands)", "finder.budgetMax": "Maximum budget (TWD ten-thousands)", "finder.areaMin": "Minimum area (ping)", "finder.areaMax": "Maximum area (ping)", "finder.buildingType": "Building type", "finder.ageMax": "Maximum age", "finder.unlimited": "Any", "finder.search": "Search viewing options", "finder.searching": "Searching…", "finder.demo": "Load demo conditions", "finder.sourceNote": "Uses existing official PLVR history only; it does not indicate a listing is currently for sale.", "finder.empty": "Search not started", "finder.emptyDetail": "Enter budget and location, or load demo conditions before searching.", "finder.budgetRequired": "Enter a maximum budget before searching.", "finder.error": "Property search data is temporarily unavailable. Try again later.", "finder.noData": "No usable official transaction data matches these filters.", "finder.results": "Property search results", "finder.districts": "Suggested districts", "finder.roads": "Suggested roads", "finder.transactions": "View transaction samples", "finder.useValuation": "Value this road", "finder.useLoan": "Calculate payment", "finder.useHolding": "Estimate monthly cost", "finder.useLocation": "View nearby livability", "finder.tableSwipe": "Swipe to view the table",
  "valuation.kicker": "Market reference", "valuation.title": "Comparable transaction valuation", "valuation.description": "Choose an area and property conditions to review comparable transaction ranges and confidence.", "valuation.help": "Valuation data is maintained by the existing backend pipeline. It is a comparable-transaction reference, not a guaranteed sale price or purchase recommendation.", "valuation.criteria": "Valuation conditions", "valuation.recheck": "Review official transaction conditions", "valuation.share": "Share and export", "valuation.shareDescription": "The share link contains query conditions only and does not submit a valuation automatically.", "valuation.copyShare": "Copy share link", "valuation.download": "Download HTML summary", "valuation.useMedian": "Calculate with median estimate", "valuation.estimateTotal": "Estimated total", "valuation.unitPrice": "Estimated unit price", "valuation.confidence": "Confidence", "valuation.level": "Valuation level", "valuation.basis": "Valuation evidence", "valuation.dataSource": "Data source", "valuation.composition": "Data composition", "valuation.usedRecords": "Transactions used", "valuation.sameRoad": "Same road", "valuation.sameType": "Same building type", "valuation.similarity": "Average similarity", "valuation.communityMatch": "Possible community match: {{name}} ({{confidence}})", "valuation.noCommunity": "No specific community matched; comparable transactions from the same road or district were used.", "valuation.range": "Valuation range", "valuation.low": "P25 low", "valuation.mid": "Weighted median", "valuation.high": "P75 high", "valuation.comparables": "View comparable transactions", "valuation.disclaimer": "This range is a valuation reference, not a guaranteed sale price or purchase recommendation.", "valuation.empty": "Valuation not started", "valuation.emptyDetail": "Choose area and property conditions to organize comparable transactions and a valuation range.", "valuation.estimate": "Estimate price", "valuation.calculating": "Estimating…", "valuation.error": "Valuation data is temporarily unavailable. Try again later.", "valuation.trend": "Market trend and scenarios", "valuation.trendDescription": "Scenarios are organized from existing official transaction trends for reference.", "valuation.scenario": "Scenario", "valuation.months": "months", "valuation.unitPriceScenario": "Scenario unit price", "valuation.totalPrice": "Total price reference", "valuation.annualRate": "Annual rate", "valuation.recentData": "View the latest 24 months", "valuation.dataStatus": "Valuation data status", "valuation.source": "Current source", "valuation.official": "Official imported data", "valuation.sample": "Sample data", "valuation.mixed": "Official and sample data", "valuation.unknownPeriod": "No confirmed period", "valuation.unknownData": "Insufficient data",
  "loan.title": "Loan payment estimate", "loan.description": "Use transparent formulas to estimate down payment, monthly payment, total interest, and rate sensitivity; entering a price does not submit automatically.", "loan.propertyPrice": "Property price (TWD ten-thousands)", "loan.downPayment": "Down payment ratio", "loan.rate": "Annual interest rate (%)", "loan.years": "Loan term (years)", "loan.grace": "Grace period (years)", "loan.income": "Monthly income (TWD ten-thousands, optional)", "loan.calculate": "Calculate monthly payment", "loan.calculating": "Calculating…", "loan.invalid": "Enter a valid price and loan term. The grace period must be shorter than the loan term.", "loan.empty": "Estimate not started", "loan.emptyDetail": "Enter price, rate, and loan term before calculating payment, total interest, and burden ratio.", "loan.error": "Loan estimate is temporarily unavailable. Try again later.",
  "commute.title": "Commute and livability", "commute.description": "Checks only the nearest MRT station and official snapshot time; it does not change risk or viewing conclusions.", "commute.check": "Check commute information", "commute.checking": "Checking commute information…", "commute.empty": "Enter a complete property address first.", "commute.noData": "Insufficient data", "commute.station": "Nearest MRT station", "commute.lines": "Lines", "commute.distance": "Straight-line distance before walking (m)", "commute.updated": "Source / updated time", "commute.source": "TDX", "commute.idle": "No lookup yet", "commute.unresolved": "No trusted commute reference could be found for this address.", "commute.unavailable": "Commute data is temporarily unavailable. Try again later.", "commute.error": "Commute data could not be loaded. Try again later.",
  "tax.kicker": "Property decision", "tax.title": "TaxOracle tax screening", "tax.description": "Screen reinvestment tax eligibility, five-year monitoring reminders, and communication reports.", "tax.help": "Choose an example case or enter conditions, then call the existing TaxOracle API to check the rules.", "tax.select": "Select or enter a case", "tax.example": "Example case", "tax.custom": "Custom case", "tax.start": "Start tax screening", "tax.running": "Checking rules…", "tax.reset": "Reset", "tax.error": "Tax data is temporarily unavailable. Try again later.", "tax.empty": "No result yet", "tax.emptyDetail": "Select a case and start tax screening.", "tax.download": "Download HTML report", "tax.reportUnavailable": "Complete tax screening before exporting a report",
  "case.title": "Saved cases and comparison", "case.description": "Only case summaries are saved; raw transaction rows and provider payloads are not saved.", "case.save": "Save case", "case.recent": "Recent cases", "case.clearCurrent": "Clear current case", "case.clearAll": "Clear all cases", "case.empty": "No saved cases. Complete a case name and address before saving.", "case.compare": "Compare cases", "case.compareCount": "Up to 3 cases; {{selected}} selected", "case.caseWorkspace": "Case workspace", "case.load": "Load", "case.delete": "Delete", "case.confirmDelete": "Click again to confirm deletion", "case.export": "Export HTML report", "case.missing": "Missing data: {{items}}", "case.status": "Case status", "case.address": "Property address/identifier", "case.price": "Comparable price", "case.ready": "Yes", "case.notReady": "No",
  "tour.dialogLabel": "Urban Copilot product tour", "tour.skip": "Skip tour", "tour.previous": "Previous", "tour.next": "Next", "tour.finish": "Finish tour", "tour.openTax": "View tax demo", "tour.openMap": "Open Map Insight", "tour.explore": "Start exploring", "tour.step1Eyebrow": "Property case workspace", "tour.step1Title": "Start with one property case", "tour.step1Description": "Review tax, location, price, and loan information in one workspace.", "tour.step2Eyebrow": "Tax screening", "tour.step2Title": "Check tax risk first", "tour.step2Description": "Existing rules organize eligibility, risk signals, and missing documents. AI explains but does not replace the rules.", "tour.step3Eyebrow": "Map insight", "tour.step3Title": "Understand the area on a map", "tour.step3Description": "Search an address or area to review nearby facilities.", "tour.step4Eyebrow": "Price and loan context", "tour.step4Title": "Add price and loan context", "tour.step4Description": "Use comparable transactions and loan information as background references, not formal valuation or approval.", "tour.step5Eyebrow": "Client communication report", "tour.step5Title": "Organize a clear summary", "tour.step5Description": "Download an HTML report with eligibility, risks, missing information, and client notes.", "tour.skipNotice": "This is a demonstrative decision-support tool. It is not a formal filing, valuation, loan approval, or legal conclusion.", "tour.start": "Start tour", "tour.caseLowRisk": "Low risk", "tour.caseMediumRisk": "Medium risk", "tour.caseHighRisk": "High risk", "tour.feasible": "Feasible", "tour.review": "Review needed", "tour.highRisk": "High risk", "tour.ruleComplete": "Rules completed", "tour.eligibility": "Eligibility", "tour.risk": "Risk", "tour.missing": "Missing", "tour.fiveYear": "Five-year monitoring", "tour.searchNearby": "Search nearby", "tour.standard": "Standard", "tour.light": "Light", "tour.satellite": "Satellite", "tour.comparableRange": "Comparable valuation range", "tour.bankRate": "Bank posted rate", "tour.marketReference": "Market reference", "tour.riskNotice": "Risk note: bank review is still required", "tour.clientReport": "Client communication report", "tour.eligibilityReason": "Eligibility", "tour.riskReason": "Risk reasons", "tour.missingReminder": "Missing information", "tour.downloadHtml": "Download HTML report",
  "dashboard.otherTools": "Other entry points and tools", "dashboard.flowHeading": "Enter property details to start a viewing decision", "dashboard.flowDescription": "Find a property, then check location, terrain, commute, price, and funding in order. The result is a conservative summary of whether this property is worth viewing.", "dashboard.flowDetailDescription": "Property decision workspace", "dashboard.startFinder": "Start property search", "dashboard.runDemo": "Run guided demo first", "dashboard.step1": "Find property", "dashboard.step1Note": "Enter budget, location, and area", "dashboard.step2": "Check location", "dashboard.step2Note": "Location insight, terrain risk, commute", "dashboard.step3": "Calculate price and funding", "dashboard.step3Note": "Valuation, loan, holding cost, taxes", "dashboard.step4": "Compare and decide", "dashboard.step4Note": "Save, compare, report, and print", "dashboard.viewingDecision": "Viewing decision", "dashboard.viewingDisclaimer": "This summary organizes existing analysis only. It does not add opaque scores or replace loan, legal, tax, or terrain judgments.", "dashboard.nextActions": "Save, compare, export, and next steps", "dashboard.helpMain": "The main flow goes from property search through location, risk, valuation, funding, and the viewing report. Commute information is a livability reference only and does not affect the viewing decision.", "dashboard.advancedTools": "Advanced tools and tax supplements", "dashboard.taxExamples": "TaxOracle example cases", "dashboard.taxExamplesNote": "After completing a viewing report, try the tax screening with example cases.", "dashboard.supplementTools": "Other supplementary tools", "dashboard.supplementToolsNote": "Expand for Map Insight, GeoMap, market data, and rate references when needed.", "dashboard.caseLow": "Low-risk home swap", "dashboard.caseLowDesc": "Demonstrates a complete feasible workflow and report output", "dashboard.caseMedium": "Medium-risk co-ownership", "dashboard.caseMediumDesc": "Demonstrates document supplements and eligibility review", "dashboard.caseHigh": "High-risk non-owner-occupied", "dashboard.caseHighDesc": "Demonstrates rule blocking and critical risk", "dashboard.taxModule": "Tax screening", "dashboard.taxModuleDesc": "Eligibility and documents", "dashboard.mapModule": "Map Insight / GeoMap", "dashboard.mapModuleDesc": "View area and POI", "dashboard.marketModule": "Market data", "dashboard.marketModuleDesc": "Supplementary market context", "dashboard.rateModule": "Bank rates", "dashboard.rateModuleDesc": "Check posted mortgage-related rates", "dashboard.valuationModule": "Price estimate", "dashboard.valuationModuleDesc": "Estimate range from comparable transactions", "dashboard.expand": "Expand",
  "dashboard.ws1Title": "Find property", "dashboard.ws1Summary": "Use Property Finder to identify candidate roads matching budget and area.", "dashboard.ws1Action": "Start property search", "dashboard.ws1Note": "When there is no input data, this is the first step. It does not auto-query or create a second address state.",
  "dashboard.ws2Title": "Check location", "dashboard.ws2Summary": "Review location insight, terrain/disaster risk, commute, and livability.", "dashboard.ws2Action": "Check location", "dashboard.ws2Secondary": "View on map", "dashboard.ws2Note": "Commute information must be queried manually and is only a livability reference; it does not affect terrain, loan, tax, valuation, or viewing decisions.",
  "dashboard.ws3Title": "Calculate price and funding", "dashboard.ws3Summary": "Operate valuation, loan, holding cost, taxes, and market context in one place.", "dashboard.ws3Action": "Valuation and funding", "dashboard.ws3Secondary": "Tax screening", "dashboard.ws3Note": "Each tool only calls the API when the user explicitly presses the button. Insufficient data shows incomplete status, not guessed conclusions.",
  "dashboard.ws4Title": "Compare and decide", "dashboard.ws4Summary": "Organize viewing decision, decision report, saved cases, comparison, and print/PDF.", "dashboard.ws4Action": "View decision", "dashboard.ws4Secondary": "Manage cases", "dashboard.ws4Note": "Comparison reports only compile existing results. Commute data does not factor into scores or rankings, and unknown terrain data is not treated as low risk.",
  "tax.caseLabel": "Example case", "tax.customLabel": "Editable", "tax.customEditable": "Editable", "tax.customCase": "Custom case", "tax.caseIdLabel": "Case ID", "tax.caseNameLabel": "Case name", "tax.apiNote": "Calls POST /taxoracle/analyze; the rule trace opens automatically on success.", "tax.errorLoad": "Example cases are temporarily unavailable. You can still use a custom case. Try again later.", "tax.errorApi": "Tax screening API call failed. Try again later.", "tax.waitingTitle": "Waiting for tax screening", "tax.waitingDetail": "Select a case and start tax screening. Eligibility, rule reasons, and report access will appear on completion.", "tax.runningTitle": "Running tax screening", "tax.runningDetail": "TaxOracle API is checking TX001–TX009. Rule results and document suggestions will appear when done.", "tax.reportDisabled": "Complete tax screening before exporting a report", "tax.riskScore": "Risk score / 100", "tax.signalNote": "Signal: {{signal}}; this is not a legal ruling or safety guarantee.", "tax.noMissing": "No missing documents at this time", "tax.aiNotice": "AI provides a natural-language explanation only. Eligibility is determined by rule engine TX001–TX009.", "tax.tabReason": "Reason", "tax.tabTrace": "Rule trace", "tax.tabMissing": "Missing documents", "tax.tabMonitor": "Five-year monitoring", "tax.tabAi": "AI explanation", "tax.ruleTitle": "View full TX001–TX009 rule trace",
  "tax.fieldSold": "Sold property is owner-occupied", "tax.fieldResidency": "Residency/occupancy met", "tax.fieldPeriod": "Repurchase period reasonable", "tax.fieldPurchased": "Repurchased property is owner-occupied", "tax.fieldOwner": "Ownership entity consistent", "tax.fieldLandValue": "Declared land value available", "tax.fieldDocs": "Documents complete", "tax.fieldMonitor": "Enters five-year monitoring", "tax.fieldException": "Exceptional circumstances exist",
  "tax.previewCase": "Case", "tax.previewClient": "Client", "tax.previewSoldSelf": "Sold owner-occupied", "tax.previewPurchasedSelf": "Repurchased owner-occupied", "tax.previewDocs": "Documents complete", "tax.previewMonitor": "Five-year monitoring",
  "dashboard.mapLoading": "Loading map...",
  "dashboard.affordMissingPrice": "Property price not yet provided", "dashboard.affordMissingLoan": "Loan not yet calculated", "dashboard.affordMissingHolding": "Holding cost not yet calculated", "dashboard.affordMissingTax": "TaxOracle not yet run",
};

const ja: RuntimeResource = {
  "action.retry": "Try again",
  "action.reset": "Reset",
  "action.expand": "Expand",
  "action.open": "Open",
  "action.search": "Search",
  "action.loading": "Loading…",
  "action.submit": "Submit",
  "action.download": "Download",
  "action.copy": "Copy",
  "action.calculate": "Calculate",
  "action.startAnalysis": "Start analysis",
  "action.loadDemo": "Load demo conditions",
  "action.save": "Save",
  "action.load": "Load",
  "action.delete": "Delete",
  "action.clear": "Clear",
  "action.compare": "Compare",
  "common.optional": "optional",
  "common.noData": "Insufficient data",
  "common.unavailable": "Temporarily unavailable",
  "common.notStarted": "Not started",
  "common.yes": "Yes",
  "common.no": "No",
  "common.source": "Source",
  "common.updated": "Updated",
  "common.period": "Period",
  "common.count": "Count",
  "common.records": "records",
  "common.dataLimit": "Data limits",
  "common.tableSwipe": "Swipe to view the table",
  "common.selectCounty": "Select county/city",
  "common.selectDistrict": "Select district",
  "common.selectRoad": "Select road",
  "map.kicker": "Maps and livability",
  "map.title": "Map Insight Lite",
  "map.description": "場所を検索し、周辺の生活利便性とデータソースを確認します。",
  "map.help": "Map results are location references only and may be limited by source coverage and availability.",
  "map.quickMode": "Quick select",
  "map.manualMode": "Manual input",
  "map.city": "County/city",
  "map.district": "District",
  "map.road": "Road or place",
  "map.searchPlaceholder": "Enter an address, landmark, or road",
  "map.radius": "Search radius (m)",
  "map.search": "場所を検索",
  "map.searching": "検索中…",
  "map.empty": "まだ場所を検索していません",
  "map.emptyDetail": "Enter a location and search to view the map and nearby data.",
  "map.nearby": "周辺の生活利便性",
  "map.nearbyDescription": "Results are grouped by category and distance for reference only.",
  "map.noResult": "No usable map result is available.",
  "map.searchError": "Map data is temporarily unavailable. Try again later.",
  "map.healthUnavailable": "Map service status is temporarily unavailable.",
  "map.sourceNote": "Source and availability follow the current service response.",
  "map.baseStandard": "標準地図",
  "map.baseLight": "ライト地図",
  "map.baseSatellite": "衛星画像",
  "map.selected": "選択した場所",
  "map.distance": "距離",
  "map.rating": "評価",
  "location.title": "位置インサイト",
  "location.description": "Use one property address to review location, terrain/disaster risk, commute, and livability in sequence.",
  "location.address": "Property address",
  "location.radius": "Analysis radius (m)",
  "location.propertyPrice": "Property price (TWD ten-thousands, optional)",
  "location.area": "Area (ping, optional)",
  "location.start": "位置分析を開始",
  "location.analyzing": "分析中…",
  "location.empty": "Enter a complete property address and start analysis to call the API.",
  "location.changeNotice": "Changing the address invalidates older location, terrain, and commute results; run the analysis again.",
  "location.noResult": "No usable location result is available.",
  "location.error": "Location data is temporarily unavailable. Try again later.",
  "location.map": "View on map",
  "location.results": "Location analysis",
  "location.score": "Location score",
  "location.strengths": "Location strengths",
  "location.weaknesses": "Location limits",
  "location.poiDetails": "View nearby POI details",
  "location.buyerFit": "Context fit reference",
  "location.dataQuality": "View data quality and limits",
  "location.transit": "Transit",
  "location.convenience": "Convenience",
  "location.education": "Education",
  "location.green": "Green space",
  "location.medical": "Medical",
  "location.risk": "Risk data",
  "finder.title": "Property Finder",
  "finder.description": "Use budget and property conditions to find relevant areas and roads from official transaction data as a viewing reference.",
  "finder.county": "County/city (optional)",
  "finder.district": "District (comma-separated)",
  "finder.budgetMin": "Minimum budget (TWD ten-thousands)",
  "finder.budgetMax": "Maximum budget (TWD ten-thousands)",
  "finder.areaMin": "Minimum area (ping)",
  "finder.areaMax": "Maximum area (ping)",
  "finder.buildingType": "Building type",
  "finder.ageMax": "Maximum age",
  "finder.unlimited": "Any",
  "finder.search": "内見候補を検索",
  "finder.searching": "検索中…",
  "finder.demo": "Load demo conditions",
  "finder.sourceNote": "Uses existing official PLVR history only; it does not indicate a listing is currently for sale.",
  "finder.empty": "Search not started",
  "finder.emptyDetail": "Enter budget and location, or load demo conditions before searching.",
  "finder.budgetRequired": "Enter a maximum budget before searching.",
  "finder.error": "Property search data is temporarily unavailable. Try again later.",
  "finder.noData": "No usable official transaction data matches these filters.",
  "finder.results": "Property search results",
  "finder.districts": "Suggested districts",
  "finder.roads": "Suggested roads",
  "finder.transactions": "View transaction samples",
  "finder.useValuation": "Value this road",
  "finder.useLoan": "Calculate payment",
  "finder.useHolding": "Estimate monthly cost",
  "finder.useLocation": "View nearby livability",
  "finder.tableSwipe": "Swipe to view the table",
  "valuation.kicker": "Market reference",
  "valuation.title": "類似取引による価格推定",
  "valuation.description": "Choose an area and property conditions to review comparable transaction ranges and confidence.",
  "valuation.help": "Valuation data is maintained by the existing backend pipeline. It is a comparable-transaction reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.criteria": "Valuation conditions",
  "valuation.recheck": "Review official transaction conditions",
  "valuation.share": "Share and export",
  "valuation.shareDescription": "The share link contains query conditions only and does not submit a valuation automatically.",
  "valuation.copyShare": "Copy share link",
  "valuation.download": "Download HTML summary",
  "valuation.useMedian": "Calculate with median estimate",
  "valuation.estimateTotal": "Estimated total",
  "valuation.unitPrice": "Estimated unit price",
  "valuation.confidence": "Confidence",
  "valuation.level": "Valuation level",
  "valuation.basis": "Valuation evidence",
  "valuation.dataSource": "Data source",
  "valuation.composition": "Data composition",
  "valuation.usedRecords": "Transactions used",
  "valuation.sameRoad": "Same road",
  "valuation.sameType": "Same building type",
  "valuation.similarity": "Average similarity",
  "valuation.communityMatch": "Possible community match: {{name}} ({{confidence}})",
  "valuation.noCommunity": "No specific community matched; comparable transactions from the same road or district were used.",
  "valuation.range": "Valuation range",
  "valuation.low": "P25 low",
  "valuation.mid": "Weighted median",
  "valuation.high": "P75 high",
  "valuation.comparables": "View comparable transactions",
  "valuation.disclaimer": "This range is a valuation reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.empty": "Valuation not started",
  "valuation.emptyDetail": "Choose area and property conditions to organize comparable transactions and a valuation range.",
  "valuation.estimate": "価格を推定",
  "valuation.calculating": "推定中…",
  "valuation.error": "Valuation data is temporarily unavailable. Try again later.",
  "valuation.trend": "Market trend and scenarios",
  "valuation.trendDescription": "Scenarios are organized from existing official transaction trends for reference.",
  "valuation.scenario": "Scenario",
  "valuation.months": "months",
  "valuation.unitPriceScenario": "Scenario unit price",
  "valuation.totalPrice": "Total price reference",
  "valuation.annualRate": "Annual rate",
  "valuation.recentData": "View the latest 24 months",
  "valuation.dataStatus": "Valuation data status",
  "valuation.source": "Current source",
  "valuation.official": "Official imported data",
  "valuation.sample": "Sample data",
  "valuation.mixed": "Official and sample data",
  "valuation.unknownPeriod": "No confirmed period",
  "valuation.unknownData": "Insufficient data",
  "loan.title": "ローン返済額の試算",
  "loan.description": "Use transparent formulas to estimate down payment, monthly payment, total interest, and rate sensitivity; entering a price does not submit automatically.",
  "loan.propertyPrice": "Property price (TWD ten-thousands)",
  "loan.downPayment": "Down payment ratio",
  "loan.rate": "Annual interest rate (%)",
  "loan.years": "Loan term (years)",
  "loan.grace": "Grace period (years)",
  "loan.income": "Monthly income (TWD ten-thousands, optional)",
  "loan.calculate": "月々の返済額を計算",
  "loan.calculating": "Calculating…",
  "loan.invalid": "Enter a valid price and loan term. The grace period must be shorter than the loan term.",
  "loan.empty": "Estimate not started",
  "loan.emptyDetail": "Enter price, rate, and loan term before calculating payment, total interest, and burden ratio.",
  "loan.error": "Loan estimate is temporarily unavailable. Try again later.",
  "commute.title": "通勤と生活利便性",
  "commute.description": "Checks only the nearest MRT station and official snapshot time; it does not change risk or viewing conclusions.",
  "commute.check": "通勤情報を確認",
  "commute.checking": "通勤情報を確認中…",
  "commute.empty": "Enter a complete property address first.",
  "commute.noData": "Insufficient data",
  "commute.station": "Nearest MRT station",
  "commute.lines": "Lines",
  "commute.distance": "Straight-line distance before walking (m)",
  "commute.updated": "Source / updated time",
  "commute.source": "TDX",
  "commute.idle": "まだ検索していません",
  "commute.unresolved": "この住所から信頼できる通勤情報を取得できませんでした。",
  "commute.unavailable": "通勤データは一時的に利用できません。後でもう一度お試しください。",
  "commute.error": "通勤データを読み込めませんでした。",
  "tax.kicker": "Property decision",
  "tax.title": "TaxOracle 税務スクリーニング",
  "tax.description": "Screen reinvestment tax eligibility, five-year monitoring reminders, and communication reports.",
  "tax.help": "Choose an example case or enter conditions, then call the existing TaxOracle API to check the rules.",
  "tax.select": "Select or enter a case",
  "tax.example": "Example case",
  "tax.custom": "Custom case",
  "tax.start": "税務スクリーニングを開始",
  "tax.running": "Checking rules…",
  "tax.reset": "Reset",
  "tax.error": "Tax data is temporarily unavailable. Try again later.",
  "tax.empty": "No result yet",
  "tax.emptyDetail": "Select a case and start tax screening.",
  "tax.download": "Download HTML report",
  "tax.reportUnavailable": "Complete tax screening before exporting a report",
  "case.title": "保存案件と比較",
  "case.description": "Only case summaries are saved; raw transaction rows and provider payloads are not saved.",
  "case.save": "案件を保存",
  "case.recent": "Recent cases",
  "case.clearCurrent": "Clear current case",
  "case.clearAll": "Clear all cases",
  "case.empty": "No saved cases. Complete a case name and address before saving.",
  "case.compare": "Compare cases",
  "case.compareCount": "Up to 3 cases; {{selected}} selected",
  "case.caseWorkspace": "Case workspace",
  "case.load": "Load",
  "case.delete": "Delete",
  "case.confirmDelete": "Click again to confirm deletion",
  "case.export": "Export HTML report",
  "case.missing": "Missing data: {{items}}",
  "case.status": "Case status",
  "case.address": "Property address/identifier",
  "case.price": "Comparable price",
  "case.ready": "Yes",
  "case.notReady": "No",
  "tour.dialogLabel": "Urban Copilot 製品ガイド",
  "tour.skip": "ガイドを閉じる",
  "tour.previous": "前へ",
  "tour.next": "次へ",
  "tour.finish": "ガイドを完了",
  "tour.openTax": "View tax demo",
  "tour.openMap": "Open Map Insight",
  "tour.explore": "探索を開始",
  "tour.step1Eyebrow": "案件決策ワークスペース",
  "tour.step1Title": "まず案件を選択",
  "tour.step1Description": "税務、位置、価格、ローン情報を一つのワークスペースで確認します。",
  "tour.step2Eyebrow": "税務スクリーニング",
  "tour.step2Title": "税務リスクを確認",
  "tour.step2Description": "既存ルールで資格、リスク、追加資料を整理します。",
  "tour.step3Eyebrow": "地図インサイト",
  "tour.step3Title": "地域を地図で確認",
  "tour.step3Description": "住所または地域を検索し、周辺施設を確認します。",
  "tour.step4Eyebrow": "価格とローン",
  "tour.step4Title": "価格とローンの背景を追加",
  "tour.step4Description": "類似取引とローン情報を参考として確認します。",
  "tour.step5Eyebrow": "顧客向けレポート",
  "tour.step5Title": "説明しやすい要約を作成",
  "tour.step5Description": "判断材料と注意点を HTML レポートに整理します。",
  "tour.skipNotice": "This is a demonstrative decision-support tool. It is not a formal filing, valuation, loan approval, or legal conclusion.",
  "tour.start": "Start tour",
  "tour.caseLowRisk": "Low risk",
  "tour.caseMediumRisk": "Medium risk",
  "tour.caseHighRisk": "High risk",
  "tour.feasible": "Feasible",
  "tour.review": "Review needed",
  "tour.highRisk": "High risk",
  "tour.ruleComplete": "Rules completed",
  "tour.eligibility": "Eligibility",
  "tour.risk": "Risk",
  "tour.missing": "Missing",
  "tour.fiveYear": "Five-year monitoring",
  "tour.searchNearby": "Search nearby",
  "tour.standard": "Standard",
  "tour.light": "Light",
  "tour.satellite": "Satellite",
  "tour.comparableRange": "Comparable valuation range",
  "tour.bankRate": "Bank posted rate",
  "tour.marketReference": "Market reference",
  "tour.riskNotice": "Risk note: bank review is still required",
  "tour.clientReport": "Client communication report",
  "tour.eligibilityReason": "Eligibility",
  "tour.riskReason": "Risk reasons",
  "tour.missingReminder": "Missing information",
  "tour.downloadHtml": "Download HTML report",
  "dashboard.otherTools": "その他の入口とツール",
  "dashboard.flowHeading": "物件情報を入力して内見判断を開始",
  "dashboard.flowDescription": "物件を探し、位置・地勢・通勤・価格・資金を順にチェックし、「この物件を見に行く価値があるか」の保守的な要約にまとめます。",
  "dashboard.flowDetailDescription": "物件決策ワークスペース",
  "dashboard.startFinder": "物件検索を開始",
  "dashboard.runDemo": "まずデモを実行",
  "dashboard.step1": "物件を探す",
  "dashboard.step1Note": "予算、場所、面積を入力",
  "dashboard.step2": "位置を確認",
  "dashboard.step2Note": "位置インサイト、地勢リスク、通勤",
  "dashboard.step3": "価格と資金を計算",
  "dashboard.step3Note": "査定、ローン、維持費、税金",
  "dashboard.step4": "比較して決定",
  "dashboard.step4Note": "保存、比較、レポート、印刷",
  "dashboard.viewingDecision": "内見判断",
  "dashboard.viewingDisclaimer": "この要約は既存の分析結果のみを整理します。不透明なスコアを追加したり、ローン・法律・税務・地勢判断に代わるものではありません。",
  "dashboard.nextActions": "保存・比較・エクスポートとその他のステップ",
  "dashboard.helpMain": "メインフローは物件検索から位置・リスク・査定・資金・内見レポートまで進みます。通勤情報は生活利便性の参考のみで、内見判断に影響しません。",
  "dashboard.advancedTools": "高度なツールと税務補足",
  "dashboard.taxExamples": "TaxOracle サンプル案件",
  "dashboard.taxExamplesNote": "内見レポート完了後、サンプル案件で税務スクリーニングを体験できます。",
  "dashboard.supplementTools": "その他の補足ツール",
  "dashboard.supplementToolsNote": "必要に応じて Map Insight、GeoMap、相場、金利を展開してください。",
  "dashboard.caseLow": "低リスク住替え案件",
  "dashboard.caseLowDesc": "完全な実行可能フローとレポート出力のデモ",
  "dashboard.caseMedium": "中リスク共有持分案件",
  "dashboard.caseMediumDesc": "書類補完と資格再確認のデモ",
  "dashboard.caseHigh": "高リスク非自住案件",
  "dashboard.caseHighDesc": "ルールブロックと重大リスクのデモ",
  "dashboard.taxModule": "税務スクリーニング",
  "dashboard.taxModuleDesc": "資格判定と書類",
  "dashboard.mapModule": "Map Insight / GeoMap",
  "dashboard.mapModuleDesc": "エリアと POI を確認",
  "dashboard.marketModule": "地域相場",
  "dashboard.marketModuleDesc": "市場背景を補足",
  "dashboard.rateModule": "銀行金利",
  "dashboard.rateModuleDesc": "公示住宅ローン関連金利を照会",
  "dashboard.valuationModule": "価格推定",
  "dashboard.valuationModuleDesc": "類似取引から推定範囲を算出",
  "dashboard.expand": "展開",
  "dashboard.ws1Title": "物件を探す",
  "dashboard.ws1Summary": "Property Finder で予算と面積に合う候補路段を探します。",
  "dashboard.ws1Action": "物件検索を開始",
  "dashboard.ws1Note": "入力データがないときはここが最初のステップです。自動検索や二つ目の住所状態は発生しません。",
  "dashboard.ws2Title": "位置を確認",
  "dashboard.ws2Summary": "位置インサイト、地勢／災害リスク、通勤と生活利便性を確認します。",
  "dashboard.ws2Action": "位置を確認",
  "dashboard.ws2Secondary": "地図で確認",
  "dashboard.ws2Note": "通勤情報は手動で照会する必要があり、生活利便性の参考のみです。地勢・ローン・税務・査定・内見判断には影響しません。",
  "dashboard.ws3Title": "価格と資金を計算",
  "dashboard.ws3Summary": "査定、ローン、維持費、税金、市場背景を一か所で操作します。",
  "dashboard.ws3Action": "査定と資金試算",
  "dashboard.ws3Secondary": "税務スクリーニング",
  "dashboard.ws3Note": "各ツールはユーザーが明示的にボタンを押した場合のみ API を呼び出します。データ不足の場合は未完了と表示し、結論を推測しません。",
  "dashboard.ws4Title": "比較して決定",
  "dashboard.ws4Summary": "内見判断、決定レポート、案件保存、比較、印刷／PDF保存を整理します。",
  "dashboard.ws4Action": "内見判断を確認",
  "dashboard.ws4Secondary": "案件を管理",
  "dashboard.ws4Note": "比較レポートは既存の結果のみをまとめます。通勤データはスコアやランキングに含まれず、地勢データ不明は低リスクとみなされません。",
  "tax.caseLabel": "サンプル案件",
  "tax.customLabel": "編集可能",
  "tax.customEditable": "編集可能",
  "tax.customCase": "カスタム案件",
  "tax.caseIdLabel": "案件ID",
  "tax.caseNameLabel": "案件名",
  "tax.apiNote": "POST /taxoracle/analyze を呼び出します。成功するとルール追跡が自動で開きます。",
  "tax.errorLoad": "サンプル案件を一時的に読み込めません。カスタム案件は引き続き使用できます。",
  "tax.errorApi": "税務スクリーニング API の呼び出しに失敗しました。後でもう一度お試しください。",
  "tax.waitingTitle": "税務スクリーニング待機中",
  "tax.waitingDetail": "案件を選択して税務スクリーニングを開始してください。完了すると資格、ルール理由、レポートが表示されます。",
  "tax.runningTitle": "税務スクリーニング実行中",
  "tax.runningDetail": "TaxOracle API が TX001–TX009 を確認中です。完了するとルール結果と書類提案が表示されます。",
  "tax.reportDisabled": "レポートを出力するには、先に税務スクリーニングを完了してください",
  "tax.riskScore": "リスクスコア / 100",
  "tax.signalNote": "シグナル：{{signal}}；法的判断や安全保証ではありません。",
  "tax.noMissing": "現時点で不足書類はありません",
  "tax.aiNotice": "AI は自然言語での説明のみを行います。資格はルールエンジン TX001–TX009 が判定します。",
  "tax.tabReason": "理由",
  "tax.tabTrace": "ルール追跡",
  "tax.tabMissing": "不足書類",
  "tax.tabMonitor": "5年管理",
  "tax.tabAi": "AI 説明",
  "tax.ruleTitle": "TX001–TX009 完全ルール追跡を表示",
  "tax.fieldSold": "売却物件が自住",
  "tax.fieldResidency": "住所登録／居住条件を満たす",
  "tax.fieldPeriod": "買替え期間が妥当",
  "tax.fieldPurchased": "買替え物件が自住",
  "tax.fieldOwner": "所有権主体が一致",
  "tax.fieldLandValue": "公示地価あり",
  "tax.fieldDocs": "書類完備",
  "tax.fieldMonitor": "5年管理に入る",
  "tax.fieldException": "例外事由あり",
  "tax.previewCase": "案件",
  "tax.previewClient": "顧客",
  "tax.previewSoldSelf": "売却自住",
  "tax.previewPurchasedSelf": "買替え自住",
  "tax.previewDocs": "書類完備",
  "tax.previewMonitor": "5年管理",
  "dashboard.mapLoading": "地図を読み込み中...",
  "dashboard.affordMissingPrice": "物件価格が未入力", "dashboard.affordMissingLoan": "ローン未試算", "dashboard.affordMissingHolding": "維持費未試算", "dashboard.affordMissingTax": "TaxOracle 未実行",
};

const ko: RuntimeResource = {
  "action.retry": "Try again",
  "action.reset": "Reset",
  "action.expand": "Expand",
  "action.open": "Open",
  "action.search": "Search",
  "action.loading": "Loading…",
  "action.submit": "Submit",
  "action.download": "Download",
  "action.copy": "Copy",
  "action.calculate": "Calculate",
  "action.startAnalysis": "Start analysis",
  "action.loadDemo": "Load demo conditions",
  "action.save": "Save",
  "action.load": "Load",
  "action.delete": "Delete",
  "action.clear": "Clear",
  "action.compare": "Compare",
  "common.optional": "optional",
  "common.noData": "Insufficient data",
  "common.unavailable": "Temporarily unavailable",
  "common.notStarted": "Not started",
  "common.yes": "Yes",
  "common.no": "No",
  "common.source": "Source",
  "common.updated": "Updated",
  "common.period": "Period",
  "common.count": "Count",
  "common.records": "records",
  "common.dataLimit": "Data limits",
  "common.tableSwipe": "Swipe to view the table",
  "common.selectCounty": "Select county/city",
  "common.selectDistrict": "Select district",
  "common.selectRoad": "Select road",
  "map.kicker": "Maps and livability",
  "map.title": "Map Insight Lite",
  "map.description": "위치를 검색하고 주변 생활 편의와 데이터 출처를 확인합니다.",
  "map.help": "Map results are location references only and may be limited by source coverage and availability.",
  "map.quickMode": "Quick select",
  "map.manualMode": "Manual input",
  "map.city": "County/city",
  "map.district": "District",
  "map.road": "Road or place",
  "map.searchPlaceholder": "Enter an address, landmark, or road",
  "map.radius": "Search radius (m)",
  "map.search": "위치 검색",
  "map.searching": "검색 중…",
  "map.empty": "아직 검색한 위치가 없습니다",
  "map.emptyDetail": "Enter a location and search to view the map and nearby data.",
  "map.nearby": "주변 생활 편의",
  "map.nearbyDescription": "Results are grouped by category and distance for reference only.",
  "map.noResult": "No usable map result is available.",
  "map.searchError": "Map data is temporarily unavailable. Try again later.",
  "map.healthUnavailable": "Map service status is temporarily unavailable.",
  "map.sourceNote": "Source and availability follow the current service response.",
  "map.baseStandard": "기본 지도",
  "map.baseLight": "밝은 지도",
  "map.baseSatellite": "위성 이미지",
  "map.selected": "선택한 위치",
  "map.distance": "거리",
  "map.rating": "평점",
  "location.title": "위치 인사이트",
  "location.description": "Use one property address to review location, terrain/disaster risk, commute, and livability in sequence.",
  "location.address": "Property address",
  "location.radius": "Analysis radius (m)",
  "location.propertyPrice": "Property price (TWD ten-thousands, optional)",
  "location.area": "Area (ping, optional)",
  "location.start": "위치 분석 시작",
  "location.analyzing": "분석 중…",
  "location.empty": "Enter a complete property address and start analysis to call the API.",
  "location.changeNotice": "Changing the address invalidates older location, terrain, and commute results; run the analysis again.",
  "location.noResult": "No usable location result is available.",
  "location.error": "Location data is temporarily unavailable. Try again later.",
  "location.map": "View on map",
  "location.results": "Location analysis",
  "location.score": "Location score",
  "location.strengths": "Location strengths",
  "location.weaknesses": "Location limits",
  "location.poiDetails": "View nearby POI details",
  "location.buyerFit": "Context fit reference",
  "location.dataQuality": "View data quality and limits",
  "location.transit": "Transit",
  "location.convenience": "Convenience",
  "location.education": "Education",
  "location.green": "Green space",
  "location.medical": "Medical",
  "location.risk": "Risk data",
  "finder.title": "Property Finder",
  "finder.description": "Use budget and property conditions to find relevant areas and roads from official transaction data as a viewing reference.",
  "finder.county": "County/city (optional)",
  "finder.district": "District (comma-separated)",
  "finder.budgetMin": "Minimum budget (TWD ten-thousands)",
  "finder.budgetMax": "Maximum budget (TWD ten-thousands)",
  "finder.areaMin": "Minimum area (ping)",
  "finder.areaMax": "Maximum area (ping)",
  "finder.buildingType": "Building type",
  "finder.ageMax": "Maximum age",
  "finder.unlimited": "Any",
  "finder.search": "매물 방향 검색",
  "finder.searching": "검색 중…",
  "finder.demo": "Load demo conditions",
  "finder.sourceNote": "Uses existing official PLVR history only; it does not indicate a listing is currently for sale.",
  "finder.empty": "Search not started",
  "finder.emptyDetail": "Enter budget and location, or load demo conditions before searching.",
  "finder.budgetRequired": "Enter a maximum budget before searching.",
  "finder.error": "Property search data is temporarily unavailable. Try again later.",
  "finder.noData": "No usable official transaction data matches these filters.",
  "finder.results": "Property search results",
  "finder.districts": "Suggested districts",
  "finder.roads": "Suggested roads",
  "finder.transactions": "View transaction samples",
  "finder.useValuation": "Value this road",
  "finder.useLoan": "Calculate payment",
  "finder.useHolding": "Estimate monthly cost",
  "finder.useLocation": "View nearby livability",
  "finder.tableSwipe": "Swipe to view the table",
  "valuation.kicker": "Market reference",
  "valuation.title": "비교 거래 기반 가격 추정",
  "valuation.description": "Choose an area and property conditions to review comparable transaction ranges and confidence.",
  "valuation.help": "Valuation data is maintained by the existing backend pipeline. It is a comparable-transaction reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.criteria": "Valuation conditions",
  "valuation.recheck": "Review official transaction conditions",
  "valuation.share": "Share and export",
  "valuation.shareDescription": "The share link contains query conditions only and does not submit a valuation automatically.",
  "valuation.copyShare": "Copy share link",
  "valuation.download": "Download HTML summary",
  "valuation.useMedian": "Calculate with median estimate",
  "valuation.estimateTotal": "Estimated total",
  "valuation.unitPrice": "Estimated unit price",
  "valuation.confidence": "Confidence",
  "valuation.level": "Valuation level",
  "valuation.basis": "Valuation evidence",
  "valuation.dataSource": "Data source",
  "valuation.composition": "Data composition",
  "valuation.usedRecords": "Transactions used",
  "valuation.sameRoad": "Same road",
  "valuation.sameType": "Same building type",
  "valuation.similarity": "Average similarity",
  "valuation.communityMatch": "Possible community match: {{name}} ({{confidence}})",
  "valuation.noCommunity": "No specific community matched; comparable transactions from the same road or district were used.",
  "valuation.range": "Valuation range",
  "valuation.low": "P25 low",
  "valuation.mid": "Weighted median",
  "valuation.high": "P75 high",
  "valuation.comparables": "View comparable transactions",
  "valuation.disclaimer": "This range is a valuation reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.empty": "Valuation not started",
  "valuation.emptyDetail": "Choose area and property conditions to organize comparable transactions and a valuation range.",
  "valuation.estimate": "가격 추정",
  "valuation.calculating": "추정 중…",
  "valuation.error": "Valuation data is temporarily unavailable. Try again later.",
  "valuation.trend": "Market trend and scenarios",
  "valuation.trendDescription": "Scenarios are organized from existing official transaction trends for reference.",
  "valuation.scenario": "Scenario",
  "valuation.months": "months",
  "valuation.unitPriceScenario": "Scenario unit price",
  "valuation.totalPrice": "Total price reference",
  "valuation.annualRate": "Annual rate",
  "valuation.recentData": "View the latest 24 months",
  "valuation.dataStatus": "Valuation data status",
  "valuation.source": "Current source",
  "valuation.official": "Official imported data",
  "valuation.sample": "Sample data",
  "valuation.mixed": "Official and sample data",
  "valuation.unknownPeriod": "No confirmed period",
  "valuation.unknownData": "Insufficient data",
  "loan.title": "대출 월 납입액 계산",
  "loan.description": "Use transparent formulas to estimate down payment, monthly payment, total interest, and rate sensitivity; entering a price does not submit automatically.",
  "loan.propertyPrice": "Property price (TWD ten-thousands)",
  "loan.downPayment": "Down payment ratio",
  "loan.rate": "Annual interest rate (%)",
  "loan.years": "Loan term (years)",
  "loan.grace": "Grace period (years)",
  "loan.income": "Monthly income (TWD ten-thousands, optional)",
  "loan.calculate": "월 납입액 계산",
  "loan.calculating": "Calculating…",
  "loan.invalid": "Enter a valid price and loan term. The grace period must be shorter than the loan term.",
  "loan.empty": "Estimate not started",
  "loan.emptyDetail": "Enter price, rate, and loan term before calculating payment, total interest, and burden ratio.",
  "loan.error": "Loan estimate is temporarily unavailable. Try again later.",
  "commute.title": "통근 및 생활 편의",
  "commute.description": "Checks only the nearest MRT station and official snapshot time; it does not change risk or viewing conclusions.",
  "commute.check": "통근 정보 확인",
  "commute.checking": "통근 정보 확인 중…",
  "commute.empty": "Enter a complete property address first.",
  "commute.noData": "Insufficient data",
  "commute.station": "Nearest MRT station",
  "commute.lines": "Lines",
  "commute.distance": "Straight-line distance before walking (m)",
  "commute.updated": "Source / updated time",
  "commute.source": "TDX",
  "commute.idle": "아직 조회하지 않았습니다",
  "commute.unresolved": "이 주소에서 신뢰할 수 있는 통근 정보를 찾지 못했습니다.",
  "commute.unavailable": "통근 데이터를 일시적으로 사용할 수 없습니다. 나중에 다시 시도해 주세요.",
  "commute.error": "통근 데이터를 불러오지 못했습니다.",
  "tax.kicker": "Property decision",
  "tax.title": "TaxOracle 세금 검토",
  "tax.description": "Screen reinvestment tax eligibility, five-year monitoring reminders, and communication reports.",
  "tax.help": "Choose an example case or enter conditions, then call the existing TaxOracle API to check the rules.",
  "tax.select": "Select or enter a case",
  "tax.example": "Example case",
  "tax.custom": "Custom case",
  "tax.start": "세금 검토 시작",
  "tax.running": "Checking rules…",
  "tax.reset": "Reset",
  "tax.error": "Tax data is temporarily unavailable. Try again later.",
  "tax.empty": "No result yet",
  "tax.emptyDetail": "Select a case and start tax screening.",
  "tax.download": "Download HTML report",
  "tax.reportUnavailable": "Complete tax screening before exporting a report",
  "case.title": "저장 사례와 비교",
  "case.description": "Only case summaries are saved; raw transaction rows and provider payloads are not saved.",
  "case.save": "사례 저장",
  "case.recent": "Recent cases",
  "case.clearCurrent": "Clear current case",
  "case.clearAll": "Clear all cases",
  "case.empty": "No saved cases. Complete a case name and address before saving.",
  "case.compare": "Compare cases",
  "case.compareCount": "Up to 3 cases; {{selected}} selected",
  "case.caseWorkspace": "Case workspace",
  "case.load": "Load",
  "case.delete": "Delete",
  "case.confirmDelete": "Click again to confirm deletion",
  "case.export": "Export HTML report",
  "case.missing": "Missing data: {{items}}",
  "case.status": "Case status",
  "case.address": "Property address/identifier",
  "case.price": "Comparable price",
  "case.ready": "Yes",
  "case.notReady": "No",
  "tour.dialogLabel": "Urban Copilot 제품 안내",
  "tour.skip": "안내 건너뛰기",
  "tour.previous": "이전",
  "tour.next": "다음",
  "tour.finish": "안내 완료",
  "tour.openTax": "View tax demo",
  "tour.openMap": "Open Map Insight",
  "tour.explore": "탐색 시작",
  "tour.step1Eyebrow": "부동산 사례 워크스페이스",
  "tour.step1Title": "하나의 사례로 시작",
  "tour.step1Description": "세금, 위치, 가격, 대출 정보를 한 화면에서 확인합니다.",
  "tour.step2Eyebrow": "세금 검토",
  "tour.step2Title": "세금 위험 확인",
  "tour.step2Description": "기존 규칙으로 자격, 위험 신호와 보완 자료를 정리합니다.",
  "tour.step3Eyebrow": "지도 인사이트",
  "tour.step3Title": "지도로 지역 확인",
  "tour.step3Description": "주소나 지역을 검색해 주변 시설을 확인합니다.",
  "tour.step4Eyebrow": "가격과 대출",
  "tour.step4Title": "가격과 대출 배경 추가",
  "tour.step4Description": "비교 거래와 대출 정보를 참고 자료로 확인합니다.",
  "tour.step5Eyebrow": "고객 커뮤니케이션",
  "tour.step5Title": "설명하기 쉬운 요약 작성",
  "tour.step5Description": "판단 근거와 주의사항을 HTML 보고서로 정리합니다.",
  "tour.skipNotice": "이 도구는 시연용 의사결정 보조 도구이며 공식 신고, 감정, 대출 승인 또는 법률 결론이 아닙니다.",
  "tour.start": "안내 시작",
  "tour.caseLowRisk": "낮은 위험",
  "tour.caseMediumRisk": "중간 위험",
  "tour.caseHighRisk": "높은 위험",
  "tour.feasible": "가능",
  "tour.review": "검토 필요",
  "tour.highRisk": "높은 위험",
  "tour.ruleComplete": "규칙 판단 완료",
  "tour.eligibility": "자격",
  "tour.risk": "위험",
  "tour.missing": "보완 자료",
  "tour.fiveYear": "5년 관리",
  "tour.searchNearby": "주변 검색",
  "tour.standard": "표준",
  "tour.light": "밝게",
  "tour.satellite": "위성",
  "tour.comparableRange": "비교 거래 가격 범위",
  "tour.bankRate": "은행 공시 금리",
  "tour.marketReference": "시장 참고",
  "tour.riskNotice": "위험 안내: 은행 심사가 필요합니다",
  "tour.clientReport": "고객 커뮤니케이션 보고서",
  "tour.eligibilityReason": "자격 판단",
  "tour.riskReason": "위험 사유",
  "tour.missingReminder": "보완 자료 안내",
  "tour.downloadHtml": "HTML 보고서 다운로드",
  "dashboard.otherTools": "기타 접근 방법 및 도구",
  "dashboard.flowHeading": "물건 정보를 입력하여 방문 결정을 시작",
  "dashboard.flowDescription": "물건을 찾고, 위치·지형·통근·가격·자금을 순서대로 확인한 후 '이 물건을 보러 갈 가치가 있는가'의 보수적 요약으로 정리합니다.",
  "dashboard.flowDetailDescription": "물건 의사결정 워크스페이스",
  "dashboard.startFinder": "물건 검색 시작",
  "dashboard.runDemo": "먼저 데모 실행",
  "dashboard.step1": "물건 찾기",
  "dashboard.step1Note": "예산, 위치, 면적 입력",
  "dashboard.step2": "위치 확인",
  "dashboard.step2Note": "위치 인사이트, 지형 위험, 통근",
  "dashboard.step3": "가격과 자금 계산",
  "dashboard.step3Note": "감정, 대출, 유지비, 세금",
  "dashboard.step4": "비교 및 결정",
  "dashboard.step4Note": "저장, 비교, 보고서, 인쇄",
  "dashboard.viewingDecision": "방문 결정",
  "dashboard.viewingDisclaimer": "이 요약은 기존 분석 결과만 정리합니다. 불투명한 점수를 추가하거나 대출·법률·세금·지형 판단을 대체하지 않습니다.",
  "dashboard.nextActions": "저장, 비교, 내보내기 및 다음 단계",
  "dashboard.helpMain": "메인 흐름은 물건 검색부터 위치, 위험, 감정, 자금, 방문 보고서까지 이어집니다. 통근 정보는 생활 편의 참고용이며 방문 결정에 영향을 주지 않습니다.",
  "dashboard.advancedTools": "고급 도구 및 세금 보충",
  "dashboard.taxExamples": "TaxOracle 예시 사례",
  "dashboard.taxExamplesNote": "방문 보고서 완료 후 예시 사례로 세금 검토를 체험해 보세요.",
  "dashboard.supplementTools": "기타 보충 도구",
  "dashboard.supplementToolsNote": "필요할 때 Map Insight, GeoMap, 시세, 금리를 펼쳐 보세요.",
  "dashboard.caseLow": "저위험 주택 교환",
  "dashboard.caseLowDesc": "완전한 실행 가능 흐름과 보고서 출력 데모",
  "dashboard.caseMedium": "중위험 공유 지분",
  "dashboard.caseMediumDesc": "서류 보완과 자격 재확인 데모",
  "dashboard.caseHigh": "고위험 비자주 거주",
  "dashboard.caseHighDesc": "규칙 차단 및 핵심 위험 데모",
  "dashboard.taxModule": "세금 검토",
  "dashboard.taxModuleDesc": "자격 판정 및 서류",
  "dashboard.mapModule": "Map Insight / GeoMap",
  "dashboard.mapModuleDesc": "지역 및 POI 확인",
  "dashboard.marketModule": "지역 시세",
  "dashboard.marketModuleDesc": "시장 배경 보충",
  "dashboard.rateModule": "은행 금리",
  "dashboard.rateModuleDesc": "공시 주택담보대출 관련 금리 조회",
  "dashboard.valuationModule": "가격 추정",
  "dashboard.valuationModuleDesc": "비교 거래에서 추정 범위 산출",
  "dashboard.expand": "펼치기",
  "dashboard.ws1Title": "물건 찾기",
  "dashboard.ws1Summary": "Property Finder로 예산과 면적에 맞는 후보 도로를 찾습니다.",
  "dashboard.ws1Action": "물건 검색 시작",
  "dashboard.ws1Note": "입력 데이터가 없을 때 여기가 첫 번째 단계입니다. 자동 조회나 두 번째 주소 상태를 생성하지 않습니다.",
  "dashboard.ws2Title": "위치 확인",
  "dashboard.ws2Summary": "위치 인사이트, 지형/재해 위험, 통근, 생활 편의를 확인합니다.",
  "dashboard.ws2Action": "위치 확인",
  "dashboard.ws2Secondary": "지도에서 보기",
  "dashboard.ws2Note": "통근 정보는 수동으로 조회해야 하며 생활 편의 참고용입니다. 지형·대출·세금·감정·방문 결정에 영향을 주지 않습니다.",
  "dashboard.ws3Title": "가격과 자금 계산",
  "dashboard.ws3Summary": "감정, 대출, 유지비, 세금, 시장 배경을 한 곳에서 조작합니다.",
  "dashboard.ws3Action": "감정 및 자금 시산",
  "dashboard.ws3Secondary": "세금 검토",
  "dashboard.ws3Note": "각 도구는 사용자가 버튼을 누를 때만 API를 호출합니다. 데이터 부족 시 미완료로 표시하며 결론을 추측하지 않습니다.",
  "dashboard.ws4Title": "비교 및 결정",
  "dashboard.ws4Summary": "방문 결정, 결정 보고서, 사례 저장, 비교, 인쇄/PDF 저장을 정리합니다.",
  "dashboard.ws4Action": "방문 결정 보기",
  "dashboard.ws4Secondary": "사례 관리",
  "dashboard.ws4Note": "비교 보고서는 기존 결과만 정리합니다. 통근 데이터는 점수나 순위에 포함되지 않으며, 지형 데이터 미확인은 저위험으로 간주되지 않습니다.",
  "tax.caseLabel": "예시 사례",
  "tax.customLabel": "편집 가능",
  "tax.customEditable": "편집 가능",
  "tax.customCase": "사용자 정의 사례",
  "tax.caseIdLabel": "사례 ID",
  "tax.caseNameLabel": "사례명",
  "tax.apiNote": "POST /taxoracle/analyze를 호출합니다. 성공하면 규칙 추적이 자동으로 열립니다.",
  "tax.errorLoad": "예시 사례를 일시적으로 불러올 수 없습니다. 사용자 정의 사례는 계속 사용 가능합니다.",
  "tax.errorApi": "세금 검토 API 호출에 실패했습니다. 나중에 다시 시도해 주세요.",
  "tax.waitingTitle": "세금 검토 대기 중",
  "tax.waitingDetail": "사례를 선택하고 세금 검토를 시작하세요. 완료되면 자격, 규칙 사유, 보고서가 표시됩니다.",
  "tax.runningTitle": "세금 검토 실행 중",
  "tax.runningDetail": "TaxOracle API가 TX001–TX009를 확인 중입니다. 완료되면 규칙 결과와 서류 제안이 표시됩니다.",
  "tax.reportDisabled": "보고서를 출력하려면 먼저 세금 검토를 완료하세요",
  "tax.riskScore": "위험 점수 / 100",
  "tax.signalNote": "신호: {{signal}}; 법적 판단이나 안전 보증이 아닙니다.",
  "tax.noMissing": "현재 누락 서류가 없습니다",
  "tax.aiNotice": "AI는 자연어 설명만 제공합니다. 자격은 규칙 엔진 TX001–TX009이 판정합니다.",
  "tax.tabReason": "사유",
  "tax.tabTrace": "규칙 추적",
  "tax.tabMissing": "누락 서류",
  "tax.tabMonitor": "5년 관리",
  "tax.tabAi": "AI 설명",
  "tax.ruleTitle": "TX001–TX009 전체 규칙 추적 보기",
  "tax.fieldSold": "매도 물건이 자주 거주",
  "tax.fieldResidency": "주소등록/거주 조건 충족",
  "tax.fieldPeriod": "재매입 기간 적정",
  "tax.fieldPurchased": "재매입 물건이 자주 거주",
  "tax.fieldOwner": "소유권 주체 일치",
  "tax.fieldLandValue": "공시지가 구비",
  "tax.fieldDocs": "서류 완비",
  "tax.fieldMonitor": "5년 관리 진입",
  "tax.fieldException": "예외 사유 존재",
  "tax.previewCase": "사례",
  "tax.previewClient": "고객",
  "tax.previewSoldSelf": "매도 자주 거주",
  "tax.previewPurchasedSelf": "재매입 자주 거주",
  "tax.previewDocs": "서류 완비",
  "tax.previewMonitor": "5년 관리",
  "dashboard.mapLoading": "지도 로딩 중...",
  "dashboard.affordMissingPrice": "물건 가격 미입력", "dashboard.affordMissingLoan": "대출 미시산", "dashboard.affordMissingHolding": "유지비 미시산", "dashboard.affordMissingTax": "TaxOracle 미실행",
};

const resources: Record<ExperienceLocale, RuntimeResource> = { "zh-TW": zhTW, en, ja, ko };

export function translateRuntimeCopy(locale: ExperienceLocale, key: RuntimeCopyKey, values: Record<string, string | number> = {}): string {
  const template = getRuntimeCopyOverride(locale, key, values) ?? resources[locale][key] ?? resources["zh-TW"][key] ?? key;
  if (getRuntimeCopyOverride(locale, key, values)) return template;
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)), template);
}

export function getRuntimeCopyCoverage(): Record<ExperienceLocale, { total: number; missing: readonly RuntimeCopyKey[] }> {
  const hasLocalizedValue = (locale: ExperienceLocale, key: RuntimeCopyKey) => Boolean(getRuntimeCopyOverride(locale, key) ?? resources[locale][key]);
  return {
    "zh-TW": { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !hasLocalizedValue("zh-TW", key)) },
    en: { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !hasLocalizedValue("en", key)) },
    ja: { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !hasLocalizedValue("ja", key)) },
    ko: { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !hasLocalizedValue("ko", key)) },
  };
}
