import type { ExperienceLocale } from "@/lib/experience-i18n";

type RuntimeCopyOverride = Partial<Record<string, string>>;

const ja: RuntimeCopyOverride = {
  "common.optional": "任意",
  "common.noData": "データ不足",
  "common.unavailable": "一時的に利用できません",
  "common.notStarted": "未開始",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.source": "データソース",
  "common.updated": "更新日時",
  "common.period": "期間",
  "common.count": "件数",
  "common.records": "件",
  "common.dataLimit": "データの制限",
  "common.tableSwipe": "表を左右にスワイプできます",
  "common.selectCounty": "都道府県・市を選択",
  "common.selectDistrict": "区・郡を選択",
  "common.selectRoad": "道路・場所を選択",
  "map.kicker": "地図と生活機能",
  "map.title": "地図インサイト",
  "map.description": "場所を検索し、周辺の生活機能とデータソースを確認します。",
  "map.help": "地図の結果は立地の参考情報です。データの範囲や利用状況に制限がある場合があります。",
  "map.quickMode": "簡単選択",
  "map.manualMode": "手動入力",
  "map.city": "市・県",
  "map.district": "区・郡",
  "map.road": "道路・場所",
  "map.searchPlaceholder": "住所、ランドマーク、道路を入力",
  "map.radius": "検索半径（m）",
  "map.search": "場所を検索",
  "map.searching": "検索中…",
  "map.empty": "場所はまだ検索されていません",
  "map.emptyDetail": "場所を入力して検索すると、地図と周辺データを表示します。",
  "map.nearby": "周辺の生活機能",
  "map.nearbyDescription": "結果はカテゴリと距離ごとに整理した参考情報です。",
  "map.noResult": "利用できる地図結果がありません。",
  "map.searchError": "地図データを一時的に取得できません。後でもう一度お試しください。",
  "map.healthUnavailable": "地図サービスの状態を確認できません。",
  "map.sourceNote": "ソースと利用状況は現在のサービス応答に基づきます。",
  "map.baseStandard": "標準地図",
  "map.baseLight": "ライト地図",
  "map.baseSatellite": "衛星画像",
  "map.selected": "選択した場所",
  "map.distance": "距離",
  "map.rating": "評価",
  "location.title": "位置情報インサイト",
  "location.description": "1つの物件住所から、位置、地形・災害リスク、通勤、生活機能を順に確認します。",
  "location.address": "物件住所",
  "location.radius": "分析半径（m）",
  "location.propertyPrice": "物件価格（万TWD、任意）",
  "location.area": "面積（坪、任意）",
  "location.start": "位置分析を開始",
  "location.analyzing": "分析中…",
  "location.empty": "物件住所を入力して位置分析を開始してください。",
  "location.changeNotice": "住所を変更すると、以前の位置・地形・通勤結果は無効になります。再度分析してください。",
  "location.noResult": "利用できる位置結果がありません。",
  "location.error": "位置データを一時的に取得できません。後でもう一度お試しください。",
  "location.map": "地図で見る",
  "location.results": "位置分析結果",
  "location.score": "位置スコア",
  "location.strengths": "位置の強み",
  "location.weaknesses": "位置の制限",
  "location.poiDetails": "周辺POIの詳細を見る",
  "location.buyerFit": "利用場面の参考",
  "location.dataQuality": "データ品質と制限を見る",
  "location.transit": "交通",
  "location.convenience": "生活利便性",
  "location.education": "教育",
  "location.green": "緑地",
  "location.medical": "医療",
  "location.risk": "リスクデータ",
  "finder.search": "内見候補を検索",
  "finder.searching": "検索中…",
  "finder.demo": "デモ条件を読み込む",
  "finder.sourceNote": "既存の公式PLVR履歴のみを使用します。現在売り出し中の物件を示すものではありません。",
  "finder.empty": "物件検索はまだ開始されていません",
  "finder.emptyDetail": "検索前に予算と場所を入力するか、デモ条件を読み込んでください。",
  "finder.budgetRequired": "検索するには予算上限を入力してください。",
  "finder.error": "物件検索データを一時的に取得できません。",
  "finder.noData": "条件に一致する公式取引データがありません。",
  "finder.results": "物件検索結果",
  "finder.districts": "候補の区・郡",
  "finder.roads": "候補の道路",
  "finder.transactions": "取引サンプルを見る",
  "finder.useValuation": "この道路を査定する",
  "finder.useLoan": "この価格で返済額を計算",
  "finder.useHolding": "月間コストを見積もる",
  "finder.useLocation": "周辺の生活機能を見る",
  "finder.tableSwipe": "表を左右にスワイプできます",
  "commute.title": "通勤と生活機能",
  "commute.description": "最寄りのMRT駅と公式スナップショット時刻だけを確認します。リスクや内見判断は変更しません。",
  "commute.check": "通勤情報を確認",
  "commute.checking": "通勤情報を確認中…",
  "commute.empty": "物件住所を入力してください。",
  "commute.noData": "データ不足",
  "commute.station": "最寄りのMRT駅",
  "commute.lines": "路線",
  "commute.distance": "歩行前の直線距離（m）",
  "commute.updated": "ソース／更新日時",
  "commute.source": "TDX",
  "commute.idle": "まだ検索していません",
  "commute.unresolved": "この住所から信頼できる通勤情報を取得できませんでした。",
  "commute.unavailable": "通勤データは一時的に利用できません。後でもう一度お試しください。",
  "commute.error": "通勤データを読み込めませんでした。",
  "loan.title": "Aegis-Credit ローン試算",
  "loan.description": "透明な計算式で頭金、月々の返済額、利息合計、金利感度を試算します。入力だけで送信されることはありません。",
  "loan.propertyPrice": "物件価格（万TWD）",
  "loan.downPayment": "頭金比率",
  "loan.rate": "年利（%）",
  "loan.years": "返済期間（年）",
  "loan.grace": "据置期間（年）",
  "loan.income": "月収（万TWD、任意）",
  "loan.calculate": "返済額を計算",
  "loan.calculating": "計算中…",
  "loan.invalid": "有効な価格と返済期間を入力してください。",
  "loan.empty": "試算はまだ開始されていません",
  "loan.emptyDetail": "価格、金利、返済期間を入力して返済額を計算してください。",
  "loan.error": "ローン試算を一時的に利用できません。",
  "tax.title": "TaxOracle 税務スクリーニング",
  "tax.description": "再投資税制の適用可能性、5年間の確認事項、説明用レポートを整理します。",
  "tax.help": "例または条件を入力して、既存のTaxOracle APIでルールを確認します。",
  "tax.select": "案件を選択または入力",
  "tax.example": "例示案件",
  "tax.custom": "カスタム案件",
  "tax.start": "税務チェックを開始",
  "tax.running": "ルールを確認中…",
  "tax.reset": "リセット",
  "tax.error": "税務データを一時的に利用できません。",
  "tax.empty": "結果はまだありません",
  "tax.emptyDetail": "案件を選択して税務チェックを開始してください。",
  "case.title": "保存案件",
  "case.description": "物件の入力、分析結果、次の確認事項をローカルに整理します。",
  "case.save": "案件を保存",
  "case.recent": "保存案件を見る",
  "case.clearCurrent": "現在の案件を解除",
  "case.clearAll": "保存案件をすべて削除",
  "case.empty": "保存案件はありません。",
  "case.compare": "比較",
  "case.compareCount": "{{selected}}件を選択中",
  "case.load": "読み込む",
  "case.delete": "削除",
  "case.confirmDelete": "削除を確認",
  "case.export": "HTMLを出力",
  "case.missing": "不足：{{items}}",
  "case.address": "物件住所",
  "case.price": "価格データ",
};

const ko: RuntimeCopyOverride = {
  "common.optional": "선택 사항",
  "common.noData": "데이터 부족",
  "common.unavailable": "일시적으로 사용할 수 없음",
  "common.notStarted": "시작하지 않음",
  "common.yes": "예",
  "common.no": "아니요",
  "common.source": "데이터 출처",
  "common.updated": "업데이트",
  "common.period": "기간",
  "common.count": "건수",
  "common.records": "건",
  "common.dataLimit": "데이터 제한",
  "common.tableSwipe": "표를 좌우로 스와이프하세요",
  "common.selectCounty": "시·현 선택",
  "common.selectDistrict": "구·군 선택",
  "common.selectRoad": "도로·장소 선택",
  "map.kicker": "지도와 생활 편의",
  "map.title": "지도 인사이트",
  "map.description": "장소를 검색하고 주변 생활 편의 정보와 데이터 출처를 확인합니다.",
  "map.help": "지도 결과는 입지 참고 정보입니다. 출처 범위와 이용 가능성에 제한이 있을 수 있습니다.",
  "map.quickMode": "빠른 선택",
  "map.manualMode": "직접 입력",
  "map.city": "시·현",
  "map.district": "구·군",
  "map.road": "도로·장소",
  "map.searchPlaceholder": "주소, 랜드마크 또는 도로 입력",
  "map.radius": "검색 반경(m)",
  "map.search": "장소 검색",
  "map.searching": "검색 중…",
  "map.empty": "검색한 장소가 없습니다",
  "map.emptyDetail": "장소를 입력하고 검색하면 지도와 주변 데이터를 확인할 수 있습니다.",
  "map.nearby": "주변 생활 편의",
  "map.nearbyDescription": "결과는 카테고리와 거리별 참고 정보로 정리됩니다.",
  "map.noResult": "사용 가능한 지도 결과가 없습니다.",
  "map.searchError": "지도 데이터를 일시적으로 가져올 수 없습니다. 나중에 다시 시도하세요.",
  "map.healthUnavailable": "지도 서비스 상태를 확인할 수 없습니다.",
  "map.sourceNote": "출처와 이용 가능성은 현재 서비스 응답을 따릅니다.",
  "map.baseStandard": "기본 지도",
  "map.baseLight": "밝은 지도",
  "map.baseSatellite": "위성 이미지",
  "map.selected": "선택한 위치",
  "map.distance": "거리",
  "map.rating": "평점",
  "location.title": "위치 인사이트",
  "location.description": "하나의 매물 주소로 위치, 지형·재해 위험, 통근, 생활 편의를 순서대로 확인합니다.",
  "location.address": "매물 주소",
  "location.radius": "분석 반경(m)",
  "location.propertyPrice": "매물 가격(만 TWD, 선택)",
  "location.area": "면적(평, 선택)",
  "location.start": "위치 분석 시작",
  "location.analyzing": "분석 중…",
  "location.empty": "매물 주소를 입력하고 위치 분석을 시작하세요.",
  "location.changeNotice": "주소를 바꾸면 이전 위치·지형·통근 결과가 무효화됩니다. 다시 분석하세요.",
  "location.noResult": "사용 가능한 위치 결과가 없습니다.",
  "location.error": "위치 데이터를 일시적으로 가져올 수 없습니다.",
  "location.map": "지도에서 보기",
  "location.results": "위치 분석 결과",
  "location.score": "위치 점수",
  "location.strengths": "위치 장점",
  "location.weaknesses": "위치 제한",
  "location.poiDetails": "주변 POI 상세 보기",
  "location.buyerFit": "활용 상황 참고",
  "location.dataQuality": "데이터 품질과 제한 보기",
  "location.transit": "교통",
  "location.convenience": "생활 편의",
  "location.education": "교육",
  "location.green": "녹지",
  "location.medical": "의료",
  "location.risk": "위험 데이터",
  "finder.search": "매물 방향 검색",
  "finder.searching": "검색 중…",
  "finder.demo": "데모 조건 불러오기",
  "finder.sourceNote": "기존 공식 PLVR 이력만 사용하며 현재 매물 여부를 의미하지 않습니다.",
  "finder.empty": "매물 검색을 시작하지 않았습니다",
  "finder.emptyDetail": "예산과 위치를 입력하거나 데모 조건을 불러온 뒤 검색하세요.",
  "finder.budgetRequired": "검색하려면 최대 예산을 입력하세요.",
  "finder.error": "매물 검색 데이터를 일시적으로 가져올 수 없습니다.",
  "finder.noData": "조건에 맞는 공식 거래 데이터가 없습니다.",
  "finder.results": "매물 검색 결과",
  "finder.districts": "추천 구·군",
  "finder.roads": "추천 도로",
  "finder.transactions": "거래 샘플 보기",
  "finder.useValuation": "이 도로 평가하기",
  "finder.useLoan": "이 가격으로 상환액 계산",
  "finder.useHolding": "월 비용 추정",
  "finder.useLocation": "주변 생활 편의 보기",
  "finder.tableSwipe": "표를 좌우로 스와이프하세요",
  "commute.title": "통근과 생활 편의",
  "commute.description": "가까운 MRT 역과 공식 스냅샷 시간만 확인하며 위험이나 매물 판단을 바꾸지 않습니다.",
  "commute.check": "통근 정보 확인",
  "commute.checking": "통근 정보 확인 중…",
  "commute.empty": "매물 주소를 입력하세요.",
  "commute.noData": "데이터 부족",
  "commute.station": "가까운 MRT 역",
  "commute.lines": "노선",
  "commute.distance": "도보 전 직선거리(m)",
  "commute.updated": "출처／업데이트 시간",
  "commute.source": "TDX",
  "commute.idle": "아직 조회하지 않음",
  "commute.unresolved": "이 주소에서 신뢰할 수 있는 통근 정보를 찾지 못했습니다.",
  "commute.unavailable": "통근 데이터를 일시적으로 사용할 수 없습니다. 나중에 다시 시도하세요.",
  "commute.error": "통근 데이터를 불러오지 못했습니다.",
  "loan.title": "Aegis-Credit 대출 계산",
  "loan.description": "투명한 공식으로 계약금, 월 상환액, 총이자와 금리 민감도를 계산합니다. 입력만으로 전송되지 않습니다.",
  "loan.propertyPrice": "매물 가격(만 TWD)",
  "loan.downPayment": "계약금 비율",
  "loan.rate": "연 이자율(%)",
  "loan.years": "대출 기간(년)",
  "loan.grace": "거치 기간(년)",
  "loan.income": "월소득(만 TWD, 선택)",
  "loan.calculate": "상환액 계산",
  "loan.calculating": "계산 중…",
  "loan.invalid": "유효한 가격과 대출 기간을 입력하세요.",
  "loan.empty": "계산을 시작하지 않았습니다",
  "loan.emptyDetail": "가격, 금리, 기간을 입력하고 상환액을 계산하세요.",
  "loan.error": "대출 계산을 일시적으로 사용할 수 없습니다.",
  "tax.title": "TaxOracle 세무 확인",
  "tax.description": "재투자 세금 자격, 5년 확인 알림과 안내 보고서를 정리합니다.",
  "tax.help": "예시 또는 조건을 입력한 뒤 기존 TaxOracle API로 규칙을 확인합니다.",
  "tax.select": "사례 선택 또는 입력",
  "tax.example": "예시 사례",
  "tax.custom": "사용자 사례",
  "tax.start": "세무 확인 시작",
  "tax.running": "규칙 확인 중…",
  "tax.reset": "초기화",
  "tax.error": "세무 데이터를 일시적으로 사용할 수 없습니다.",
  "tax.empty": "아직 결과가 없습니다",
  "tax.emptyDetail": "사례를 선택하고 세무 확인을 시작하세요.",
  "case.title": "저장된 사례",
  "case.description": "매물 입력, 분석 결과와 다음 확인 사항을 로컬에 정리합니다.",
  "case.save": "사례 저장",
  "case.recent": "저장된 사례 보기",
  "case.clearCurrent": "현재 사례 지우기",
  "case.clearAll": "저장된 사례 모두 삭제",
  "case.empty": "저장된 사례가 없습니다.",
  "case.compare": "비교",
  "case.compareCount": "{{selected}}개 선택",
  "case.load": "불러오기",
  "case.delete": "삭제",
  "case.confirmDelete": "삭제 확인",
  "case.export": "HTML 내보내기",
  "case.missing": "누락: {{items}}",
  "case.address": "매물 주소",
  "case.price": "가격 데이터",
};

const jaProduction: RuntimeCopyOverride = {
  "locale.switcherLabel": "言語を選択",
  "common.optional": "任意",
  "common.noData": "利用できるデータがありません",
  "common.unavailable": "現在利用できません",
  "common.notStarted": "未開始",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.source": "データソース",
  "common.updated": "更新日",
  "common.period": "期間",
  "common.count": "件数",
  "common.records": "件",
  "common.dataLimit": "データの制限",
  "common.tableSwipe": "表を横にスクロールして確認",
  "common.selectCounty": "市・県を選択",
  "common.selectDistrict": "区・郡を選択",
  "common.selectRoad": "道路を選択",
  "action.open": "開く",
  "action.search": "検索",
  "action.loading": "読み込み中…",
  "action.retry": "再試行",
  "map.kicker": "地図と生活機能",
  "map.title": "地図インサイト",
  "map.description": "場所を検索し、周辺の生活機能とデータソースを確認します。",
  "map.help": "地図の結果は位置情報の参考です。データの範囲と利用状況により制限される場合があります。",
  "map.quickMode": "候補から選択",
  "map.manualMode": "手動入力",
  "map.city": "市・県",
  "map.district": "区・郡",
  "map.road": "道路または場所",
  "map.searchPlaceholder": "住所、ランドマーク、道路を入力",
  "map.radius": "検索範囲（メートル）",
  "map.search": "場所を検索",
  "map.searching": "検索中…",
  "map.empty": "まだ場所を検索していません",
  "map.emptyDetail": "場所を入力して検索すると、地図と周辺データを確認できます。",
  "map.nearby": "周辺の生活機能",
  "map.nearbyDescription": "結果はカテゴリと距離ごとに整理しています。参考情報です。",
  "map.noResult": "利用できる地図結果がありません。",
  "map.searchError": "地図データを取得できません。しばらくしてから再試行してください。",
  "map.healthUnavailable": "地図サービスの状態を確認できません。",
  "map.sourceNote": "ソースと利用状況は現在のサービス応答に基づきます。",
  "map.selected": "選択した場所",
  "map.distance": "距離",
  "map.rating": "評価",
  "commute.check": "通勤情報を確認",
  "commute.checking": "通勤情報を確認中…",
  "commute.unavailable": "通勤データを現在利用できません。しばらくしてから再試行してください。",
  "commute.unresolved": "この住所から信頼できる通勤参考結果を取得できません。",
};

const koProduction: RuntimeCopyOverride = {
  "locale.switcherLabel": "언어 선택",
  "common.optional": "선택 사항",
  "common.noData": "사용 가능한 데이터 없음",
  "common.unavailable": "현재 사용할 수 없음",
  "common.notStarted": "시작하지 않음",
  "common.yes": "예",
  "common.no": "아니요",
  "common.source": "데이터 출처",
  "common.updated": "업데이트",
  "common.period": "기간",
  "common.count": "건수",
  "common.records": "건",
  "common.dataLimit": "데이터 제한",
  "common.tableSwipe": "표를 좌우로 밀어 확인하세요",
  "common.selectCounty": "시·현 선택",
  "common.selectDistrict": "구·군 선택",
  "common.selectRoad": "도로 선택",
  "action.open": "열기",
  "action.search": "검색",
  "action.loading": "불러오는 중…",
  "action.retry": "다시 시도",
  "map.kicker": "지도와 생활 편의",
  "map.title": "지도 인사이트",
  "map.description": "위치를 검색하고 주변 생활 편의와 데이터 출처를 확인합니다.",
  "map.help": "지도 결과는 위치 참고용입니다. 데이터 범위와 사용 가능 여부에 따라 제한될 수 있습니다.",
  "map.quickMode": "빠른 선택",
  "map.manualMode": "직접 입력",
  "map.city": "시·현",
  "map.district": "구·군",
  "map.road": "도로 또는 장소",
  "map.searchPlaceholder": "주소, 랜드마크 또는 도로 입력",
  "map.radius": "검색 반경(미터)",
  "map.search": "위치 검색",
  "map.searching": "검색 중…",
  "map.empty": "아직 검색한 위치가 없습니다",
  "map.emptyDetail": "위치를 입력하고 검색하면 지도와 주변 데이터를 확인할 수 있습니다.",
  "map.nearby": "주변 생활 편의",
  "map.nearbyDescription": "결과는 카테고리와 거리별로 정리한 참고 정보입니다.",
  "map.noResult": "사용 가능한 지도 결과가 없습니다.",
  "map.searchError": "지도 데이터를 가져올 수 없습니다. 잠시 후 다시 시도하세요.",
  "map.healthUnavailable": "지도 서비스 상태를 확인할 수 없습니다.",
  "map.sourceNote": "출처와 사용 가능 여부는 현재 서비스 응답을 따릅니다.",
  "map.selected": "선택한 위치",
  "map.distance": "거리",
  "map.rating": "평점",
  "commute.check": "통근 정보 확인",
  "commute.checking": "통근 정보 확인 중…",
  "commute.unavailable": "통근 데이터를 현재 사용할 수 없습니다. 잠시 후 다시 시도하세요.",
  "commute.unresolved": "이 주소에서 신뢰할 수 있는 통근 참고 결과를 가져올 수 없습니다.",
};

const overrides: Partial<Record<ExperienceLocale, RuntimeCopyOverride>> = {
  ja: { ...ja, ...jaProduction },
  ko: { ...ko, ...koProduction },
};

export function getRuntimeCopyOverride(locale: ExperienceLocale, key: string, values: Record<string, string | number> = {}) {
  const template = overrides[locale]?.[key];
  if (!template) return undefined;
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)), template);
}
