import type { ExperienceLocale } from "@/lib/experience-i18n";

export const RUNTIME_COPY_KEYS = [
  "action.retry", "action.reset", "action.expand", "action.open", "action.search", "action.loading", "action.submit", "action.download", "action.copy", "action.calculate", "action.startAnalysis", "action.loadDemo", "action.save", "action.load", "action.delete", "action.clear", "action.compare",
  "common.optional", "common.noData", "common.unavailable", "common.notStarted", "common.yes", "common.no", "common.source", "common.updated", "common.period", "common.count", "common.records", "common.dataLimit", "common.tableSwipe", "common.selectCounty", "common.selectDistrict", "common.selectRoad",
  "map.kicker", "map.title", "map.description", "map.help", "map.quickMode", "map.manualMode", "map.city", "map.district", "map.road", "map.searchPlaceholder", "map.radius", "map.search", "map.searching", "map.empty", "map.emptyDetail", "map.nearby", "map.nearbyDescription", "map.noResult", "map.searchError", "map.healthUnavailable", "map.sourceNote",
  "location.title", "location.description", "location.address", "location.radius", "location.propertyPrice", "location.area", "location.start", "location.analyzing", "location.empty", "location.changeNotice", "location.noResult", "location.error", "location.map", "location.results", "location.score", "location.strengths", "location.weaknesses", "location.poiDetails", "location.buyerFit", "location.dataQuality", "location.transit", "location.convenience", "location.education", "location.green", "location.medical", "location.risk",
  "finder.title", "finder.description", "finder.county", "finder.district", "finder.budgetMin", "finder.budgetMax", "finder.areaMin", "finder.areaMax", "finder.buildingType", "finder.ageMax", "finder.unlimited", "finder.search", "finder.searching", "finder.demo", "finder.sourceNote", "finder.empty", "finder.emptyDetail", "finder.budgetRequired", "finder.error", "finder.noData", "finder.results", "finder.districts", "finder.roads", "finder.transactions", "finder.useValuation", "finder.useLoan", "finder.useHolding", "finder.useLocation", "finder.tableSwipe",
  "valuation.kicker", "valuation.title", "valuation.description", "valuation.help", "valuation.criteria", "valuation.recheck", "valuation.share", "valuation.shareDescription", "valuation.copyShare", "valuation.download", "valuation.useMedian", "valuation.estimateTotal", "valuation.unitPrice", "valuation.confidence", "valuation.level", "valuation.basis", "valuation.dataSource", "valuation.composition", "valuation.usedRecords", "valuation.sameRoad", "valuation.sameType", "valuation.similarity", "valuation.communityMatch", "valuation.noCommunity", "valuation.range", "valuation.low", "valuation.mid", "valuation.high", "valuation.comparables", "valuation.disclaimer", "valuation.empty", "valuation.emptyDetail", "valuation.estimate", "valuation.calculating", "valuation.error", "valuation.trend", "valuation.trendDescription", "valuation.scenario", "valuation.months", "valuation.unitPriceScenario", "valuation.totalPrice", "valuation.annualRate", "valuation.recentData", "valuation.dataStatus", "valuation.source", "valuation.official", "valuation.sample", "valuation.mixed", "valuation.unknownPeriod", "valuation.unknownData",
  "loan.title", "loan.description", "loan.propertyPrice", "loan.downPayment", "loan.rate", "loan.years", "loan.grace", "loan.income", "loan.calculate", "loan.calculating", "loan.invalid", "loan.empty", "loan.emptyDetail", "loan.error",
  "commute.title", "commute.description", "commute.check", "commute.checking", "commute.empty", "commute.noData", "commute.station", "commute.lines", "commute.distance", "commute.updated", "commute.source", "commute.idle", "commute.unresolved", "commute.unavailable", "commute.error",
  "tax.kicker", "tax.title", "tax.description", "tax.help", "tax.select", "tax.example", "tax.custom", "tax.start", "tax.running", "tax.reset", "tax.error", "tax.empty", "tax.emptyDetail", "tax.download", "tax.reportUnavailable",
  "case.title", "case.description", "case.save", "case.recent", "case.clearCurrent", "case.clearAll", "case.empty", "case.compare", "case.compareCount", "case.caseWorkspace", "case.load", "case.delete", "case.confirmDelete", "case.export", "case.missing", "case.status", "case.address", "case.price", "case.ready", "case.notReady",
  "tour.dialogLabel", "tour.skip", "tour.previous", "tour.next", "tour.finish", "tour.openTax", "tour.openMap", "tour.explore", "tour.step1Eyebrow", "tour.step1Title", "tour.step1Description", "tour.step2Eyebrow", "tour.step2Title", "tour.step2Description", "tour.step3Eyebrow", "tour.step3Title", "tour.step3Description", "tour.step4Eyebrow", "tour.step4Title", "tour.step4Description", "tour.step5Eyebrow", "tour.step5Title", "tour.step5Description", "tour.skipNotice", "tour.start", "tour.caseLowRisk", "tour.caseMediumRisk", "tour.caseHighRisk", "tour.feasible", "tour.review", "tour.highRisk", "tour.ruleComplete", "tour.eligibility", "tour.risk", "tour.missing", "tour.fiveYear", "tour.searchNearby", "tour.standard", "tour.light", "tour.satellite", "tour.comparableRange", "tour.bankRate", "tour.marketReference", "tour.riskNotice", "tour.clientReport", "tour.eligibilityReason", "tour.riskReason", "tour.missingReminder", "tour.downloadHtml",
] as const;

export type RuntimeCopyKey = (typeof RUNTIME_COPY_KEYS)[number];

type RuntimeResource = Record<RuntimeCopyKey, string>;

const zhTW: RuntimeResource = {
  "action.retry": "再試一次", "action.reset": "重設", "action.expand": "展開", "action.open": "開啟", "action.search": "搜尋", "action.loading": "載入中…", "action.submit": "送出", "action.download": "下載", "action.copy": "複製", "action.calculate": "計算", "action.startAnalysis": "開始分析", "action.loadDemo": "載入示範條件", "action.save": "儲存", "action.load": "載入", "action.delete": "刪除", "action.clear": "清除", "action.compare": "比較",
  "common.optional": "可選", "common.noData": "資料不足", "common.unavailable": "暫時無法使用", "common.notStarted": "尚未開始", "common.yes": "是", "common.no": "否", "common.source": "資料來源", "common.updated": "更新時間", "common.period": "期間", "common.count": "筆數", "common.records": "筆", "common.dataLimit": "資料限制", "common.tableSwipe": "表格可左右滑動", "common.selectCounty": "選擇縣市", "common.selectDistrict": "選擇鄉鎮市區", "common.selectRoad": "選擇路段",
  "map.kicker": "地圖與生活機能", "map.title": "Map Insight Lite", "map.description": "搜尋位置並查看附近的生活機能與資料來源。", "map.help": "地圖結果僅供區位參考；資料可能受來源、範圍與可用性限制。", "map.quickMode": "快速選擇", "map.manualMode": "手動輸入", "map.city": "縣市", "map.district": "行政區", "map.road": "路段或地點", "map.searchPlaceholder": "輸入地址、地標或路段", "map.radius": "搜尋半徑（公尺）", "map.search": "搜尋位置", "map.searching": "搜尋中…", "map.empty": "尚未搜尋位置", "map.emptyDetail": "輸入位置後，按下搜尋查看地圖與附近資料。", "map.nearby": "附近生活機能", "map.nearbyDescription": "結果依類別與距離整理，僅供參考。", "map.noResult": "目前沒有可用的地圖結果。", "map.searchError": "地圖資料暫時無法取得，請稍後再試。", "map.healthUnavailable": "地圖服務狀態暫時無法確認。", "map.sourceNote": "來源與可用性依目前服務回應為準。",
  "location.title": "位置洞察", "location.description": "用同一個物件地址，依序完成位置洞察、地勢／災害風險、通勤與生活機能。", "location.address": "物件地址", "location.radius": "分析半徑（公尺）", "location.propertyPrice": "房屋總價（萬元，可選）", "location.area": "坪數（可選）", "location.start": "開始位置分析", "location.analyzing": "分析中…", "location.empty": "請先輸入完整物件地址，按下開始位置分析後才會呼叫 API。", "location.changeNotice": "地址變更後，舊的位置、地勢與通勤結果會失效；請重新分析。", "location.noResult": "目前沒有可用的位置結果。", "location.error": "位置資料暫時無法取得，請稍後再試。", "location.map": "在地圖查看", "location.results": "位置分析結果", "location.score": "位置分數", "location.strengths": "位置優勢", "location.weaknesses": "位置限制", "location.poiDetails": "查看附近 POI 詳細資料", "location.buyerFit": "適合情境參考", "location.dataQuality": "查看資料品質與限制", "location.transit": "交通", "location.convenience": "生活便利", "location.education": "教育", "location.green": "綠地", "location.medical": "醫療", "location.risk": "風險資料",
  "finder.title": "Property Finder", "finder.description": "依預算與條件，從官方實價登錄成交資料找出較符合的區域與路段，作為看屋方向參考。", "finder.county": "縣市（可留空）", "finder.district": "行政區（可用逗號分隔）", "finder.budgetMin": "預算下限（萬元）", "finder.budgetMax": "預算上限（萬元）", "finder.areaMin": "坪數下限", "finder.areaMax": "坪數上限", "finder.buildingType": "建物型態", "finder.ageMax": "屋齡上限", "finder.unlimited": "不限", "finder.search": "搜尋看屋方向", "finder.searching": "搜尋中…", "finder.demo": "載入示範條件", "finder.sourceNote": "僅使用既有官方 PLVR 歷史成交，不代表目前有待售物件。", "finder.empty": "尚未開始找房", "finder.emptyDetail": "請先輸入預算與地點，或載入示範條件後搜尋。", "finder.budgetRequired": "請先輸入預算上限，才能開始找房。", "finder.error": "找房資料暫時無法取得，請稍後再試。", "finder.noData": "目前篩選條件沒有可用的官方交易資料。", "finder.results": "找房結果", "finder.districts": "推薦行政區", "finder.roads": "推薦路段", "finder.transactions": "查看完整成交樣本", "finder.useValuation": "用這個路段估價", "finder.useLoan": "用這個價格算月付", "finder.useHolding": "算每月總支出", "finder.useLocation": "看附近生活機能", "finder.tableSwipe": "表格可左右滑動",
  "valuation.kicker": "市場背景參考", "valuation.title": "實價登錄可比成交估算", "valuation.description": "選擇區域與物件條件，查看可比成交估值區間與信心分數。", "valuation.help": "估價資料由既有後台資料管線維護；結果是可比成交參考，不是保證成交價或購買建議。", "valuation.criteria": "估算條件", "valuation.recheck": "重新查看官方成交條件", "valuation.share": "分享與匯出", "valuation.shareDescription": "分享連結只帶入查詢條件，不會自動送出估價。", "valuation.copyShare": "複製分享連結", "valuation.download": "下載 HTML 摘要", "valuation.useMedian": "用估價中位總價試算", "valuation.estimateTotal": "估算總價", "valuation.unitPrice": "每坪估算單價", "valuation.confidence": "信心分數", "valuation.level": "估價層級", "valuation.basis": "本次估算依據", "valuation.dataSource": "資料來源", "valuation.composition": "資料組成", "valuation.usedRecords": "採用成交", "valuation.sameRoad": "同路段", "valuation.sameType": "同建物類型", "valuation.similarity": "平均相似度", "valuation.communityMatch": "可能命中社區：{{name}}（{{confidence}}）", "valuation.noCommunity": "目前未命中特定社區，改以同路段或同區可比成交估算。", "valuation.range": "估值區間", "valuation.low": "P25 低", "valuation.mid": "加權中位", "valuation.high": "P75 高", "valuation.comparables": "查看完整可比成交", "valuation.disclaimer": "區間是估值參考，不是保證成交價或購買建議。", "valuation.empty": "尚未估算", "valuation.emptyDetail": "選擇區域與物件條件後，系統會整理可比成交與估值區間。", "valuation.estimate": "估算房價", "valuation.calculating": "估算中…", "valuation.error": "估價資料暫時無法取得，請稍後再試。", "valuation.trend": "市場趨勢與未來情境", "valuation.trendDescription": "依既有官方實價登錄趨勢整理情境參考。", "valuation.scenario": "情境", "valuation.months": "個月", "valuation.unitPriceScenario": "每坪情境單價", "valuation.totalPrice": "總價參考", "valuation.annualRate": "採用年率", "valuation.recentData": "查看最近 24 個月資料", "valuation.dataStatus": "估價資料狀態", "valuation.source": "目前資料來源", "valuation.official": "官方匯入資料", "valuation.sample": "展示樣本", "valuation.mixed": "官方與展示混合", "valuation.unknownPeriod": "尚無可確認期間", "valuation.unknownData": "資料不足",
  "loan.title": "貸款月付試算", "loan.description": "用透明公式估算頭期款、月付、總利息與利率變動影響；帶入總價後不會自動送出。", "loan.propertyPrice": "房屋總價（萬元）", "loan.downPayment": "頭期款比例", "loan.rate": "年利率（%）", "loan.years": "貸款年限（年）", "loan.grace": "寬限期年數", "loan.income": "月收入（萬元，可選）", "loan.calculate": "計算貸款月付", "loan.calculating": "試算中…", "loan.invalid": "請先輸入有效總價與貸款年限；寬限期必須小於貸款年限。", "loan.empty": "尚未試算", "loan.emptyDetail": "請先輸入總價、利率與貸款年限，再計算月付、總利息與負擔率。", "loan.error": "貸款試算暫時無法完成，請稍後再試。",
  "commute.title": "通勤與生活機能", "commute.description": "只查最近捷運站與官方快照時間，不會改變風險或看房結論。", "commute.check": "查看通勤資訊", "commute.checking": "正在查詢通勤資訊…", "commute.empty": "請先輸入完整物件地址。", "commute.noData": "資料不足", "commute.station": "最近捷運站", "commute.lines": "路線", "commute.distance": "步行前的直線距離（公尺）", "commute.updated": "資料來源／資料更新時間", "commute.source": "TDX", "commute.idle": "尚未查詢", "commute.unresolved": "目前無法從此地址取得可信的通勤參考結果。", "commute.unavailable": "通勤資料目前無法使用，請稍後再試。", "commute.error": "通勤資料暫時無法取得，請稍後再試。",
  "tax.kicker": "案件決策", "tax.title": "TaxOracle 稅務快篩", "tax.description": "重購退稅資格快篩、五年列管提醒與客戶溝通報告。", "tax.help": "選擇範例案件或自行輸入條件，再呼叫既有 TaxOracle API 檢核規則。", "tax.select": "選擇或輸入案件", "tax.example": "範例案件", "tax.custom": "自訂案件", "tax.start": "開始稅務快篩", "tax.running": "正在檢核規則…", "tax.reset": "重設", "tax.error": "稅務資料暫時無法取得，請稍後再試。", "tax.empty": "尚未產生結果", "tax.emptyDetail": "請先選擇案件，然後按開始稅務快篩。", "tax.download": "下載 HTML 報告", "tax.reportUnavailable": "請先完成稅務快篩才能輸出報告",
  "case.title": "案件儲存與比較", "case.description": "只保存案件摘要，不保存原始交易列或 provider payload。", "case.save": "儲存案件", "case.recent": "最近案件", "case.clearCurrent": "清除目前案件", "case.clearAll": "清除全部案件", "case.empty": "尚未保存案件，完成案件名稱與地址後即可保存。", "case.compare": "比較案件", "case.compareCount": "最多比較 3 件，已選 {{selected}} 件", "case.caseWorkspace": "案件工作台", "case.load": "載入", "case.delete": "刪除", "case.confirmDelete": "再次點擊確認刪除", "case.export": "匯出 HTML 報告", "case.missing": "待補資料：{{items}}", "case.status": "案件狀態", "case.address": "物件地址／識別", "case.price": "可比較價格", "case.ready": "是", "case.notReady": "否",
  "tour.dialogLabel": "Urban Copilot 產品導覽", "tour.skip": "略過導覽", "tour.previous": "上一步", "tour.next": "下一步", "tour.finish": "完成導覽", "tour.openTax": "查看稅務示範", "tour.openMap": "開啟 Map Insight", "tour.explore": "開始探索", "tour.step1Eyebrow": "案件決策工作台", "tour.step1Title": "先從一筆交易案件開始", "tour.step1Description": "選擇展示案件，系統會把稅務、區域、估價與房貸資訊整理在同一個工作台。", "tour.step2Eyebrow": "稅務快篩", "tour.step2Title": "先判斷稅務風險", "tour.step2Description": "系統依既有規則整理資格、風險燈號與補件提醒。AI 只做解釋，不取代規則判斷。", "tour.step3Eyebrow": "地圖洞察", "tour.step3Title": "用地圖看懂這個區域", "tour.step3Description": "搜尋地址或快速選擇區域，查看交通、學校、公園、醫療、商圈與餐飲。", "tour.step4Eyebrow": "價格與房貸背景", "tour.step4Title": "補上價格與房貸背景", "tour.step4Description": "用可比成交樣本查看估值區間與房貸風險背景，這些不是正式鑑價或核貸結果。", "tour.step5Eyebrow": "客戶溝通報告", "tour.step5Title": "整理成可溝通的結論", "tour.step5Description": "下載 HTML 報告，整理資格判斷、風險原因、補件提醒與客戶說明。", "tour.skipNotice": "本系統為展示型決策輔助工具，內容不代表正式申報、鑑價、核貸或法律結論。", "tour.start": "開始導覽", "tour.caseLowRisk": "低風險", "tour.caseMediumRisk": "中風險", "tour.caseHighRisk": "高風險", "tour.feasible": "可行", "tour.review": "需複核", "tour.highRisk": "高風險", "tour.ruleComplete": "規則引擎判斷完成", "tour.eligibility": "資格", "tour.risk": "風險", "tour.missing": "補件", "tour.fiveYear": "五年列管", "tour.searchNearby": "搜尋附近", "tour.standard": "標準", "tour.light": "淺色", "tour.satellite": "衛星", "tour.comparableRange": "可比成交估值區間", "tour.bankRate": "銀行牌告利率", "tour.marketReference": "市場背景參考", "tour.riskNotice": "風險提示：仍需銀行審核", "tour.clientReport": "客戶溝通報告", "tour.eligibilityReason": "資格判斷", "tour.riskReason": "風險原因", "tour.missingReminder": "補件提醒", "tour.downloadHtml": "下載 HTML 報告",
};

const en: RuntimeResource = {
  "action.retry": "Try again", "action.reset": "Reset", "action.expand": "Expand", "action.open": "Open", "action.search": "Search", "action.loading": "Loading…", "action.submit": "Submit", "action.download": "Download", "action.copy": "Copy", "action.calculate": "Calculate", "action.startAnalysis": "Start analysis", "action.loadDemo": "Load demo conditions", "action.save": "Save", "action.load": "Load", "action.delete": "Delete", "action.clear": "Clear", "action.compare": "Compare",
  "common.optional": "optional", "common.noData": "Insufficient data", "common.unavailable": "Temporarily unavailable", "common.notStarted": "Not started", "common.yes": "Yes", "common.no": "No", "common.source": "Source", "common.updated": "Updated", "common.period": "Period", "common.count": "Count", "common.records": "records", "common.dataLimit": "Data limits", "common.tableSwipe": "Swipe to view the table", "common.selectCounty": "Select county/city", "common.selectDistrict": "Select district", "common.selectRoad": "Select road",
  "map.kicker": "Maps and livability", "map.title": "Map Insight Lite", "map.description": "Search a place and review nearby livability information and sources.", "map.help": "Map results are location references only and may be limited by source coverage and availability.", "map.quickMode": "Quick select", "map.manualMode": "Manual input", "map.city": "County/city", "map.district": "District", "map.road": "Road or place", "map.searchPlaceholder": "Enter an address, landmark, or road", "map.radius": "Search radius (m)", "map.search": "Search location", "map.searching": "Searching…", "map.empty": "No location searched", "map.emptyDetail": "Enter a location and search to view the map and nearby data.", "map.nearby": "Nearby livability", "map.nearbyDescription": "Results are grouped by category and distance for reference only.", "map.noResult": "No usable map result is available.", "map.searchError": "Map data is temporarily unavailable. Try again later.", "map.healthUnavailable": "Map service status is temporarily unavailable.", "map.sourceNote": "Source and availability follow the current service response.",
  "location.title": "Location Insight", "location.description": "Use one property address to review location, terrain/disaster risk, commute, and livability in sequence.", "location.address": "Property address", "location.radius": "Analysis radius (m)", "location.propertyPrice": "Property price (TWD ten-thousands, optional)", "location.area": "Area (ping, optional)", "location.start": "Start location analysis", "location.analyzing": "Analyzing…", "location.empty": "Enter a complete property address and start analysis to call the API.", "location.changeNotice": "Changing the address invalidates older location, terrain, and commute results; run the analysis again.", "location.noResult": "No usable location result is available.", "location.error": "Location data is temporarily unavailable. Try again later.", "location.map": "View on map", "location.results": "Location analysis", "location.score": "Location score", "location.strengths": "Location strengths", "location.weaknesses": "Location limits", "location.poiDetails": "View nearby POI details", "location.buyerFit": "Context fit reference", "location.dataQuality": "View data quality and limits", "location.transit": "Transit", "location.convenience": "Convenience", "location.education": "Education", "location.green": "Green space", "location.medical": "Medical", "location.risk": "Risk data",
  "finder.title": "Property Finder", "finder.description": "Use budget and property conditions to find relevant areas and roads from official transaction data as a viewing reference.", "finder.county": "County/city (optional)", "finder.district": "District (comma-separated)", "finder.budgetMin": "Minimum budget (TWD ten-thousands)", "finder.budgetMax": "Maximum budget (TWD ten-thousands)", "finder.areaMin": "Minimum area (ping)", "finder.areaMax": "Maximum area (ping)", "finder.buildingType": "Building type", "finder.ageMax": "Maximum age", "finder.unlimited": "Any", "finder.search": "Search viewing options", "finder.searching": "Searching…", "finder.demo": "Load demo conditions", "finder.sourceNote": "Uses existing official PLVR history only; it does not indicate a listing is currently for sale.", "finder.empty": "Search not started", "finder.emptyDetail": "Enter budget and location, or load demo conditions before searching.", "finder.budgetRequired": "Enter a maximum budget before searching.", "finder.error": "Property search data is temporarily unavailable. Try again later.", "finder.noData": "No usable official transaction data matches these filters.", "finder.results": "Property search results", "finder.districts": "Suggested districts", "finder.roads": "Suggested roads", "finder.transactions": "View transaction samples", "finder.useValuation": "Value this road", "finder.useLoan": "Calculate payment", "finder.useHolding": "Estimate monthly cost", "finder.useLocation": "View nearby livability", "finder.tableSwipe": "Swipe to view the table",
  "valuation.kicker": "Market reference", "valuation.title": "Comparable transaction valuation", "valuation.description": "Choose an area and property conditions to review comparable transaction ranges and confidence.", "valuation.help": "Valuation data is maintained by the existing backend pipeline. It is a comparable-transaction reference, not a guaranteed sale price or purchase recommendation.", "valuation.criteria": "Valuation conditions", "valuation.recheck": "Review official transaction conditions", "valuation.share": "Share and export", "valuation.shareDescription": "The share link contains query conditions only and does not submit a valuation automatically.", "valuation.copyShare": "Copy share link", "valuation.download": "Download HTML summary", "valuation.useMedian": "Calculate with median estimate", "valuation.estimateTotal": "Estimated total", "valuation.unitPrice": "Estimated unit price", "valuation.confidence": "Confidence", "valuation.level": "Valuation level", "valuation.basis": "Valuation evidence", "valuation.dataSource": "Data source", "valuation.composition": "Data composition", "valuation.usedRecords": "Transactions used", "valuation.sameRoad": "Same road", "valuation.sameType": "Same building type", "valuation.similarity": "Average similarity", "valuation.communityMatch": "Possible community match: {{name}} ({{confidence}})", "valuation.noCommunity": "No specific community matched; comparable transactions from the same road or district were used.", "valuation.range": "Valuation range", "valuation.low": "P25 low", "valuation.mid": "Weighted median", "valuation.high": "P75 high", "valuation.comparables": "View comparable transactions", "valuation.disclaimer": "This range is a valuation reference, not a guaranteed sale price or purchase recommendation.", "valuation.empty": "Valuation not started", "valuation.emptyDetail": "Choose area and property conditions to organize comparable transactions and a valuation range.", "valuation.estimate": "Estimate price", "valuation.calculating": "Estimating…", "valuation.error": "Valuation data is temporarily unavailable. Try again later.", "valuation.trend": "Market trend and scenarios", "valuation.trendDescription": "Scenarios are organized from existing official transaction trends for reference.", "valuation.scenario": "Scenario", "valuation.months": "months", "valuation.unitPriceScenario": "Scenario unit price", "valuation.totalPrice": "Total price reference", "valuation.annualRate": "Annual rate", "valuation.recentData": "View the latest 24 months", "valuation.dataStatus": "Valuation data status", "valuation.source": "Current source", "valuation.official": "Official imported data", "valuation.sample": "Sample data", "valuation.mixed": "Official and sample data", "valuation.unknownPeriod": "No confirmed period", "valuation.unknownData": "Insufficient data",
  "loan.title": "Loan payment estimate", "loan.description": "Use transparent formulas to estimate down payment, monthly payment, total interest, and rate sensitivity; entering a price does not submit automatically.", "loan.propertyPrice": "Property price (TWD ten-thousands)", "loan.downPayment": "Down payment ratio", "loan.rate": "Annual interest rate (%)", "loan.years": "Loan term (years)", "loan.grace": "Grace period (years)", "loan.income": "Monthly income (TWD ten-thousands, optional)", "loan.calculate": "Calculate monthly payment", "loan.calculating": "Calculating…", "loan.invalid": "Enter a valid price and loan term. The grace period must be shorter than the loan term.", "loan.empty": "Estimate not started", "loan.emptyDetail": "Enter price, rate, and loan term before calculating payment, total interest, and burden ratio.", "loan.error": "Loan estimate is temporarily unavailable. Try again later.",
  "commute.title": "Commute and livability", "commute.description": "Checks only the nearest MRT station and official snapshot time; it does not change risk or viewing conclusions.", "commute.check": "Check commute information", "commute.checking": "Checking commute information…", "commute.empty": "Enter a complete property address first.", "commute.noData": "Insufficient data", "commute.station": "Nearest MRT station", "commute.lines": "Lines", "commute.distance": "Straight-line distance before walking (m)", "commute.updated": "Source / updated time", "commute.source": "TDX", "commute.idle": "No lookup yet", "commute.unresolved": "No trusted commute reference could be found for this address.", "commute.unavailable": "Commute data is temporarily unavailable. Try again later.", "commute.error": "Commute data could not be loaded. Try again later.",
  "tax.kicker": "Property decision", "tax.title": "TaxOracle tax screening", "tax.description": "Screen reinvestment tax eligibility, five-year monitoring reminders, and communication reports.", "tax.help": "Choose an example case or enter conditions, then call the existing TaxOracle API to check the rules.", "tax.select": "Select or enter a case", "tax.example": "Example case", "tax.custom": "Custom case", "tax.start": "Start tax screening", "tax.running": "Checking rules…", "tax.reset": "Reset", "tax.error": "Tax data is temporarily unavailable. Try again later.", "tax.empty": "No result yet", "tax.emptyDetail": "Select a case and start tax screening.", "tax.download": "Download HTML report", "tax.reportUnavailable": "Complete tax screening before exporting a report",
  "case.title": "Saved cases and comparison", "case.description": "Only case summaries are saved; raw transaction rows and provider payloads are not saved.", "case.save": "Save case", "case.recent": "Recent cases", "case.clearCurrent": "Clear current case", "case.clearAll": "Clear all cases", "case.empty": "No saved cases. Complete a case name and address before saving.", "case.compare": "Compare cases", "case.compareCount": "Up to 3 cases; {{selected}} selected", "case.caseWorkspace": "Case workspace", "case.load": "Load", "case.delete": "Delete", "case.confirmDelete": "Click again to confirm deletion", "case.export": "Export HTML report", "case.missing": "Missing data: {{items}}", "case.status": "Case status", "case.address": "Property address/identifier", "case.price": "Comparable price", "case.ready": "Yes", "case.notReady": "No",
  "tour.dialogLabel": "Urban Copilot product tour", "tour.skip": "Skip tour", "tour.previous": "Previous", "tour.next": "Next", "tour.finish": "Finish tour", "tour.openTax": "View tax demo", "tour.openMap": "Open Map Insight", "tour.explore": "Start exploring", "tour.step1Eyebrow": "Property case workspace", "tour.step1Title": "Start with one property case", "tour.step1Description": "Review tax, location, price, and loan information in one workspace.", "tour.step2Eyebrow": "Tax screening", "tour.step2Title": "Check tax risk first", "tour.step2Description": "Existing rules organize eligibility, risk signals, and missing documents. AI explains but does not replace the rules.", "tour.step3Eyebrow": "Map insight", "tour.step3Title": "Understand the area on a map", "tour.step3Description": "Search an address or area to review nearby facilities.", "tour.step4Eyebrow": "Price and loan context", "tour.step4Title": "Add price and loan context", "tour.step4Description": "Use comparable transactions and loan information as background references, not formal valuation or approval.", "tour.step5Eyebrow": "Client communication report", "tour.step5Title": "Organize a clear summary", "tour.step5Description": "Download an HTML report with eligibility, risks, missing information, and client notes.", "tour.skipNotice": "This is a demonstrative decision-support tool. It is not a formal filing, valuation, loan approval, or legal conclusion.", "tour.start": "Start tour", "tour.caseLowRisk": "Low risk", "tour.caseMediumRisk": "Medium risk", "tour.caseHighRisk": "High risk", "tour.feasible": "Feasible", "tour.review": "Review needed", "tour.highRisk": "High risk", "tour.ruleComplete": "Rules completed", "tour.eligibility": "Eligibility", "tour.risk": "Risk", "tour.missing": "Missing", "tour.fiveYear": "Five-year monitoring", "tour.searchNearby": "Search nearby", "tour.standard": "Standard", "tour.light": "Light", "tour.satellite": "Satellite", "tour.comparableRange": "Comparable valuation range", "tour.bankRate": "Bank posted rate", "tour.marketReference": "Market reference", "tour.riskNotice": "Risk note: bank review is still required", "tour.clientReport": "Client communication report", "tour.eligibilityReason": "Eligibility", "tour.riskReason": "Risk reasons", "tour.missingReminder": "Missing information", "tour.downloadHtml": "Download HTML report",
};

const ja: RuntimeResource = {
  "action.retry": "Try again",
  "action.reset": "Reset",
  "action.expand": "Expand",
  "action.open": "Open",
  "action.search": "Search",
  "action.loading": "Loading…",
  "action.submit": "Submit",
  "action.download": "Download",
  "action.copy": "Copy",
  "action.calculate": "Calculate",
  "action.startAnalysis": "Start analysis",
  "action.loadDemo": "Load demo conditions",
  "action.save": "Save",
  "action.load": "Load",
  "action.delete": "Delete",
  "action.clear": "Clear",
  "action.compare": "Compare",
  "common.optional": "optional",
  "common.noData": "Insufficient data",
  "common.unavailable": "Temporarily unavailable",
  "common.notStarted": "Not started",
  "common.yes": "Yes",
  "common.no": "No",
  "common.source": "Source",
  "common.updated": "Updated",
  "common.period": "Period",
  "common.count": "Count",
  "common.records": "records",
  "common.dataLimit": "Data limits",
  "common.tableSwipe": "Swipe to view the table",
  "common.selectCounty": "Select county/city",
  "common.selectDistrict": "Select district",
  "common.selectRoad": "Select road",
  "map.kicker": "Maps and livability",
  "map.title": "Map Insight Lite",
  "map.description": "場所を検索し、周辺の生活利便性とデータソースを確認します。",
  "map.help": "Map results are location references only and may be limited by source coverage and availability.",
  "map.quickMode": "Quick select",
  "map.manualMode": "Manual input",
  "map.city": "County/city",
  "map.district": "District",
  "map.road": "Road or place",
  "map.searchPlaceholder": "Enter an address, landmark, or road",
  "map.radius": "Search radius (m)",
  "map.search": "場所を検索",
  "map.searching": "検索中…",
  "map.empty": "まだ場所を検索していません",
  "map.emptyDetail": "Enter a location and search to view the map and nearby data.",
  "map.nearby": "周辺の生活利便性",
  "map.nearbyDescription": "Results are grouped by category and distance for reference only.",
  "map.noResult": "No usable map result is available.",
  "map.searchError": "Map data is temporarily unavailable. Try again later.",
  "map.healthUnavailable": "Map service status is temporarily unavailable.",
  "map.sourceNote": "Source and availability follow the current service response.",
  "location.title": "位置インサイト",
  "location.description": "Use one property address to review location, terrain/disaster risk, commute, and livability in sequence.",
  "location.address": "Property address",
  "location.radius": "Analysis radius (m)",
  "location.propertyPrice": "Property price (TWD ten-thousands, optional)",
  "location.area": "Area (ping, optional)",
  "location.start": "位置分析を開始",
  "location.analyzing": "分析中…",
  "location.empty": "Enter a complete property address and start analysis to call the API.",
  "location.changeNotice": "Changing the address invalidates older location, terrain, and commute results; run the analysis again.",
  "location.noResult": "No usable location result is available.",
  "location.error": "Location data is temporarily unavailable. Try again later.",
  "location.map": "View on map",
  "location.results": "Location analysis",
  "location.score": "Location score",
  "location.strengths": "Location strengths",
  "location.weaknesses": "Location limits",
  "location.poiDetails": "View nearby POI details",
  "location.buyerFit": "Context fit reference",
  "location.dataQuality": "View data quality and limits",
  "location.transit": "Transit",
  "location.convenience": "Convenience",
  "location.education": "Education",
  "location.green": "Green space",
  "location.medical": "Medical",
  "location.risk": "Risk data",
  "finder.title": "Property Finder",
  "finder.description": "Use budget and property conditions to find relevant areas and roads from official transaction data as a viewing reference.",
  "finder.county": "County/city (optional)",
  "finder.district": "District (comma-separated)",
  "finder.budgetMin": "Minimum budget (TWD ten-thousands)",
  "finder.budgetMax": "Maximum budget (TWD ten-thousands)",
  "finder.areaMin": "Minimum area (ping)",
  "finder.areaMax": "Maximum area (ping)",
  "finder.buildingType": "Building type",
  "finder.ageMax": "Maximum age",
  "finder.unlimited": "Any",
  "finder.search": "内見候補を検索",
  "finder.searching": "検索中…",
  "finder.demo": "Load demo conditions",
  "finder.sourceNote": "Uses existing official PLVR history only; it does not indicate a listing is currently for sale.",
  "finder.empty": "Search not started",
  "finder.emptyDetail": "Enter budget and location, or load demo conditions before searching.",
  "finder.budgetRequired": "Enter a maximum budget before searching.",
  "finder.error": "Property search data is temporarily unavailable. Try again later.",
  "finder.noData": "No usable official transaction data matches these filters.",
  "finder.results": "Property search results",
  "finder.districts": "Suggested districts",
  "finder.roads": "Suggested roads",
  "finder.transactions": "View transaction samples",
  "finder.useValuation": "Value this road",
  "finder.useLoan": "Calculate payment",
  "finder.useHolding": "Estimate monthly cost",
  "finder.useLocation": "View nearby livability",
  "finder.tableSwipe": "Swipe to view the table",
  "valuation.kicker": "Market reference",
  "valuation.title": "類似取引による価格推定",
  "valuation.description": "Choose an area and property conditions to review comparable transaction ranges and confidence.",
  "valuation.help": "Valuation data is maintained by the existing backend pipeline. It is a comparable-transaction reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.criteria": "Valuation conditions",
  "valuation.recheck": "Review official transaction conditions",
  "valuation.share": "Share and export",
  "valuation.shareDescription": "The share link contains query conditions only and does not submit a valuation automatically.",
  "valuation.copyShare": "Copy share link",
  "valuation.download": "Download HTML summary",
  "valuation.useMedian": "Calculate with median estimate",
  "valuation.estimateTotal": "Estimated total",
  "valuation.unitPrice": "Estimated unit price",
  "valuation.confidence": "Confidence",
  "valuation.level": "Valuation level",
  "valuation.basis": "Valuation evidence",
  "valuation.dataSource": "Data source",
  "valuation.composition": "Data composition",
  "valuation.usedRecords": "Transactions used",
  "valuation.sameRoad": "Same road",
  "valuation.sameType": "Same building type",
  "valuation.similarity": "Average similarity",
  "valuation.communityMatch": "Possible community match: {{name}} ({{confidence}})",
  "valuation.noCommunity": "No specific community matched; comparable transactions from the same road or district were used.",
  "valuation.range": "Valuation range",
  "valuation.low": "P25 low",
  "valuation.mid": "Weighted median",
  "valuation.high": "P75 high",
  "valuation.comparables": "View comparable transactions",
  "valuation.disclaimer": "This range is a valuation reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.empty": "Valuation not started",
  "valuation.emptyDetail": "Choose area and property conditions to organize comparable transactions and a valuation range.",
  "valuation.estimate": "価格を推定",
  "valuation.calculating": "推定中…",
  "valuation.error": "Valuation data is temporarily unavailable. Try again later.",
  "valuation.trend": "Market trend and scenarios",
  "valuation.trendDescription": "Scenarios are organized from existing official transaction trends for reference.",
  "valuation.scenario": "Scenario",
  "valuation.months": "months",
  "valuation.unitPriceScenario": "Scenario unit price",
  "valuation.totalPrice": "Total price reference",
  "valuation.annualRate": "Annual rate",
  "valuation.recentData": "View the latest 24 months",
  "valuation.dataStatus": "Valuation data status",
  "valuation.source": "Current source",
  "valuation.official": "Official imported data",
  "valuation.sample": "Sample data",
  "valuation.mixed": "Official and sample data",
  "valuation.unknownPeriod": "No confirmed period",
  "valuation.unknownData": "Insufficient data",
  "loan.title": "ローン返済額の試算",
  "loan.description": "Use transparent formulas to estimate down payment, monthly payment, total interest, and rate sensitivity; entering a price does not submit automatically.",
  "loan.propertyPrice": "Property price (TWD ten-thousands)",
  "loan.downPayment": "Down payment ratio",
  "loan.rate": "Annual interest rate (%)",
  "loan.years": "Loan term (years)",
  "loan.grace": "Grace period (years)",
  "loan.income": "Monthly income (TWD ten-thousands, optional)",
  "loan.calculate": "月々の返済額を計算",
  "loan.calculating": "Calculating…",
  "loan.invalid": "Enter a valid price and loan term. The grace period must be shorter than the loan term.",
  "loan.empty": "Estimate not started",
  "loan.emptyDetail": "Enter price, rate, and loan term before calculating payment, total interest, and burden ratio.",
  "loan.error": "Loan estimate is temporarily unavailable. Try again later.",
  "commute.title": "通勤と生活利便性",
  "commute.description": "Checks only the nearest MRT station and official snapshot time; it does not change risk or viewing conclusions.",
  "commute.check": "通勤情報を確認",
  "commute.checking": "通勤情報を確認中…",
  "commute.empty": "Enter a complete property address first.",
  "commute.noData": "Insufficient data",
  "commute.station": "Nearest MRT station",
  "commute.lines": "Lines",
  "commute.distance": "Straight-line distance before walking (m)",
  "commute.updated": "Source / updated time",
  "commute.source": "TDX",
  "commute.idle": "まだ検索していません",
  "commute.unresolved": "この住所から信頼できる通勤情報を取得できませんでした。",
  "commute.unavailable": "通勤データは一時的に利用できません。後でもう一度お試しください。",
  "commute.error": "通勤データを読み込めませんでした。",
  "tax.kicker": "Property decision",
  "tax.title": "TaxOracle 税務スクリーニング",
  "tax.description": "Screen reinvestment tax eligibility, five-year monitoring reminders, and communication reports.",
  "tax.help": "Choose an example case or enter conditions, then call the existing TaxOracle API to check the rules.",
  "tax.select": "Select or enter a case",
  "tax.example": "Example case",
  "tax.custom": "Custom case",
  "tax.start": "税務スクリーニングを開始",
  "tax.running": "Checking rules…",
  "tax.reset": "Reset",
  "tax.error": "Tax data is temporarily unavailable. Try again later.",
  "tax.empty": "No result yet",
  "tax.emptyDetail": "Select a case and start tax screening.",
  "tax.download": "Download HTML report",
  "tax.reportUnavailable": "Complete tax screening before exporting a report",
  "case.title": "保存案件と比較",
  "case.description": "Only case summaries are saved; raw transaction rows and provider payloads are not saved.",
  "case.save": "案件を保存",
  "case.recent": "Recent cases",
  "case.clearCurrent": "Clear current case",
  "case.clearAll": "Clear all cases",
  "case.empty": "No saved cases. Complete a case name and address before saving.",
  "case.compare": "Compare cases",
  "case.compareCount": "Up to 3 cases; {{selected}} selected",
  "case.caseWorkspace": "Case workspace",
  "case.load": "Load",
  "case.delete": "Delete",
  "case.confirmDelete": "Click again to confirm deletion",
  "case.export": "Export HTML report",
  "case.missing": "Missing data: {{items}}",
  "case.status": "Case status",
  "case.address": "Property address/identifier",
  "case.price": "Comparable price",
  "case.ready": "Yes",
  "case.notReady": "No",
  "tour.dialogLabel": "Urban Copilot 製品ガイド",
  "tour.skip": "ガイドを閉じる",
  "tour.previous": "前へ",
  "tour.next": "次へ",
  "tour.finish": "ガイドを完了",
  "tour.openTax": "View tax demo",
  "tour.openMap": "Open Map Insight",
  "tour.explore": "探索を開始",
  "tour.step1Eyebrow": "案件決策ワークスペース",
  "tour.step1Title": "まず案件を選択",
  "tour.step1Description": "税務、位置、価格、ローン情報を一つのワークスペースで確認します。",
  "tour.step2Eyebrow": "税務スクリーニング",
  "tour.step2Title": "税務リスクを確認",
  "tour.step2Description": "既存ルールで資格、リスク、追加資料を整理します。",
  "tour.step3Eyebrow": "地図インサイト",
  "tour.step3Title": "地域を地図で確認",
  "tour.step3Description": "住所または地域を検索し、周辺施設を確認します。",
  "tour.step4Eyebrow": "価格とローン",
  "tour.step4Title": "価格とローンの背景を追加",
  "tour.step4Description": "類似取引とローン情報を参考として確認します。",
  "tour.step5Eyebrow": "顧客向けレポート",
  "tour.step5Title": "説明しやすい要約を作成",
  "tour.step5Description": "判断材料と注意点を HTML レポートに整理します。",
  "tour.skipNotice": "This is a demonstrative decision-support tool. It is not a formal filing, valuation, loan approval, or legal conclusion.",
  "tour.start": "Start tour",
  "tour.caseLowRisk": "Low risk",
  "tour.caseMediumRisk": "Medium risk",
  "tour.caseHighRisk": "High risk",
  "tour.feasible": "Feasible",
  "tour.review": "Review needed",
  "tour.highRisk": "High risk",
  "tour.ruleComplete": "Rules completed",
  "tour.eligibility": "Eligibility",
  "tour.risk": "Risk",
  "tour.missing": "Missing",
  "tour.fiveYear": "Five-year monitoring",
  "tour.searchNearby": "Search nearby",
  "tour.standard": "Standard",
  "tour.light": "Light",
  "tour.satellite": "Satellite",
  "tour.comparableRange": "Comparable valuation range",
  "tour.bankRate": "Bank posted rate",
  "tour.marketReference": "Market reference",
  "tour.riskNotice": "Risk note: bank review is still required",
  "tour.clientReport": "Client communication report",
  "tour.eligibilityReason": "Eligibility",
  "tour.riskReason": "Risk reasons",
  "tour.missingReminder": "Missing information",
  "tour.downloadHtml": "Download HTML report",
};

const ko: RuntimeResource = {
  "action.retry": "Try again",
  "action.reset": "Reset",
  "action.expand": "Expand",
  "action.open": "Open",
  "action.search": "Search",
  "action.loading": "Loading…",
  "action.submit": "Submit",
  "action.download": "Download",
  "action.copy": "Copy",
  "action.calculate": "Calculate",
  "action.startAnalysis": "Start analysis",
  "action.loadDemo": "Load demo conditions",
  "action.save": "Save",
  "action.load": "Load",
  "action.delete": "Delete",
  "action.clear": "Clear",
  "action.compare": "Compare",
  "common.optional": "optional",
  "common.noData": "Insufficient data",
  "common.unavailable": "Temporarily unavailable",
  "common.notStarted": "Not started",
  "common.yes": "Yes",
  "common.no": "No",
  "common.source": "Source",
  "common.updated": "Updated",
  "common.period": "Period",
  "common.count": "Count",
  "common.records": "records",
  "common.dataLimit": "Data limits",
  "common.tableSwipe": "Swipe to view the table",
  "common.selectCounty": "Select county/city",
  "common.selectDistrict": "Select district",
  "common.selectRoad": "Select road",
  "map.kicker": "Maps and livability",
  "map.title": "Map Insight Lite",
  "map.description": "위치를 검색하고 주변 생활 편의와 데이터 출처를 확인합니다.",
  "map.help": "Map results are location references only and may be limited by source coverage and availability.",
  "map.quickMode": "Quick select",
  "map.manualMode": "Manual input",
  "map.city": "County/city",
  "map.district": "District",
  "map.road": "Road or place",
  "map.searchPlaceholder": "Enter an address, landmark, or road",
  "map.radius": "Search radius (m)",
  "map.search": "위치 검색",
  "map.searching": "검색 중…",
  "map.empty": "아직 검색한 위치가 없습니다",
  "map.emptyDetail": "Enter a location and search to view the map and nearby data.",
  "map.nearby": "주변 생활 편의",
  "map.nearbyDescription": "Results are grouped by category and distance for reference only.",
  "map.noResult": "No usable map result is available.",
  "map.searchError": "Map data is temporarily unavailable. Try again later.",
  "map.healthUnavailable": "Map service status is temporarily unavailable.",
  "map.sourceNote": "Source and availability follow the current service response.",
  "location.title": "위치 인사이트",
  "location.description": "Use one property address to review location, terrain/disaster risk, commute, and livability in sequence.",
  "location.address": "Property address",
  "location.radius": "Analysis radius (m)",
  "location.propertyPrice": "Property price (TWD ten-thousands, optional)",
  "location.area": "Area (ping, optional)",
  "location.start": "위치 분석 시작",
  "location.analyzing": "분석 중…",
  "location.empty": "Enter a complete property address and start analysis to call the API.",
  "location.changeNotice": "Changing the address invalidates older location, terrain, and commute results; run the analysis again.",
  "location.noResult": "No usable location result is available.",
  "location.error": "Location data is temporarily unavailable. Try again later.",
  "location.map": "View on map",
  "location.results": "Location analysis",
  "location.score": "Location score",
  "location.strengths": "Location strengths",
  "location.weaknesses": "Location limits",
  "location.poiDetails": "View nearby POI details",
  "location.buyerFit": "Context fit reference",
  "location.dataQuality": "View data quality and limits",
  "location.transit": "Transit",
  "location.convenience": "Convenience",
  "location.education": "Education",
  "location.green": "Green space",
  "location.medical": "Medical",
  "location.risk": "Risk data",
  "finder.title": "Property Finder",
  "finder.description": "Use budget and property conditions to find relevant areas and roads from official transaction data as a viewing reference.",
  "finder.county": "County/city (optional)",
  "finder.district": "District (comma-separated)",
  "finder.budgetMin": "Minimum budget (TWD ten-thousands)",
  "finder.budgetMax": "Maximum budget (TWD ten-thousands)",
  "finder.areaMin": "Minimum area (ping)",
  "finder.areaMax": "Maximum area (ping)",
  "finder.buildingType": "Building type",
  "finder.ageMax": "Maximum age",
  "finder.unlimited": "Any",
  "finder.search": "매물 방향 검색",
  "finder.searching": "검색 중…",
  "finder.demo": "Load demo conditions",
  "finder.sourceNote": "Uses existing official PLVR history only; it does not indicate a listing is currently for sale.",
  "finder.empty": "Search not started",
  "finder.emptyDetail": "Enter budget and location, or load demo conditions before searching.",
  "finder.budgetRequired": "Enter a maximum budget before searching.",
  "finder.error": "Property search data is temporarily unavailable. Try again later.",
  "finder.noData": "No usable official transaction data matches these filters.",
  "finder.results": "Property search results",
  "finder.districts": "Suggested districts",
  "finder.roads": "Suggested roads",
  "finder.transactions": "View transaction samples",
  "finder.useValuation": "Value this road",
  "finder.useLoan": "Calculate payment",
  "finder.useHolding": "Estimate monthly cost",
  "finder.useLocation": "View nearby livability",
  "finder.tableSwipe": "Swipe to view the table",
  "valuation.kicker": "Market reference",
  "valuation.title": "비교 거래 기반 가격 추정",
  "valuation.description": "Choose an area and property conditions to review comparable transaction ranges and confidence.",
  "valuation.help": "Valuation data is maintained by the existing backend pipeline. It is a comparable-transaction reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.criteria": "Valuation conditions",
  "valuation.recheck": "Review official transaction conditions",
  "valuation.share": "Share and export",
  "valuation.shareDescription": "The share link contains query conditions only and does not submit a valuation automatically.",
  "valuation.copyShare": "Copy share link",
  "valuation.download": "Download HTML summary",
  "valuation.useMedian": "Calculate with median estimate",
  "valuation.estimateTotal": "Estimated total",
  "valuation.unitPrice": "Estimated unit price",
  "valuation.confidence": "Confidence",
  "valuation.level": "Valuation level",
  "valuation.basis": "Valuation evidence",
  "valuation.dataSource": "Data source",
  "valuation.composition": "Data composition",
  "valuation.usedRecords": "Transactions used",
  "valuation.sameRoad": "Same road",
  "valuation.sameType": "Same building type",
  "valuation.similarity": "Average similarity",
  "valuation.communityMatch": "Possible community match: {{name}} ({{confidence}})",
  "valuation.noCommunity": "No specific community matched; comparable transactions from the same road or district were used.",
  "valuation.range": "Valuation range",
  "valuation.low": "P25 low",
  "valuation.mid": "Weighted median",
  "valuation.high": "P75 high",
  "valuation.comparables": "View comparable transactions",
  "valuation.disclaimer": "This range is a valuation reference, not a guaranteed sale price or purchase recommendation.",
  "valuation.empty": "Valuation not started",
  "valuation.emptyDetail": "Choose area and property conditions to organize comparable transactions and a valuation range.",
  "valuation.estimate": "가격 추정",
  "valuation.calculating": "추정 중…",
  "valuation.error": "Valuation data is temporarily unavailable. Try again later.",
  "valuation.trend": "Market trend and scenarios",
  "valuation.trendDescription": "Scenarios are organized from existing official transaction trends for reference.",
  "valuation.scenario": "Scenario",
  "valuation.months": "months",
  "valuation.unitPriceScenario": "Scenario unit price",
  "valuation.totalPrice": "Total price reference",
  "valuation.annualRate": "Annual rate",
  "valuation.recentData": "View the latest 24 months",
  "valuation.dataStatus": "Valuation data status",
  "valuation.source": "Current source",
  "valuation.official": "Official imported data",
  "valuation.sample": "Sample data",
  "valuation.mixed": "Official and sample data",
  "valuation.unknownPeriod": "No confirmed period",
  "valuation.unknownData": "Insufficient data",
  "loan.title": "대출 월 납입액 계산",
  "loan.description": "Use transparent formulas to estimate down payment, monthly payment, total interest, and rate sensitivity; entering a price does not submit automatically.",
  "loan.propertyPrice": "Property price (TWD ten-thousands)",
  "loan.downPayment": "Down payment ratio",
  "loan.rate": "Annual interest rate (%)",
  "loan.years": "Loan term (years)",
  "loan.grace": "Grace period (years)",
  "loan.income": "Monthly income (TWD ten-thousands, optional)",
  "loan.calculate": "월 납입액 계산",
  "loan.calculating": "Calculating…",
  "loan.invalid": "Enter a valid price and loan term. The grace period must be shorter than the loan term.",
  "loan.empty": "Estimate not started",
  "loan.emptyDetail": "Enter price, rate, and loan term before calculating payment, total interest, and burden ratio.",
  "loan.error": "Loan estimate is temporarily unavailable. Try again later.",
  "commute.title": "통근 및 생활 편의",
  "commute.description": "Checks only the nearest MRT station and official snapshot time; it does not change risk or viewing conclusions.",
  "commute.check": "통근 정보 확인",
  "commute.checking": "통근 정보 확인 중…",
  "commute.empty": "Enter a complete property address first.",
  "commute.noData": "Insufficient data",
  "commute.station": "Nearest MRT station",
  "commute.lines": "Lines",
  "commute.distance": "Straight-line distance before walking (m)",
  "commute.updated": "Source / updated time",
  "commute.source": "TDX",
  "commute.idle": "아직 조회하지 않았습니다",
  "commute.unresolved": "이 주소에서 신뢰할 수 있는 통근 정보를 찾지 못했습니다.",
  "commute.unavailable": "통근 데이터를 일시적으로 사용할 수 없습니다. 나중에 다시 시도해 주세요.",
  "commute.error": "통근 데이터를 불러오지 못했습니다.",
  "tax.kicker": "Property decision",
  "tax.title": "TaxOracle 세금 검토",
  "tax.description": "Screen reinvestment tax eligibility, five-year monitoring reminders, and communication reports.",
  "tax.help": "Choose an example case or enter conditions, then call the existing TaxOracle API to check the rules.",
  "tax.select": "Select or enter a case",
  "tax.example": "Example case",
  "tax.custom": "Custom case",
  "tax.start": "세금 검토 시작",
  "tax.running": "Checking rules…",
  "tax.reset": "Reset",
  "tax.error": "Tax data is temporarily unavailable. Try again later.",
  "tax.empty": "No result yet",
  "tax.emptyDetail": "Select a case and start tax screening.",
  "tax.download": "Download HTML report",
  "tax.reportUnavailable": "Complete tax screening before exporting a report",
  "case.title": "저장 사례와 비교",
  "case.description": "Only case summaries are saved; raw transaction rows and provider payloads are not saved.",
  "case.save": "사례 저장",
  "case.recent": "Recent cases",
  "case.clearCurrent": "Clear current case",
  "case.clearAll": "Clear all cases",
  "case.empty": "No saved cases. Complete a case name and address before saving.",
  "case.compare": "Compare cases",
  "case.compareCount": "Up to 3 cases; {{selected}} selected",
  "case.caseWorkspace": "Case workspace",
  "case.load": "Load",
  "case.delete": "Delete",
  "case.confirmDelete": "Click again to confirm deletion",
  "case.export": "Export HTML report",
  "case.missing": "Missing data: {{items}}",
  "case.status": "Case status",
  "case.address": "Property address/identifier",
  "case.price": "Comparable price",
  "case.ready": "Yes",
  "case.notReady": "No",
  "tour.dialogLabel": "Urban Copilot 제품 안내",
  "tour.skip": "안내 건너뛰기",
  "tour.previous": "이전",
  "tour.next": "다음",
  "tour.finish": "안내 완료",
  "tour.openTax": "View tax demo",
  "tour.openMap": "Open Map Insight",
  "tour.explore": "탐색 시작",
  "tour.step1Eyebrow": "부동산 사례 워크스페이스",
  "tour.step1Title": "하나의 사례로 시작",
  "tour.step1Description": "세금, 위치, 가격, 대출 정보를 한 화면에서 확인합니다.",
  "tour.step2Eyebrow": "세금 검토",
  "tour.step2Title": "세금 위험 확인",
  "tour.step2Description": "기존 규칙으로 자격, 위험 신호와 보완 자료를 정리합니다.",
  "tour.step3Eyebrow": "지도 인사이트",
  "tour.step3Title": "지도로 지역 확인",
  "tour.step3Description": "주소나 지역을 검색해 주변 시설을 확인합니다.",
  "tour.step4Eyebrow": "가격과 대출",
  "tour.step4Title": "가격과 대출 배경 추가",
  "tour.step4Description": "비교 거래와 대출 정보를 참고 자료로 확인합니다.",
  "tour.step5Eyebrow": "고객 커뮤니케이션",
  "tour.step5Title": "설명하기 쉬운 요약 작성",
  "tour.step5Description": "판단 근거와 주의사항을 HTML 보고서로 정리합니다.",
  "tour.skipNotice": "이 도구는 시연용 의사결정 보조 도구이며 공식 신고, 감정, 대출 승인 또는 법률 결론이 아닙니다.",
  "tour.start": "안내 시작",
  "tour.caseLowRisk": "낮은 위험",
  "tour.caseMediumRisk": "중간 위험",
  "tour.caseHighRisk": "높은 위험",
  "tour.feasible": "가능",
  "tour.review": "검토 필요",
  "tour.highRisk": "높은 위험",
  "tour.ruleComplete": "규칙 판단 완료",
  "tour.eligibility": "자격",
  "tour.risk": "위험",
  "tour.missing": "보완 자료",
  "tour.fiveYear": "5년 관리",
  "tour.searchNearby": "주변 검색",
  "tour.standard": "표준",
  "tour.light": "밝게",
  "tour.satellite": "위성",
  "tour.comparableRange": "비교 거래 가격 범위",
  "tour.bankRate": "은행 공시 금리",
  "tour.marketReference": "시장 참고",
  "tour.riskNotice": "위험 안내: 은행 심사가 필요합니다",
  "tour.clientReport": "고객 커뮤니케이션 보고서",
  "tour.eligibilityReason": "자격 판단",
  "tour.riskReason": "위험 사유",
  "tour.missingReminder": "보완 자료 안내",
  "tour.downloadHtml": "HTML 보고서 다운로드",
};

const resources: Record<ExperienceLocale, RuntimeResource> = { "zh-TW": zhTW, en, ja, ko };

export function translateRuntimeCopy(locale: ExperienceLocale, key: RuntimeCopyKey, values: Record<string, string | number> = {}): string {
  const template = resources[locale][key] ?? resources["zh-TW"][key] ?? key;
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)), template);
}

export function getRuntimeCopyCoverage(): Record<ExperienceLocale, { total: number; missing: readonly RuntimeCopyKey[] }> {
  return {
    "zh-TW": { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !resources["zh-TW"][key]) },
    en: { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !resources.en[key]) },
    ja: { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !resources.ja[key]) },
    ko: { total: RUNTIME_COPY_KEYS.length, missing: RUNTIME_COPY_KEYS.filter((key) => !resources.ko[key]) },
  };
}
