import type { ExperienceLocale } from "@/lib/experience-i18n";

const copy = {
  "zh-TW": {
    title: "確認目前查看的房產身分",
    intro: "先輸入觀察資料，再由人員檢視候選項目。地址只是觀察，座標只是一個點；兩者都不會自動證明地號或建物身分。",
    featureOff: "此功能目前尚未在後端開放。直接前往本頁也無法執行身分流程。",
    authMissing: "需要既有的 Supabase 登入工作階段才能使用此工作區。",
    authConfig: "公開的 Supabase 瀏覽器驗證設定尚未完成。",
    workspace: "工作區",
    loadWorkspace: "載入工作區權限",
    roleNote: "畫面上的角色提示只改善操作呈現；FastAPI 仍會逐次驗證權限。",
    inputHeading: "建立身分解析",
    inputKind: "觀察資料類型",
    address: "地址觀察",
    lot: "地號觀察",
    building: "建號觀察",
    coordinates: "座標點",
    mapClick: "地圖點選座標",
    submitResolution: "尋找可能的房產身分",
    openResolution: "開啟既有解析",
    resolutionId: "解析 ID",
    normalized: "後端正規化結果（進階）",
    candidates: "候選項目（仍需人工確認）",
    noPreselect: "系統不會預選排名第一的候選項目。排名與信心值只供檢視。",
    humanRequired: "仍需人工確認",
    confidence: "信心參考",
    coverage: "涵蓋狀態",
    evidence: "證據",
    references: "身分參照",
    limitations: "限制與涵蓋細節",
    conflicts: "衝突",
    reviewed: "我已檢視所選候選項目的來源、涵蓋範圍、限制與衝突。",
    intent: "我明確要以人工判斷確認此候選項目，並了解這不是法律產權認證。",
    reason: "確認理由",
    confirm: "人工確認此候選項目並建立／連結房產",
    rejectCandidate: "拒絕所選候選項目",
    rejectAll: "拒絕整個解析",
    providerUnavailable: "資料提供者目前無法使用；這不代表沒有房產、沒有相符項目、安全或已驗證。",
    ambiguity: "存在歧義；請逐項檢視，系統不會替你選擇。",
    blocking: "存在阻擋衝突，現在不能確認。",
    history: "不可變更的人工決策紀錄",
    property: "已由人員確認的房產摘要",
    selectedCandidate: "伺服器記錄的所選候選項目",
    confirmedCaution: "此狀態記錄人工確認與來源脈絡，不代表政府核發產權、法律所有權或官方地籍認證。",
    graph: "關係圖",
    graphLoad: "載入關係圖",
    evidenceLoad: "載入證據",
    loadMore: "載入下一頁",
    caseHeading: "另行建立並連結案件",
    caseSeparate: "確認房產不會自動連結案件。建立案件與連結都是各自明確的操作。",
    caseTitle: "案件標題",
    createCase: "建立未驗證案件",
    attachCase: "明確將已確認解析連結至此案件",
    caseConflict: "案件已變更。畫面已重新取得目前版本；請檢視後再按一次連結。",
    retrySafe: "上一個指令的結果未知。可安全重試；本次重試會沿用相同識別鍵。",
    retry: "安全重試同一操作",
    notFound: "找不到要求的項目，或你無權查看。為避免跨工作區列舉，不提供更多細節。",
    invalidResponse: "伺服器回應不符合已簽署格式；畫面已採取失敗關閉。",
    invalidInput: "輸入內容不符合已核准格式。請檢查欄位後再試一次。",
    commandSavedRefreshFailed: "指令已由伺服器接受，但目前無法重新載入最新畫面。請重新開啟此解析，不要重送該指令。",
    genericError: "操作無法完成。",
    permissionDenied: "伺服器拒絕此操作的權限。",
    idempotencyConflict: "這次重試與原始指令不一致，已停止操作。",
    staleEvidence: "證據已過期；目前無法確認。",
    conflictingEvidence: "證據彼此衝突；目前無法確認。",
    coverageUnavailable: "來源涵蓋目前無法取得；不會推定成功。",
    maintenance: "服務暫時無法使用。",
    loadWorkspaceFirst: "請先載入此工作區的權限脈絡。",
    invalidObservation: "請完整填寫有效且有界限的觀察資料。",
    confirmationSaved: "人工確認已儲存，並已從伺服器重新載入。未自動連結任何案件。",
    resolutionConflict: "解析已變更並重新載入。請重新檢視目前候選項目後再作決定。",
    rejectionSaved: "拒絕決定已儲存；候選項目與證據歷程仍然可見。",
    rejectionConflict: "解析已變更並重新載入。請檢視目前歷程後再作新的拒絕決定。",
    caseCreated: "案件已建立為未驗證狀態，尚未連結房產。",
    caseAttached: "已透過獨立且明確的指令將確認解析連結至案件。",
    roleRestricted: "只有擁有者或管理員會看到確認控制項；伺服器權限仍是最終依據。",
    working: "處理中",
  },
  en: {
    title: "Confirm the identity of the property you are reviewing",
    intro: "Enter an observation, then review candidates as a person. An address is an observation and coordinates are a point; neither proves parcel or building identity.",
    featureOff: "The backend has not enabled this feature. Direct navigation does not expose a working identity flow.",
    authMissing: "An existing Supabase authenticated session is required.", authConfig: "Public Supabase browser authentication is not configured.",
    workspace: "Workspace", loadWorkspace: "Load workspace access", roleNote: "Role hints only improve presentation; FastAPI authorizes every request.",
    inputHeading: "Create an identity resolution", inputKind: "Observation type", address: "Address observation", lot: "Lot-number observation", building: "Building-number observation", coordinates: "Coordinate point", mapClick: "Map-click point", submitResolution: "Find possible property identities", openResolution: "Open existing resolution", resolutionId: "Resolution ID", normalized: "Backend-normalized input (advanced)",
    candidates: "Candidates (human confirmation required)", noPreselect: "Rank 1 is never preselected. Rank and confidence are review aids only.", humanRequired: "Human confirmation required", confidence: "Confidence reference", coverage: "Coverage", evidence: "Evidence", references: "Identity references", limitations: "Limitations and coverage detail", conflicts: "Conflicts",
    reviewed: "I reviewed the selected candidate's source, coverage, limitations, and conflicts.", intent: "I explicitly intend to confirm this candidate by human judgment and understand this is not legal title certification.", reason: "Confirmation reason", confirm: "Human-confirm candidate and create/link property", rejectCandidate: "Reject selected candidate", rejectAll: "Reject entire resolution",
    providerUnavailable: "A provider is unavailable. This does not mean no property, no match, safe, or verified.", ambiguity: "Identity is ambiguous. Review each candidate; the system will not choose.", blocking: "A blocking conflict prevents confirmation.", history: "Immutable human decision history",
    property: "Human-confirmed property summary", selectedCandidate: "Server-recorded selected candidate", confirmedCaution: "This records a human confirmation and provenance; it is not government title, legal ownership, or official cadastral certification.", graph: "Relationship graph", graphLoad: "Load graph", evidenceLoad: "Load evidence", loadMore: "Load next page",
    caseHeading: "Create and attach a Case separately", caseSeparate: "Property confirmation never attaches a Case automatically. Case creation and attachment are separate explicit commands.", caseTitle: "Case title", createCase: "Create unverified Case", attachCase: "Explicitly attach confirmed resolution to this Case", caseConflict: "The Case changed. Its current version was refreshed; review it and click attach again.",
    retrySafe: "The command outcome is unknown. Retry safely with the same idempotency key.", retry: "Retry the same action safely", notFound: "The item was not found or is not visible to you. No cross-workspace detail is exposed.", invalidResponse: "The server response did not match the signed contract; the UI failed closed.", invalidInput: "The input does not match the approved format. Check the fields and try again.", commandSavedRefreshFailed: "The server accepted the command, but the current view could not be refreshed. Reopen this resolution; do not resubmit that command.", genericError: "The operation could not be completed.",
    permissionDenied: "The server denied permission for this operation.", idempotencyConflict: "This retry differs from the original command, so it was stopped.", staleEvidence: "Evidence is stale; confirmation is blocked.", conflictingEvidence: "Evidence conflicts; confirmation is blocked.", coverageUnavailable: "Source coverage is unavailable; success is not inferred.", maintenance: "The service is temporarily unavailable.", loadWorkspaceFirst: "Load this workspace's access context first.", invalidObservation: "Complete a valid, bounded observation.", confirmationSaved: "Human confirmation was saved and refreshed from the server. No Case was attached automatically.", resolutionConflict: "The resolution changed and was refreshed. Review the current candidates before making a new decision.", rejectionSaved: "The rejection was saved; candidate and evidence history remain visible.", rejectionConflict: "The resolution changed and was refreshed. Review the current history before making a new rejection decision.", caseCreated: "The Case was created as unverified and has not been attached.", caseAttached: "The confirmed resolution was attached to the Case through a separate explicit command.", roleRestricted: "Only an owner or admin is shown confirmation controls; server authorization remains authoritative.", working: "Working",
  },
  ja: {
    title: "確認中の不動産の同一性を確かめる", intro: "観測情報を入力し、人が候補を確認します。住所や座標だけでは土地・建物の同一性は証明されません。", featureOff: "この機能はバックエンドで無効です。", authMissing: "既存の Supabase 認証セッションが必要です。", authConfig: "公開用 Supabase 認証設定がありません。", workspace: "ワークスペース", loadWorkspace: "権限を確認", roleNote: "表示上の役割は補助情報です。最終的な認可は FastAPI が行います。", inputHeading: "同一性解析を作成", inputKind: "観測種別", address: "住所", lot: "地番", building: "建物番号", coordinates: "座標", mapClick: "地図クリック", submitResolution: "候補を検索", openResolution: "既存の解析を開く", resolutionId: "解析 ID", normalized: "正規化結果（詳細）", candidates: "候補（人による確認が必要）", noPreselect: "1位の候補も自動選択されません。", humanRequired: "人による確認が必要", confidence: "信頼度（参考）", coverage: "カバレッジ", evidence: "証拠", references: "参照", limitations: "制限事項", conflicts: "競合", reviewed: "選択した候補の出典・範囲・制限・競合を確認しました。", intent: "法的な権利証明ではないことを理解し、人の判断で確認します。", reason: "確認理由", confirm: "人の判断で候補を確認", rejectCandidate: "選択候補を却下", rejectAll: "解析全体を却下", providerUnavailable: "提供元を利用できません。該当なし・安全・確認済みを意味しません。", ambiguity: "同一性が曖昧です。システムは自動選択しません。", blocking: "重大な競合のため確認できません。", history: "変更不可の判断履歴", property: "人が確認した不動産概要", selectedCandidate: "サーバーに記録された選択候補", confirmedCaution: "法的所有権や公的地籍の証明ではありません。", graph: "関係グラフ", graphLoad: "グラフを表示", evidenceLoad: "証拠を表示", loadMore: "次を表示", caseHeading: "案件は別操作で作成・関連付け", caseSeparate: "確認後も案件は自動関連付けされません。", caseTitle: "案件名", createCase: "未確認案件を作成", attachCase: "確認済み解析を案件に関連付け", caseConflict: "案件が変更されたため最新版を取得しました。確認後に再実行してください。", retrySafe: "結果が不明です。同じ識別キーで安全に再試行できます。", retry: "同じ操作を安全に再試行", notFound: "対象が存在しないか閲覧権限がありません。", invalidResponse: "応答形式が契約と一致しないため安全側で停止しました。", invalidInput: "入力が承認済み形式と一致しません。各項目を確認して再実行してください。", commandSavedRefreshFailed: "コマンドは保存されましたが、最新表示を取得できませんでした。この解析を開き直し、同じコマンドを再送しないでください。", genericError: "操作を完了できませんでした。",
    permissionDenied: "この操作はサーバーにより許可されませんでした。", idempotencyConflict: "再試行の内容が元のコマンドと異なるため停止しました。", staleEvidence: "証拠が古いため確認できません。", conflictingEvidence: "証拠が競合しているため確認できません。", coverageUnavailable: "情報源の範囲を取得できないため、成功とは判断しません。", maintenance: "サービスは一時的に利用できません。", loadWorkspaceFirst: "先にワークスペースのアクセス情報を読み込んでください。", invalidObservation: "有効で範囲内の観測情報を入力してください。", confirmationSaved: "人による確認を保存し、サーバーから再読み込みしました。案件は自動関連付けされていません。", resolutionConflict: "解析が変更されたため再読み込みしました。現在の候補を確認してから再度判断してください。", rejectionSaved: "却下を保存しました。候補と証拠の履歴は引き続き表示されます。", rejectionConflict: "解析が変更されたため再読み込みしました。現在の履歴を確認してから再度却下してください。", caseCreated: "未確認の案件を作成しました。まだ不動産には関連付けられていません。", caseAttached: "別の明示的なコマンドで、確認済み解析を案件に関連付けました。", roleRestricted: "確認操作は所有者または管理者にのみ表示され、最終的な認可はサーバーが行います。", working: "処理中",
  },
  ko: {
    title: "검토 중인 부동산 신원 확인", intro: "관찰 정보를 입력한 뒤 사람이 후보를 검토합니다. 주소와 좌표만으로 필지나 건물 신원이 증명되지는 않습니다.", featureOff: "백엔드에서 이 기능이 비활성화되어 있습니다.", authMissing: "기존 Supabase 인증 세션이 필요합니다.", authConfig: "공개 Supabase 브라우저 인증 설정이 없습니다.", workspace: "워크스페이스", loadWorkspace: "접근 권한 확인", roleNote: "화면의 역할 표시는 안내용이며 FastAPI가 매 요청을 승인합니다.", inputHeading: "신원 확인 요청 만들기", inputKind: "관찰 유형", address: "주소 관찰", lot: "필지 번호", building: "건물 번호", coordinates: "좌표", mapClick: "지도 클릭 좌표", submitResolution: "가능한 신원 찾기", openResolution: "기존 확인 열기", resolutionId: "확인 ID", normalized: "정규화 결과(고급)", candidates: "후보(사람의 확인 필요)", noPreselect: "1순위 후보도 자동 선택되지 않습니다.", humanRequired: "사람의 확인 필요", confidence: "신뢰도 참고", coverage: "범위", evidence: "증거", references: "참조", limitations: "제한 및 범위", conflicts: "충돌", reviewed: "선택한 후보의 출처, 범위, 제한 및 충돌을 검토했습니다.", intent: "법적 소유권 인증이 아님을 이해하고 사람의 판단으로 확인합니다.", reason: "확인 사유", confirm: "사람의 판단으로 후보 확인", rejectCandidate: "선택 후보 거절", rejectAll: "전체 확인 거절", providerUnavailable: "제공자를 사용할 수 없습니다. 일치 없음, 안전 또는 확인됨을 뜻하지 않습니다.", ambiguity: "신원이 모호합니다. 시스템은 자동 선택하지 않습니다.", blocking: "차단 충돌로 인해 확인할 수 없습니다.", history: "변경할 수 없는 판단 기록", property: "사람이 확인한 부동산 요약", selectedCandidate: "서버에 기록된 선택 후보", confirmedCaution: "법적 소유권이나 공식 지적 인증이 아닙니다.", graph: "관계 그래프", graphLoad: "그래프 불러오기", evidenceLoad: "증거 불러오기", loadMore: "다음 페이지", caseHeading: "별도로 Case 생성 및 연결", caseSeparate: "확인 후에도 Case는 자동 연결되지 않습니다.", caseTitle: "Case 제목", createCase: "미확인 Case 생성", attachCase: "확인된 결과를 Case에 명시적으로 연결", caseConflict: "Case가 변경되어 현재 버전을 불러왔습니다. 검토 후 다시 실행하세요.", retrySafe: "결과를 알 수 없습니다. 같은 식별 키로 안전하게 다시 시도할 수 있습니다.", retry: "같은 작업 안전하게 재시도", notFound: "항목을 찾을 수 없거나 볼 권한이 없습니다.", invalidResponse: "응답이 계약과 맞지 않아 안전하게 중단했습니다.", invalidInput: "입력이 승인된 형식과 맞지 않습니다. 필드를 확인한 뒤 다시 시도하세요.", commandSavedRefreshFailed: "명령은 저장되었지만 최신 화면을 불러오지 못했습니다. 이 확인을 다시 열고 같은 명령을 다시 보내지 마세요.", genericError: "작업을 완료할 수 없습니다.",
    permissionDenied: "서버가 이 작업의 권한을 거부했습니다.", idempotencyConflict: "재시도 내용이 원래 명령과 달라 작업을 중단했습니다.", staleEvidence: "증거가 오래되어 확인할 수 없습니다.", conflictingEvidence: "증거가 충돌하여 확인할 수 없습니다.", coverageUnavailable: "출처 범위를 사용할 수 없어 성공으로 판단하지 않습니다.", maintenance: "서비스를 일시적으로 사용할 수 없습니다.", loadWorkspaceFirst: "먼저 워크스페이스 접근 정보를 불러오세요.", invalidObservation: "유효하고 범위가 제한된 관찰 정보를 입력하세요.", confirmationSaved: "사람의 확인을 저장하고 서버에서 다시 불러왔습니다. Case는 자동 연결되지 않았습니다.", resolutionConflict: "확인 내용이 변경되어 다시 불러왔습니다. 현재 후보를 검토한 뒤 다시 결정하세요.", rejectionSaved: "거절 결정을 저장했습니다. 후보와 증거 이력은 계속 표시됩니다.", rejectionConflict: "확인 내용이 변경되어 다시 불러왔습니다. 현재 이력을 검토한 뒤 다시 거절하세요.", caseCreated: "미확인 Case를 만들었습니다. 아직 부동산에 연결되지 않았습니다.", caseAttached: "별도의 명시적 명령으로 확인된 결과를 Case에 연결했습니다.", roleRestricted: "확인 컨트롤은 소유자 또는 관리자에게만 표시되며 최종 권한은 서버가 확인합니다.", working: "처리 중",
  },
} as const;

export type IdentityCopy = { [Key in keyof (typeof copy)["en"]]: string };

export function getIdentityCopy(locale: ExperienceLocale): IdentityCopy {
  return copy[locale];
}
