from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from io import BytesIO
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

TEMPLATE_DIR = Path(__file__).resolve().parents[1] / "templates"


@dataclass(frozen=True)
class ReportContext:
    module_name: str
    module_slug: str
    assessment_id: int
    created_at: datetime
    input_summary: dict[str, Any]
    analysis_result: dict[str, Any]
    data_sources: list[str]
    disclaimer: str


environment = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    autoescape=select_autoescape(["html", "xml"]),
)


MODULE_LABELS = {
    "aegis-credit": "Aegis-Credit Mortgage Risk",
    "tax-oracle": "TaxOracle Repurchase Tax Review",
    "lex-prop": "LexProp Title Risk",
}

INPUT_FIELDS = {
    "aegis-credit": [
        "applicant_name",
        "property_address",
        "property_value",
        "loan_amount",
        "monthly_income",
        "existing_debt",
        "loan_term_years",
    ],
    "tax-oracle": [
        "taxpayer_name",
        "property_address",
        "assessed_value",
        "replacement_purchase_value",
        "annual_rental_income",
        "holding_years",
        "transaction_type",
        "is_self_use",
        "has_outstanding_tax_debt",
    ],
    "lex-prop": [
        "owner_name",
        "property_address",
        "title_number",
        "has_lien",
        "has_easement",
        "dispute_notes",
    ],
}

DATA_SOURCES = {
    "aegis-credit": [
        "User-submitted mortgage intake form",
        "Local deterministic Aegis-Credit MVP rules engine",
        "Local PostgreSQL assessment record",
    ],
    "tax-oracle": [
        "User-submitted tax scenario form",
        "Local deterministic TaxOracle repurchase refund rules engine",
        "Local PostgreSQL assessment record",
    ],
    "lex-prop": [
        "User-submitted title risk intake form",
        "Local LexProp keyword classifier rules",
        "Local PostgreSQL assessment record",
    ],
}

DISCLAIMER = (
    "This report is generated by an MVP rules engine for internal workflow prototyping only. "
    "It does not use real external APIs, machine learning, legal advice, tax advice, credit bureau data, "
    "or official registry verification. Human professional review is required before any business decision."
)


def build_report_context(module_slug: str, assessment: Any) -> ReportContext:
    result = dict(assessment.mock_result or {})
    return ReportContext(
        module_name=MODULE_LABELS[module_slug],
        module_slug=module_slug,
        assessment_id=assessment.id,
        created_at=assessment.created_at,
        input_summary=_input_summary(module_slug, assessment),
        analysis_result=result,
        data_sources=DATA_SOURCES[module_slug],
        disclaimer=DISCLAIMER,
    )


def render_report_html(context: ReportContext) -> str:
    template = environment.get_template("assessment_report.html")
    return template.render(report=context)


def render_report_pdf(html: str) -> bytes:
    from xhtml2pdf import pisa

    output = BytesIO()
    pdf = pisa.CreatePDF(src=html, dest=output, encoding="utf-8")
    if pdf.err:
        raise ValueError("Unable to render PDF report")
    return output.getvalue()


def _input_summary(module_slug: str, assessment: Any) -> dict[str, Any]:
    return {
        field: _serialize_value(getattr(assessment, field))
        for field in INPUT_FIELDS[module_slug]
    }


def _serialize_value(value: Any) -> Any:
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, datetime):
        return value.isoformat()
    return value
