-- PropTech AI Copilot valuation database schema for Supabase/Postgres.
-- Apply through Supabase SQL Editor or a reviewed migration process.

create table if not exists real_price_transactions (
    id bigint generated by default as identity primary key,
    transaction_period varchar(7) not null,
    city text not null,
    district text not null,
    road text not null,
    address_text text default '',
    building_type text not null,
    area_ping numeric(12, 2) not null,
    building_age_years numeric(8, 2) not null default 0,
    floor integer not null default 0,
    total_floor integer,
    unit_price_per_ping numeric(14, 2) not null,
    total_price numeric(16, 2) not null,
    lat double precision,
    lng double precision,
    source text not null,
    dedupe_key text,
    imported_at timestamptz not null default now(),
    raw_note text default ''
);

create index if not exists idx_real_price_city_district_road on real_price_transactions (city, district, road);
create index if not exists idx_real_price_city_district on real_price_transactions (city, district);
create index if not exists idx_real_price_building_type on real_price_transactions (building_type);
create index if not exists idx_real_price_transaction_period on real_price_transactions (transaction_period desc);
create index if not exists idx_real_price_lat_lng on real_price_transactions (lat, lng);
create unique index if not exists uq_real_price_source_dedupe_key
    on real_price_transactions (source, dedupe_key)
    where dedupe_key is not null;

create table if not exists community_buildings (
    community_id text primary key,
    community_name text not null,
    city text not null,
    district text not null,
    road text not null,
    address_pattern text default '',
    lat double precision,
    lng double precision,
    building_type text,
    completed_year integer,
    total_floors integer,
    source text not null,
    confidence text not null default 'low',
    updated_at timestamptz not null default now()
);

create index if not exists idx_community_city_district_road on community_buildings (city, district, road);
create index if not exists idx_community_name on community_buildings (community_name);

create table if not exists valuation_import_runs (
    id bigint generated by default as identity primary key,
    source_name text not null,
    source_period text,
    imported_at timestamptz not null default now(),
    record_count integer not null default 0,
    city_scope text default '',
    district_scope text default '',
    road_scope text default '',
    input_file_count integer not null default 0,
    read_rows integer not null default 0,
    accepted_rows integer not null default 0,
    inserted_rows integer not null default 0,
    updated_rows integer not null default 0,
    skipped_duplicate_rows integer not null default 0,
    excluded_rows integer not null default 0,
    status text not null,
    note text default ''
);
