-- Official PLVR market pipeline metadata and atomically published read model.
-- Raw archives remain outside the repository and are never exposed publicly.
create table if not exists official_market_releases (
    release_id text primary key,
    source_id text not null,
    publication_date date,
    discovered_at timestamptz not null default now(),
    schema_version text,
    archive_sha256 text,
    status text not null check (status in ('discovered','validated','published','failed','rolled_back')),
    is_active boolean not null default false,
    input_rows integer not null default 0,
    accepted_rows integer not null default 0,
    warning_rows integer not null default 0,
    quarantined_rows integer not null default 0,
    duplicate_rows integer not null default 0,
    cancelled_rows integer not null default 0,
    failure_phase text,
    failure_reason_code text
);

create table if not exists official_market_artifacts (
    artifact_id bigint generated by default as identity primary key,
    release_id text not null references official_market_releases(release_id) on delete cascade,
    artifact_role text not null check (artifact_role in ('manifest','schema','transaction_archive','transaction_file')),
    source_name text not null,
    sha256 text not null,
    byte_size bigint not null check (byte_size >= 0),
    acquired_at timestamptz not null default now(),
    retention_until timestamptz,
    unique (release_id, artifact_role, sha256)
);

create table if not exists market_transactions (
    transaction_id text primary key,
    release_id text not null references official_market_releases(release_id) on delete restrict,
    source_id text not null,
    source_record_id text,
    transaction_type text not null,
    county text not null,
    district text not null,
    transaction_date date,
    area_sqm numeric(14, 4),
    total_price_ntd numeric(20, 2),
    unit_price_ntd_sqm numeric(18, 4),
    unit_price_ntd_ping numeric(18, 4),
    parking_area_sqm numeric(14, 4),
    parking_price_ntd numeric(20, 2),
    building_type text,
    special_transaction_flags jsonb not null default '[]'::jsonb,
    validation_status text not null,
    dedupe_fingerprint text not null,
    imported_at timestamptz not null default now(),
    unique (release_id, dedupe_fingerprint)
);

create index if not exists idx_market_transactions_region_period on market_transactions (county, district, transaction_date, transaction_type);
create index if not exists idx_market_transactions_release on market_transactions (release_id);
create index if not exists idx_market_transactions_quality on market_transactions (validation_status);

create table if not exists market_transaction_quality_events (
    event_id bigint generated by default as identity primary key,
    transaction_id text references market_transactions(transaction_id) on delete cascade,
    release_id text not null references official_market_releases(release_id) on delete cascade,
    reason_code text not null,
    created_at timestamptz not null default now()
);

create table if not exists market_region_period_aggregates (
    release_id text not null references official_market_releases(release_id) on delete restrict,
    county text not null,
    district text not null,
    period varchar(7) not null,
    transaction_type text not null,
    sample_status text not null check (sample_status in ('sufficient','limited','insufficient','no_data','unavailable')),
    transaction_count integer not null check (transaction_count >= 0),
    valid_comparable_count integer not null check (valid_comparable_count >= 0),
    median_unit_price_ntd_sqm numeric(18, 4),
    mean_unit_price_ntd_sqm numeric(18, 4),
    lower_quartile_unit_price_ntd_sqm numeric(18, 4),
    upper_quartile_unit_price_ntd_sqm numeric(18, 4),
    minimum_unit_price_ntd_sqm numeric(18, 4),
    maximum_unit_price_ntd_sqm numeric(18, 4),
    median_total_price_ntd numeric(20, 2),
    median_area_sqm numeric(14, 4),
    total_transaction_value_ntd numeric(22, 2),
    aggregation_version text not null,
    source_updated_at date,
    coverage_status text not null,
    data_status text not null,
    primary key (release_id, county, district, period, transaction_type)
);

create index if not exists idx_market_aggregates_region_period on market_region_period_aggregates (county, district, period desc);

create table if not exists official_market_region_coverage (
    release_id text not null references official_market_releases(release_id) on delete restrict,
    county text not null,
    district text not null,
    coverage_status text not null,
    latest_period varchar(7),
    record_count integer not null default 0,
    source_updated_at date,
    primary key (release_id, county, district)
);

create index if not exists idx_official_market_region_coverage_region_period
    on official_market_region_coverage (county, district, latest_period desc);

create table if not exists market_import_runs (
    import_run_id uuid primary key,
    release_id text references official_market_releases(release_id) on delete restrict,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    status text not null check (status in ('running','succeeded','failed','cancelled')),
    phase text,
    failure_reason_code text,
    evidence jsonb not null default '{}'::jsonb
);

create table if not exists market_import_checkpoints (
    import_run_id uuid primary key references market_import_runs(import_run_id) on delete cascade,
    release_cursor text,
    row_cursor bigint not null default 0,
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_market_active_release on official_market_releases (is_active) where is_active;
