import type { MapLayerViewModel, MapWorkspaceViewModel, ParcelFeatureViewModel } from "./contract";

const candidateParcels = [
  {
    geometryId: "demo-geometry-candidate-a-v1",
    parcelIdentityReferenceId: "demo-parcel-ref-a",
    layerKey: "parcel_candidates",
    label: "Candidate parcel A",
    relationship: "candidate",
    matchBasis: "Synthetic location reference overlaps the demo search area.",
    areaLabel: "Approx. 486 m²",
    confidenceLabel: "Review rank 1 of 2",
    evidenceId: "demo-evidence-parcel-a",
    sourceLabel: "Synthetic parcel index",
    authority: "synthetic",
    polygon: [[160, 116], [350, 92], [385, 250], [182, 274]],
  },
  {
    geometryId: "demo-geometry-candidate-b-v1",
    parcelIdentityReferenceId: "demo-parcel-ref-b",
    layerKey: "parcel_candidates",
    label: "Candidate parcel B",
    relationship: "candidate",
    matchBasis: "Synthetic identifier fragment is similar; jurisdiction remains unchecked.",
    areaLabel: "Approx. 421 m²",
    confidenceLabel: "Review rank 2 of 2",
    evidenceId: "demo-evidence-parcel-b",
    sourceLabel: "Synthetic parcel index",
    authority: "synthetic",
    polygon: [[385, 250], [556, 230], [584, 376], [414, 402]],
  },
] as const satisfies readonly ParcelFeatureViewModel[];

const confirmedParcels = [
  {
    geometryId: "demo-geometry-confirmed-v3",
    parcelIdentityReferenceId: "demo-parcel-ref-reviewed",
    layerKey: "confirmed_parcel",
    label: "Reviewed working geometry",
    relationship: "confirmed_working_geometry",
    matchBasis: "A prior synthetic human-review record selected this working geometry.",
    areaLabel: "Approx. 462 m²",
    evidenceId: "demo-evidence-confirmed-v3",
    sourceLabel: "Synthetic review ledger",
    authority: "synthetic",
    polygon: [[98, 292], [273, 270], [302, 423], [122, 446]],
  },
] as const satisfies readonly ParcelFeatureViewModel[];

const layers = [
  {
    key: "parcel_candidates",
    title: "Parcel candidates",
    category: "parcel",
    status: "present",
    selectedByDefault: true,
    sourceLabel: "Synthetic parcel index",
    authority: "synthetic",
    attribution: "Demo fixture · Parcel candidate set 2026.09",
    evidenceId: "demo-observation-parcel-candidates",
    observedAt: "2026-09-01T09:00:00+08:00",
    coverageLabel: "Demo search window only",
    summary: "Two possible parcel geometries are available for inspection.",
    limitation: "Candidate rank and overlap do not establish parcel identity, title, ownership, or legal boundary.",
    color: "#6d5bd0",
    lineStyle: "dashed",
  },
  {
    key: "confirmed_parcel",
    title: "Reviewed working geometry",
    category: "parcel",
    status: "present",
    selectedByDefault: true,
    sourceLabel: "Synthetic review ledger",
    authority: "synthetic",
    attribution: "Demo fixture · Prior human-review record",
    evidenceId: "demo-observation-confirmed-parcel",
    observedAt: "2026-08-18T14:20:00+08:00",
    coverageLabel: "One synthetic review record",
    summary: "A previously reviewed working geometry is shown separately from current candidates.",
    limitation: "Reviewed working geometry is not a legal boundary or proof of ownership.",
    color: "#12715b",
    lineStyle: "solid",
  },
  {
    key: "planning_reference",
    title: "Planning reference",
    category: "planning",
    status: "present",
    selectedByDefault: true,
    sourceLabel: "Synthetic planning snapshot",
    authority: "synthetic",
    attribution: "Demo fixture · Planning scenario 04",
    evidenceId: "demo-observation-planning",
    observedAt: "2026-08-28T10:10:00+08:00",
    coverageLabel: "Complete for the synthetic viewport",
    summary: "A demo planning corridor intersects part of the investigation area.",
    limitation: "The corridor is illustrative and cannot support a planning or development decision.",
    color: "#c4782f",
    lineStyle: "solid",
  },
  {
    key: "access_context",
    title: "Access context",
    category: "access",
    status: "partial_coverage",
    selectedByDefault: true,
    sourceLabel: "Synthetic access survey",
    authority: "synthetic",
    attribution: "Demo fixture · Access survey sample",
    evidenceId: "demo-observation-access",
    observedAt: "2026-08-30T11:40:00+08:00",
    coverageLabel: "Partial · east edge not surveyed",
    summary: "One observed access line is shown; the east edge has no survey coverage.",
    limitation: "Unsurveyed edges remain unknown. The visible line does not prove legal access.",
    color: "#167e9b",
    lineStyle: "dashed",
  },
  {
    key: "environment_screen",
    title: "Environmental screen",
    category: "environment",
    status: "unknown",
    selectedByDefault: true,
    sourceLabel: "Synthetic environmental screen",
    authority: "synthetic",
    attribution: "Demo fixture · Unassessed environmental layer",
    evidenceId: "demo-observation-environment",
    observedAt: "2026-09-01T09:05:00+08:00",
    coverageLabel: "Coverage cannot be established",
    summary: "The fixture cannot determine whether an environmental feature is present.",
    limitation: "Unknown is not a negative result and must not be interpreted as safe or no risk.",
    color: "#71678a",
    lineStyle: "dotted",
  },
  {
    key: "heritage_context",
    title: "Heritage context",
    category: "reference",
    status: "unavailable",
    selectedByDefault: true,
    sourceLabel: "Synthetic heritage adapter",
    authority: "synthetic",
    attribution: "Demo fixture · Provider unavailable scenario",
    evidenceId: "demo-observation-heritage",
    observedAt: "2026-09-01T09:06:00+08:00",
    coverageLabel: "Provider unavailable",
    summary: "The synthetic provider did not return an answer for this check.",
    limitation: "Unavailable does not establish absence. Re-check the source before relying on this layer.",
    color: "#a14652",
    lineStyle: "dotted",
  },
  {
    key: "soil_history",
    title: "Soil history",
    category: "environment",
    status: "stale",
    selectedByDefault: false,
    sourceLabel: "Synthetic historical survey",
    authority: "synthetic",
    attribution: "Demo fixture · Archived soil sample",
    evidenceId: "demo-observation-soil",
    observedAt: "2024-11-12T08:00:00+08:00",
    coverageLabel: "Historical snapshot · freshness expired",
    summary: "A historical observation exists outside the demo freshness window.",
    limitation: "Refresh is required before the historical observation can inform consequential review.",
    color: "#8d6e4a",
    lineStyle: "dashed",
  },
  {
    key: "structure_match",
    title: "Structure match",
    category: "reference",
    status: "no_match",
    selectedByDefault: true,
    sourceLabel: "Synthetic structure index",
    authority: "synthetic",
    attribution: "Demo fixture · Structure query result",
    evidenceId: "demo-observation-structure",
    observedAt: "2026-09-01T09:07:00+08:00",
    coverageLabel: "Match attempted · absence not proven",
    summary: "No matching structure was returned by the demo query.",
    limitation: "No match is not proof that no structure exists and is not a safety finding.",
    color: "#6b7280",
    lineStyle: "dotted",
  },
] as const satisfies readonly MapLayerViewModel[];

export const syntheticMapWorkspace: MapWorkspaceViewModel = {
  context: {
    workspaceId: "demo-workspace-07",
    caseId: "demo-case-2408",
    caseTitle: "Synthetic acquisition review · Scenario 24-08",
    purpose: "Buy-side due diligence",
    reviewStage: "Spatial evidence review",
    reviewOwner: "Demo review team",
    selectedPropertyEntity: {
      propertyEntityId: "demo-property-entity-03",
      displayLabel: "Synthetic property scenario C",
      locationSummary: "Demo district · Taiwan reference grid",
      identityStatus: "reviewed",
    },
  },
  candidateParcels,
  confirmedParcels,
  layers,
  observationIds: layers.map((layer) => layer.evidenceId),
  viewport: {
    centerLongitude: 120.9816,
    centerLatitude: 23.9739,
    zoom: 17,
    bounds: [120.976, 23.968, 120.987, 23.98],
  },
  limitations: [
    "Everything on this page is deterministic Synthetic / Demo data for component development.",
    "Selecting a parcel only changes the inspection focus. It does not confirm identity or create any record or link.",
    "Geometry, overlap, proximity, and layer results do not establish legal parcel ownership, legal boundary, suitability, or safety.",
    "Empty, unknown, unavailable, stale, partial, and no-match layers require follow-up; none means no risk.",
  ],
};
