"""Read-only authenticated Property Identity production smoke checks.

Configuration is environment-only. Output contains only fixed check names,
HTTP status codes, and correlation IDs generated by this process.
"""

from __future__ import annotations

import base64
import json
import os
import re
from dataclasses import dataclass, field
from typing import Mapping, Protocol
from urllib.error import HTTPError
from urllib.parse import urlsplit
from urllib.request import HTTPRedirectHandler, ProxyHandler, Request, build_opener
from uuid import UUID, uuid4


TIMEOUT_SECONDS = 10.0
CONTROL_BODY_LIMIT = 4096
_JWT_SEGMENT = re.compile(r"^[A-Za-z0-9_-]+={0,2}$")
_CORRELATION_ID = re.compile(r"^[0-9a-f]{32}$")
_SAFE_CHECK_NAMES = frozenset({
    "configuration", "token_invalid", "service_role_refused", "write_mode_refused",
    "WRITE_MODE_UNSUPPORTED", "runtime", "authenticated_root", "property",
    "property_graph", "property_evidence", "unauthenticated_control",
})


class SmokeConfigurationError(ValueError):
    """Configuration refusal carrying only a fixed, safe check name."""


@dataclass(frozen=True)
class SmokeConfig:
    base_url: str
    token: str = field(repr=False)
    workspace_id: UUID
    property_id: UUID
    write_mode: bool


@dataclass(frozen=True)
class HttpResponse:
    status: int
    headers: Mapping[str, str] = field(repr=False)
    body: bytes = field(repr=False)


@dataclass(frozen=True)
class CheckResult:
    name: str
    passed: bool
    status: int
    correlation_id: str = "-"

    def line(self) -> str:
        outcome = "PASS" if self.passed else "FAIL"
        status = self.status if isinstance(self.status, int) and (self.status == 0 or 100 <= self.status <= 599) else 0
        correlation_id = self.correlation_id if _CORRELATION_ID.fullmatch(self.correlation_id) else "-"
        name = self.name if self.name in _SAFE_CHECK_NAMES else "runtime"
        return f"{outcome} status={status} correlation_id={correlation_id} check={name}"


class SmokeClient(Protocol):
    def request(
        self, method: str, url: str, *, headers: Mapping[str, str],
        timeout: float, max_body_bytes: int,
    ) -> HttpResponse: ...


class _NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, request, fp, code, msg, headers, newurl):
        return None


class UrllibSmokeClient:
    """Bounded GET transport that never follows a redirect with Authorization."""

    def __init__(self) -> None:
        self._opener = build_opener(ProxyHandler({}), _NoRedirect())

    def request(
        self, method: str, url: str, *, headers: Mapping[str, str],
        timeout: float, max_body_bytes: int,
    ) -> HttpResponse:
        if method != "GET":
            raise ValueError("unsupported HTTP method")
        request = Request(url, method=method, headers=dict(headers))
        try:
            with self._opener.open(request, timeout=timeout) as response:
                return HttpResponse(
                    response.status,
                    dict(response.headers.items()),
                    response.read(max_body_bytes),
                )
        except HTTPError as error:
            with error:
                return HttpResponse(
                    error.code,
                    dict(error.headers.items()),
                    error.read(max_body_bytes),
                )


def validate_base_url(value: str) -> str:
    """Require a single safe API origin, allowing HTTP only on exact loopback hosts."""

    try:
        if not value or any(char.isspace() or char == "\\" for char in value) or "?" in value or "#" in value:
            raise ValueError
        parsed = urlsplit(value)
        host = parsed.hostname
        port = parsed.port  # Also rejects invalid port syntax.
        if (
            parsed.scheme not in {"http", "https"}
            or not host
            or not parsed.netloc
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path not in {"", "/"}
            or (parsed.scheme == "http" and host.lower() not in {"localhost", "127.0.0.1"})
        ):
            raise ValueError
        authority = host.lower()
        if ":" in authority:
            authority = f"[{authority}]"
        if port is not None:
            authority = f"{authority}:{port}"
        return f"{parsed.scheme}://{authority}"
    except ValueError:
        raise ValueError("unsafe API base URL") from None


def _refuse_service_role(token: str) -> None:
    """Inspect only the untrusted JWT payload; the API authenticates the token."""

    if not token or len(token) > 16_384 or any(char.isspace() for char in token):
        raise SmokeConfigurationError("token_invalid")
    segments = token.split(".")
    if len(segments) != 3 or any(not _JWT_SEGMENT.fullmatch(part) for part in segments):
        raise SmokeConfigurationError("token_invalid")
    try:
        payload_bytes = base64.urlsafe_b64decode(segments[1] + "=" * (-len(segments[1]) % 4))
        payload = json.loads(payload_bytes.decode("utf-8"))
    except (ValueError, UnicodeDecodeError):
        raise SmokeConfigurationError("token_invalid") from None
    if not isinstance(payload, dict):
        raise SmokeConfigurationError("token_invalid")
    if payload.get("role") == "service_role":
        raise SmokeConfigurationError("service_role_refused")


def _load_config(environ: Mapping[str, str]) -> SmokeConfig:
    try:
        base_url = validate_base_url(environ.get("SMOKE_API_BASE_URL", ""))
        workspace_id = UUID(environ["SMOKE_WORKSPACE_ID"])
        property_id = UUID(environ["SMOKE_PROPERTY_ENTITY_ID"])
    except (KeyError, TypeError, ValueError):
        raise SmokeConfigurationError("configuration") from None

    token = environ.get("SMOKE_USER_BEARER_TOKEN", "")
    _refuse_service_role(token)

    write_value = environ.get("SMOKE_WRITE_MODE", "false")
    if write_value not in {"false", "true"}:
        raise SmokeConfigurationError("write_mode_refused")
    write_mode = write_value == "true"
    if write_mode:
        try:
            test_workspace_id = UUID(environ["SMOKE_TEST_WORKSPACE_ID"])
        except (KeyError, TypeError, ValueError):
            raise SmokeConfigurationError("write_mode_refused") from None
        if test_workspace_id != workspace_id:
            raise SmokeConfigurationError("write_mode_refused")
    return SmokeConfig(base_url, token, workspace_id, property_id, write_mode)


def _headers_are_safe(headers: Mapping[str, str], *, remote: bool) -> bool:
    required = {
        "cache-control": "private, no-store",
        "x-content-type-options": "nosniff",
        "x-frame-options": "DENY",
        "referrer-policy": "strict-origin-when-cross-origin",
        "cross-origin-opener-policy": "same-origin",
        "cross-origin-resource-policy": "same-site",
        "content-security-policy": "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",
        "permissions-policy": "camera=(), geolocation=(), payment=(), usb=(), serial=(), bluetooth=(), microphone=(self)",
    }
    if any(headers.get(name) != value for name, value in required.items()):
        return False
    if remote and headers.get("strict-transport-security") != "max-age=31536000; includeSubDomains":
        return False
    return True


def _control_is_authentication_required(body: bytes) -> bool:
    try:
        payload = json.loads(body.decode("utf-8"))
        return isinstance(payload, dict) and payload.get("error", {}).get("code") == "authentication_required"
    except (ValueError, AttributeError, UnicodeDecodeError):
        return False


def _check(
    client: SmokeClient, config: SmokeConfig, *, name: str, path: str,
    authenticated: bool,
) -> CheckResult:
    request_id = uuid4().hex
    headers = {"Accept": "application/json", "X-Correlation-ID": request_id}
    if authenticated:
        headers["Authorization"] = f"Bearer {config.token}"
    try:
        response = client.request(
            "GET", f"{config.base_url}{path}", headers=headers,
            timeout=TIMEOUT_SECONDS,
            max_body_bytes=0 if authenticated else CONTROL_BODY_LIMIT,
        )
        status = response.status if isinstance(response.status, int) and 100 <= response.status <= 599 else 0
        response_headers = {key.lower(): value for key, value in response.headers.items()}
        matching_id = response_headers.get("x-correlation-id") == request_id
        expected_status = 200 if authenticated else 401
        passed = (
            status == expected_status
            and matching_id
            and _headers_are_safe(
                response_headers,
                remote=urlsplit(config.base_url).hostname not in {"localhost", "127.0.0.1"},
            )
            and (authenticated or response_headers.get("www-authenticate") == "Bearer")
            and (authenticated or _control_is_authentication_required(response.body))
        )
        return CheckResult(name, passed, status, request_id if matching_id else "-")
    except Exception:
        # Client errors can include URLs, headers, or response text; never render them.
        return CheckResult(name, False, 0)


def run(*, environ: Mapping[str, str] | None = None, client: SmokeClient | None = None) -> list[CheckResult]:
    """Run read checks or fail closed before sending any request."""

    try:
        config = _load_config(os.environ if environ is None else environ)
    except SmokeConfigurationError as error:
        return [CheckResult(str(error), False, 0)]
    if config.write_mode:
        # There is no cleanup API for persistent parcel hypotheses.
        return [CheckResult("WRITE_MODE_UNSUPPORTED", False, 0)]

    http_client = client if client is not None else UrllibSmokeClient()
    property_path = f"/v1/properties/{config.property_id}"
    requests = (
        ("authenticated_root", "/v1", True),
        ("property", property_path, True),
        ("property_graph", f"{property_path}/graph", True),
        ("property_evidence", f"{property_path}/evidence", True),
        ("unauthenticated_control", "/v1", False),
    )
    return [
        _check(http_client, config, name=name, path=path, authenticated=authenticated)
        for name, path, authenticated in requests
    ]


def main(*, environ: Mapping[str, str] | None = None, client: SmokeClient | None = None) -> int:
    try:
        results = run(environ=environ, client=client)
    except Exception:
        results = [CheckResult("runtime", False, 0)]
    for result in results:
        print(result.line())
    return 0 if all(result.passed for result in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
