import { useMemo, useState, type ReactNode } from "react";
import type { JourneyPropertyContext } from "@/lib/location-market-journey";
import type { JourneyAffordabilityContext, JourneyPriceContext } from "@/lib/price-affordability-journey";
import { buildDecisionAttentionItems, buildJourneyDecisionContext, type DecisionAttentionItem } from "@/lib/decision-case-journey";
import { DecisionAttentionPanel } from "@/components/guided-journey/decision-attention-panel";
import { DecisionCaseActionSelector, type DecisionCaseAction } from "@/components/guided-journey/decision-case-action-selector";
import { DecisionCaseStatusStrip } from "@/components/guided-journey/decision-case-status-strip";
import { DecisionReadinessSummary } from "@/components/guided-journey/decision-readiness-summary";
import { JourneyDecisionContextHeader } from "@/components/guided-journey/journey-decision-context-header";

export function DecisionCaseStage({ propertyContext, priceContext, affordabilityContext, renderCommandCenter, renderSavedCases, onBackToProperty, onBackToPrice, onBackToAffordability, onNavigateToAction }: { propertyContext: JourneyPropertyContext; priceContext: JourneyPriceContext; affordabilityContext: JourneyAffordabilityContext; renderCommandCenter: () => ReactNode; renderSavedCases: () => ReactNode; onBackToProperty: () => void; onBackToPrice: () => void; onBackToAffordability: () => void; onNavigateToAction: (action: DecisionAttentionItem["action"]) => void }) {
  const [activeAction, setActiveAction] = useState<DecisionCaseAction>("none");
  const context = useMemo(() => buildJourneyDecisionContext({ propertyContext, priceContext, affordabilityContext }), [affordabilityContext, priceContext, propertyContext]);
  const attentionItems = useMemo(() => buildDecisionAttentionItems(context), [context]);
  function handleAttentionAction(action: DecisionAttentionItem["action"]) { if (action === "case") setActiveAction("new"); else onNavigateToAction(action); }
  return <div className="min-w-0 space-y-4"><section className="min-w-0 rounded-xl border border-cyan-100 bg-cyan-50/60 p-4"><p className="text-[10px] font-bold tracking-wider text-cyan-700">第 5 步，共 5 步</p><h2 className="mt-1 text-xl font-black text-slate-950">資料是否足夠，我接下來要做什麼？</h2><p className="mt-1 text-xs leading-5 text-slate-600">先整理目前已知資料、缺失項目與阻擋事項，再由你決定是否建立案件、補件、看屋、比較或列印。</p></section><JourneyDecisionContextHeader context={context} onBackToProperty={onBackToProperty} onBackToPrice={onBackToPrice} onBackToAffordability={onBackToAffordability} /><DecisionCaseStatusStrip context={context} /><DecisionReadinessSummary context={context} /><DecisionAttentionPanel items={attentionItems} onNavigate={handleAttentionAction} /><DecisionCaseActionSelector activeAction={activeAction} onSelect={setActiveAction} />{activeAction === "new" && <section aria-labelledby="embedded-case-workspace-heading" className="min-w-0 rounded-xl border border-cyan-100 bg-white p-4"><h3 id="embedded-case-workspace-heading" className="text-base font-black text-slate-950">Property Case Command Center</h3><p className="mt-1 text-xs leading-5 text-slate-600">案件欄位與人工工作區已開啟；既有列印 guard、缺失資料與各 section 仍沿用。</p><div className="mt-4">{renderCommandCenter()}</div></section>}{activeAction === "saved" && <section aria-labelledby="saved-case-list-heading" className="min-w-0 rounded-xl border border-stone-200 bg-white p-4"><h3 id="saved-case-list-heading" className="text-base font-black text-slate-950">Saved Cases</h3><p className="mt-1 text-xs leading-5 text-slate-600">請明確選擇案件；不會自動選第一筆或最新案件。</p><div className="mt-4">{renderSavedCases()}</div></section>}<section aria-labelledby="decision-print-heading" className="min-w-0 rounded-xl border border-stone-200 bg-white p-4"><h3 id="decision-print-heading" className="text-base font-black text-slate-950">列印／匯出</h3><p className="mt-1 text-xs leading-5 text-slate-600">建立案件並符合既有 print guard 後，才可由使用者明確點擊列印目前摘要；資料不完整時保留資料不足聲明。</p><button type="button" disabled className="mt-3 rounded-lg border border-stone-300 px-3 py-2 text-xs font-bold text-slate-500">尚未建立可列印案件</button></section><nav aria-label="案件流程返回" className="flex flex-col gap-2 sm:flex-row"><button type="button" onClick={onBackToProperty} className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">回到第一步找物件</button><button type="button" onClick={onBackToPrice} className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">回到價格步驟</button><button type="button" onClick={onBackToAffordability} className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">回到資金步驟</button></nav></div>;
}
