"use client";

import { attentionCategoryLabel, type DecisionAttentionItem } from "@/lib/decision-case-journey";
import { useExperienceLocale } from "@/components/experience-locale-provider";

export function DecisionAttentionPanel({ items, onNavigate }: { items: readonly DecisionAttentionItem[]; onNavigate: (action: DecisionAttentionItem["action"]) => void }) {
  const { copy } = useExperienceLocale();
  const ordered = [...items].sort((left, right) => ["blocked", "missing", "unknown", "partial", "pending"].indexOf(left.category) - ["blocked", "missing", "unknown", "partial", "pending"].indexOf(right.category));
  return <section aria-labelledby="decision-attention-heading" className="min-w-0 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold tracking-wider text-amber-800">ATTENTION FIRST</p><h3 id="decision-attention-heading" className="mt-1 text-base font-black text-amber-950">{copy("journey.attentionTitle")}</h3></div><span className="text-xs font-bold text-amber-800">{ordered.length ? `${ordered.length}` : copy("journey.attentionNone")}</span></div>{ordered.length ? <ul className="mt-3 grid gap-2 md:grid-cols-2">{ordered.map((item) => <li key={item.id} className="min-w-0 rounded-lg bg-white/80 p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-[10px] font-bold text-amber-800">{attentionCategoryLabel(item.category)}</p><p className="mt-1 break-words text-xs font-bold text-slate-900">{item.label}</p><p className="mt-1 text-[11px] text-slate-600">{item.status}</p></div><button type="button" onClick={() => onNavigate(item.action)} className="shrink-0 rounded-lg border border-amber-300 px-2 py-1.5 text-[10px] font-bold text-amber-900">{copy("journey.attentionNavigate")}</button></div></li>)}</ul> : <p className="mt-3 text-xs leading-5 text-amber-900">{copy("journey.attentionEmpty")}</p>}<p className="mt-3 text-[11px] leading-5 text-amber-800">{copy("journey.attentionNote")}</p></section>;
}
