import { useMemo, useState, type ReactNode } from "react";
import type { JourneyPropertyContext } from "@/lib/location-market-journey";
import type { JourneyAffordabilityContext, JourneyPriceContext } from "@/lib/price-affordability-journey";
import { buildDecisionAttentionItems, buildJourneyDecisionContext, type DecisionAttentionItem } from "@/lib/decision-case-journey";
import { DecisionAttentionPanel } from "@/components/guided-journey/decision-attention-panel";
import { DecisionCaseActionSelector, type DecisionCaseAction } from "@/components/guided-journey/decision-case-action-selector";
import { DecisionCaseStatusStrip } from "@/components/guided-journey/decision-case-status-strip";
import { DecisionReadinessSummary } from "@/components/guided-journey/decision-readiness-summary";
import { JourneyDecisionContextHeader } from "@/components/guided-journey/journey-decision-context-header";
import { useExperienceLocale } from "@/components/experience-locale-provider";

export function DecisionCaseStage({ propertyContext, priceContext, affordabilityContext, renderCommandCenter, renderSavedCases, onBackToProperty, onBackToPrice, onBackToAffordability, onNavigateToAction }: { propertyContext: JourneyPropertyContext; priceContext: JourneyPriceContext; affordabilityContext: JourneyAffordabilityContext; renderCommandCenter: () => ReactNode; renderSavedCases: () => ReactNode; onBackToProperty: () => void; onBackToPrice: () => void; onBackToAffordability: () => void; onNavigateToAction: (action: DecisionAttentionItem["action"]) => void }) {
  const [activeAction, setActiveAction] = useState<DecisionCaseAction>("none");
  const { t } = useExperienceLocale();
  const context = useMemo(() => buildJourneyDecisionContext({ propertyContext, priceContext, affordabilityContext }), [affordabilityContext, priceContext, propertyContext]);
  const attentionItems = useMemo(() => buildDecisionAttentionItems(context), [context]);
  function handleAttentionAction(action: DecisionAttentionItem["action"]) { if (action === "case") setActiveAction("new"); else onNavigateToAction(action); }
  return <div className="min-w-0 space-y-4"><section className="min-w-0 rounded-xl border border-cyan-100 bg-cyan-50/60 p-4"><p className="text-[10px] font-bold tracking-wider text-cyan-700">{t("journey.step")} 5 / 5</p><h2 className="mt-1 text-xl font-black text-slate-950">{t("journey.decision.question")}</h2><p className="mt-1 text-xs leading-5 text-slate-600">{t("journey.decision.description")}</p></section><JourneyDecisionContextHeader context={context} onBackToProperty={onBackToProperty} onBackToPrice={onBackToPrice} onBackToAffordability={onBackToAffordability} /><DecisionCaseStatusStrip context={context} /><DecisionReadinessSummary context={context} /><DecisionAttentionPanel items={attentionItems} onNavigate={handleAttentionAction} /><DecisionCaseActionSelector activeAction={activeAction} onSelect={setActiveAction} />{activeAction === "new" && <section aria-labelledby="embedded-case-workspace-heading" className="min-w-0 rounded-xl border border-cyan-100 bg-white p-4"><h3 id="embedded-case-workspace-heading" className="text-base font-black text-slate-950">Property Case Command Center</h3><p className="mt-1 text-xs leading-5 text-slate-600">{t("journey.decision.description")}</p><div className="mt-4">{renderCommandCenter()}</div></section>}{activeAction === "saved" && <section aria-labelledby="saved-case-list-heading" className="min-w-0 rounded-xl border border-stone-200 bg-white p-4"><h3 id="saved-case-list-heading" className="text-base font-black text-slate-950">Saved Cases</h3><p className="mt-1 text-xs leading-5 text-slate-600">{t("state.empty.next")}</p><div className="mt-4">{renderSavedCases()}</div></section>}<section aria-labelledby="decision-print-heading" className="min-w-0 rounded-xl border border-stone-200 bg-white p-4"><h3 id="decision-print-heading" className="text-base font-black text-slate-950">{t("evidence.details")}</h3><p className="mt-1 text-xs leading-5 text-slate-600">{t("trust.noPurchase")}</p><button type="button" disabled className="mt-3 rounded-lg border border-stone-300 px-3 py-2 text-xs font-bold text-slate-500">{t("state.not_assessed.heading")}</button></section><nav aria-label={t("journey.decision.title")} className="flex flex-col gap-2 sm:flex-row"><button type="button" onClick={onBackToProperty} className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">{t("journey.property.previous")}</button><button type="button" onClick={onBackToPrice} className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">{t("journey.price.previous")}</button><button type="button" onClick={onBackToAffordability} className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">{t("journey.affordability.previous")}</button></nav></div>;
}
